Rem
Rem emaas_dashboards_seed_data.sql
Rem
Rem Copyright (c) 2013, 2014, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    NAME
Rem      emaas_dashboards_seed_data.sql 
Rem
Rem    DESCRIPTION
Rem      Dashboard Framework seed data sql file.
Rem
Rem    NOTES
Rem      None
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    guochen  10/29/15 - update tiles time control support
Rem    miayu    10/26/15 - move to 1.4.0 folder
Rem    miayu    10/19/15- Created
Rem

DEFINE TENANT_ID = '&1'
SET FEEDBACK ON
SET SERVEROUTPUT ON

DECLARE

BEGIN  

--Rem screenshots for OOB ITA Dashboards
UPDATE EMS_DASHBOARD
SET LAST_MODIFICATION_DATE   =NVL(LAST_MODIFICATION_DATE,CREATION_DATE),
  LAST_MODIFIED_BY='Oracle'
WHERE tenant_id   ='&TENANT_ID'
AND dashboard_id <=1000;

commit;
DBMS_OUTPUT.PUT_LINE('Update OOB Dashboard modification data in Schema object: EMS_DASHBOARD for tenant: &TENANT_ID successfully');

EXCEPTION
WHEN OTHERS THEN
  ROLLBACK;
  DBMS_OUTPUT.PUT_LINE('Failed to update OOB Dashboard modification data in Schema object: EMS_DASHBOARD for tenant: &TENANT_ID due to '||SQLERRM);   
  RAISE;
END;
/

DECLARE

BEGIN
  --Rem by default, OOBdashboards support 'auto' showing time control. 
  UPDATE EMS_DASHBOARD SET ENABLE_TIME_RANGE=2 WHERE TENANT_ID='&TENANT_ID' AND IS_SYSTEM=1;

  --Rem by default, TA tiles support time control, other tile do not support
  UPDATE EMS_DASHBOARD_TILE SET WIDGET_SUPPORT_TIME_CONTROL=0 WHERE TENANT_ID='&TENANT_ID' AND PROVIDER_NAME='TargetAnalytics';
  UPDATE EMS_DASHBOARD_TILE SET WIDGET_SUPPORT_TIME_CONTROL=1 WHERE TENANT_ID='&TENANT_ID' AND PROVIDER_NAME<>'TargetAnalytics';
  
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Update ENABLE_TIME_RANGE and WIDGET_SUPPORT_TIME_CONTROL in Schema object: EMS_DASHBOARD and EMS_DASHBOARD_TILE for tenant: &TENANT_ID successfully');

EXCEPTION
WHEN OTHERS THEN
  ROLLBACK;
  DBMS_OUTPUT.PUT_LINE('Failed to update ENABLE_TIME_RANGE and WIDGET_SUPPORT_TIME_CONTROL in Schema object: EMS_DASHBOARD and EMS_DASHBOARD_TILE for tenant: &TENANT_ID due to '||SQLERRM);   
  RAISE;
END;
/

DECLARE
  MPS_DSB_ID_1 CONSTANT NUMBER:=19;
  MPS_DSB_TILE_ID_1_1 CONSTANT NUMBER:=32;
  MPS_DSB_TILE_ID_1_2 CONSTANT NUMBER:=33;
  MPS_DSB_TILE_ID_1_3 CONSTANT NUMBER:=34;
  MPS_DSB_TILE_ID_1_4 CONSTANT NUMBER:=35;
  MPS_DSB_TILE_ID_1_5 CONSTANT NUMBER:=36;
  MPS_DSB_TILE_ID_1_6 CONSTANT NUMBER:=37;
  V_COUNT NUMBER;
  mps_screenshot CLOB:='data:image/png;base64,'||
''; --Add base64 encoded screenshot with size 320x170 px here. 

BEGIN  

  SELECT COUNT(1) INTO V_COUNT FROM EMS_DASHBOARD WHERE TENANT_ID='&TENANT_ID' AND DASHBOARD_ID=19;
  IF (V_COUNT>0) THEN
    DBMS_OUTPUT.PUT_LINE('MPS OOB dashboard have been added for: &TENANT_ID, no need to add again');  
  ELSE
    Insert into EMS_DASHBOARD (DASHBOARD_ID,NAME,TYPE,DESCRIPTION,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,IS_SYSTEM,APPLICATION_TYPE,ENABLE_TIME_RANGE,DELETED,TENANT_ID,SCREEN_SHOT) 
    values (MPS_DSB_ID_1,'Managed PaaS Cloud Services',0,'Managed PaaS Cloud Services',SYS_EXTRACT_UTC(SYSTIMESTAMP),null,null,'Oracle',1,4,0,0,'&TENANT_ID',mps_screenshot);--mps has type id:4

    Insert into EMS_DASHBOARD_TILE (TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,TYPE) 
    values (MPS_DSB_TILE_ID_1_1,MPS_DSB_ID_1,SYS_EXTRACT_UTC(SYSTIMESTAMP),null,null,'Oracle','Services Summary',1,1,0,0,'&TENANT_ID','4000','Services Summary','Services Summary','Managed PaaS Service',null,null,'Oracle',to_char(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS.ff3"Z"'),1,'MPS_SERVICE_SUMMARY_WIDGET','/region/portalsummary/servicesummary/js/servicesummary.js','/region/portalsummary/servicesummary/servicesummary.html','mpsUI','0.1','assetRoot',0,0,0);
    
    Insert into EMS_DASHBOARD_TILE (TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,TYPE) 
    values (MPS_DSB_TILE_ID_1_2,MPS_DSB_ID_1,SYS_EXTRACT_UTC(SYSTIMESTAMP),null,null,'Oracle','Allocation Summary',1,2,0,0,'&TENANT_ID','4001','Allocation Summary','Allocation Summary','Managed PaaS Service',null,null,'Oracle',to_char(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS.ff3"Z"'),1,'MPS_ALLOCATION_SUMMARY_WIDGET','/region/portalsummary/allocationsummary/js/allocationsummary.js','/region/portalsummary/allocationsummary/allocationsummary.html','mpsUI','0.1','assetRoot',0,1,0);
    
    Insert into EMS_DASHBOARD_TILE (TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,TYPE) 
    values (MPS_DSB_TILE_ID_1_3,MPS_DSB_ID_1,SYS_EXTRACT_UTC(SYSTIMESTAMP),null,null,'Oracle','Backup Summary',1,1,0,0,'&TENANT_ID','4002','Backup Summary','Backup Summary','Managed PaaS Service',null,null,'Oracle',to_char(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS.ff3"Z"'),1,'MPS_BACKUP_SUMMARY_WIDGET','/region/portalsummary/backupsummary/js/backupsummary.js','/region/portalsummary/backupsummary/backupsummary.html','mpsUI','0.1','assetRoot',0,3,0);
    
    Insert into EMS_DASHBOARD_TILE (TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,TYPE) 
    values (MPS_DSB_TILE_ID_1_4,MPS_DSB_ID_1,SYS_EXTRACT_UTC(SYSTIMESTAMP),null,null,'Oracle','Patch Summary',1,1,0,0,'&TENANT_ID','4003','Patch Summary','Patch Summary','Managed PaaS Service',null,null,'Oracle',to_char(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS.ff3"Z"'),1,'MPS_PATCH_SUMMARY_WIDGET','/region/portalsummary/patchsummary/js/patchsummary.js','/region/portalsummary/patchsummary/patchsummary.html','mpsUI','0.1','assetRoot',0,4,0);
    
    Insert into EMS_DASHBOARD_TILE (TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,TYPE) 
    values (MPS_DSB_TILE_ID_1_5,MPS_DSB_ID_1,SYS_EXTRACT_UTC(SYSTIMESTAMP),null,null,'Oracle','Notifications Summary',1,2,0,0,'&TENANT_ID','4004','Notifications Summary','Notifications Summary','Managed PaaS Service',null,null,'Oracle',to_char(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS.ff3"Z"'),1,'MPS_NOTIFICATIONS_SUMMARY_WIDGET','/region/portalsummary/notificationsummary/js/notificationsummary.js','/region/portalsummary/notificationsummary/notificationsummary.html','mpsUI','0.1','assetRoot',0,5,0);
    
    Insert into EMS_DASHBOARD_TILE (TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,TYPE) 
    values (MPS_DSB_TILE_ID_1_6,MPS_DSB_ID_1,SYS_EXTRACT_UTC(SYSTIMESTAMP),null,null,'Oracle','Cloud Services',2,7,0,0,'&TENANT_ID','4005','Cloud Services','Cloud Services','Managed PaaS Service',null,null,'Oracle',to_char(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS.ff3"Z"'),1,'MPS_SERVICES_WIDGET','/region/serviceinstances/js/serviceinstances.js','/region/serviceinstances/serviceinstances.html','mpsUI','0.1','assetRoot',1,0,0);

    Insert into EMS_DASHBOARD_LAST_ACCESS (DASHBOARD_ID,ACCESSED_BY,ACCESS_DATE,TENANT_ID) 
    values (MPS_DSB_ID_1,'Oracle',SYS_EXTRACT_UTC(SYSTIMESTAMP),'&TENANT_ID');
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Add MPS OOB dashboard successfully for tenant: &TENANT_ID');  
  END IF;

EXCEPTION
WHEN OTHERS THEN
  ROLLBACK;
  DBMS_OUTPUT.PUT_LINE('Failed to Add MPS OOB dashboard to Schema object: EMS_DASHBOARD for tenant: &TENANT_ID due to '||SQLERRM);   
  RAISE;
END;
/

