Rem
Rem emaas_dashboards_seed_data_ocs.sql
Rem
Rem Copyright (c) 2013, 2014, 2015, 2016, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    NAME
Rem      emaas_dashboards_seed_data_ocs.sql 
Rem
Rem    DESCRIPTION
Rem      Seed data for Orchestration
Rem
Rem    NOTES
Rem      None
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    MIAYU       09/30/16 - Add OOB dashborads for Orchestration
Rem

DEFINE TENANT_ID ='&1'
SET FEEDBACK ON
SET SERVEROUTPUT ON

DECLARE
  V_COUNT                                NUMBER;
  V_DASHBOARD_ID                         NUMBER(38,0);
  V_NAME                                 VARCHAR2(320 BYTE);
  V_TYPE                                 NUMBER(38,0);
  V_DESCRIPTION                          VARCHAR2(1280 BYTE);
  V_CREATION_DATE                        TIMESTAMP(6);
  V_LAST_MODIFICATION_DATE               TIMESTAMP(6);
  V_LAST_MODIFIED_BY                     VARCHAR2(128 BYTE);
  V_OWNER                                VARCHAR2(128 BYTE);
  V_IS_SYSTEM                            NUMBER(1,0);
  V_APPLICATION_TYPE                     NUMBER(4,0);
  V_ENABLE_TIME_RANGE                    NUMBER(2,0);
  V_ENABLE_REFRESH                       NUMBER(1,0);
  V_ENABLE_ENTITY_FILTER                 NUMBER(1,0);
  V_ENABLE_DESCRIPTION                   NUMBER(1,0);
  V_SHARE_PUBLIC                         NUMBER(1,0);
  V_DELETED                              NUMBER(38,0);
  V_TENANT_ID                            NUMBER(38,0) := '&TENANT_ID';
  V_SCREEN_SHOT                          CLOB;

  V_DASHBOARD_SET_ID                     NUMBER(38,0);
  V_SUB_DASHBOARD_ID                     NUMBER(38,0);
  V_SUB_DSB_POSITION                     NUMBER(38,0);

  V_TILE_ID                     NUMBER(38,0);
  V_TITLE                       VARCHAR2(64 BYTE);
  V_HEIGHT                      NUMBER(38,0);
  V_WIDTH                       NUMBER(38,0);
  V_IS_MAXIMIZED                NUMBER(1,0);
  V_POSITION                    NUMBER(38,0);
  V_WIDGET_UNIQUE_ID            VARCHAR2(64 BYTE);
  V_WIDGET_NAME                 VARCHAR2(64 BYTE);
  V_WIDGET_DESCRIPTION          VARCHAR2(256 BYTE);
  V_WIDGET_GROUP_NAME           VARCHAR2(64 BYTE);
  V_WIDGET_ICON                 VARCHAR2(1024 BYTE);
  V_WIDGET_HISTOGRAM            VARCHAR2(1024 BYTE);
  V_WIDGET_OWNER                VARCHAR2(128 BYTE);
  V_WIDGET_CREATION_TIME        VARCHAR2(32 BYTE);
  V_WIDGET_SOURCE               NUMBER(38,0);
  V_WIDGET_KOC_NAME             VARCHAR2(256 BYTE);
  V_WIDGET_VIEWMODE             VARCHAR2(1024 BYTE);
  V_WIDGET_TEMPLATE             VARCHAR2(1024 BYTE);
  V_PROVIDER_NAME               VARCHAR2(64 BYTE);
  V_PROVIDER_VERSION            VARCHAR2(64 BYTE);
  V_PROVIDER_ASSET_ROOT         VARCHAR2(64 BYTE);
  V_TILE_ROW                    NUMBER(38,0);
  V_TILE_COLUMN                 NUMBER(38,0);
  V_TILE_TYPE                   NUMBER(38,0);
  V_TILE_SUPPORT_TIMECONTROL    NUMBER(1,0);
  V_TILE_LINKED_DASHBOARD       NUMBER(38,0);

  V_PARAM_NAME                  EMS_DASHBOARD_TILE_PARAMS.PARAM_NAME%TYPE;
  V_PARAM_TYPE                  EMS_DASHBOARD_TILE_PARAMS.PARAM_TYPE%TYPE;
  V_PARAM_VALUE_STR             EMS_DASHBOARD_TILE_PARAMS.PARAM_VALUE_STR%TYPE;
  V_PARAM_VALUE_NUM             EMS_DASHBOARD_TILE_PARAMS.PARAM_VALUE_NUM%TYPE;
  V_PARAM_VALUE_TIMESTAMP       EMS_DASHBOARD_TILE_PARAMS.PARAM_VALUE_TIMESTAMP%TYPE;

  CONST_NULL                       CONSTANT    CLOB:=null;
  CONST_ORACLE                     CONSTANT    VARCHAR2(128 BYTE):='Oracle';
  CONST_IS_SYSTEM                  CONSTANT    NUMBER:=1;
  CONST_OOB_DSB_AUTO_REFRESH       CONSTANT    EMS_DASHBOARD_USER_OPTIONS.AUTO_REFRESH_INTERVAL%TYPE:=0;
  CONST_OOB_DSB_ACCESS_DATE        CONSTANT    EMS_DASHBOARD_USER_OPTIONS.ACCESS_DATE%TYPE:=SYS_EXTRACT_UTC(SYSTIMESTAMP);
  CONST_OOB_DSB_IS_FAVORITE        CONSTANT    EMS_DASHBOARD_USER_OPTIONS.IS_FAVORITE%TYPE:=0;
  
  CONST_DASHBOARD_ID_ENT_HEALTH    CONSTANT    EMS_DASHBOARD.DASHBOARD_ID%type:=31; 
  V_TID                   NUMBER(38,0) := '&TENANT_ID';
  CURSOR TENANT_CURSOR IS
    SELECT DISTINCT TENANT_ID FROM EMS_DASHBOARD ORDER BY TENANT_ID;
BEGIN
  OPEN TENANT_CURSOR;
  LOOP
     IF (V_TID<>-1) THEN
        V_TENANT_ID:=V_TID;
     ELSE
       FETCH TENANT_CURSOR INTO V_TENANT_ID;
       EXIT WHEN TENANT_CURSOR%NOTFOUND;     
     END IF; 
  SELECT COUNT(DASHBOARD_ID) INTO V_COUNT FROM EMS_DASHBOARD WHERE DASHBOARD_ID=37 AND TENANT_ID=V_TENANT_ID;
  IF (V_COUNT=0) THEN
      V_DASHBOARD_ID              := 37;
      V_NAME                      := 'Orchestration Workflows';
      V_TYPE                      := 0;
      V_DESCRIPTION               := 'Orchestration';
      V_CREATION_DATE             := SYS_EXTRACT_UTC(SYSTIMESTAMP);
      V_LAST_MODIFICATION_DATE    := SYS_EXTRACT_UTC(SYSTIMESTAMP);
      V_LAST_MODIFIED_BY          := CONST_ORACLE;
      V_OWNER                     := CONST_ORACLE;
      V_IS_SYSTEM                 := 1;
      V_APPLICATION_TYPE          := 6;
      V_ENABLE_TIME_RANGE         := 1;
      V_ENABLE_REFRESH            := 1;
      V_ENABLE_ENTITY_FILTER      := 0;
      V_ENABLE_DESCRIPTION        := 0;
      V_SHARE_PUBLIC              := 0;
      V_DELETED                   := 0;
      V_SCREEN_SHOT               :=
'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAClAToDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD6nVV2jgdPSl2r/dH5VyfjCC0nvLD7Zrt3paiNkaNJ5YI5kZkLfOjLiQeWAp3ZCs/BzkJoBsY5xqsOtale2wt2iPmmZo3bzGZ5GB+TO4MBtVQoJX7vlqoB1u1f7o/Kjav90flVNtVs1gMzSkRhV'||
'cnY33SMg4x0wevbn0NVv+Ei0nyEmF7G0TsqIygkMzFgAMDk5VuPagDV2r/dH5UbV/uj8qiguoZ3KxPuIUP0OMEkAg9/un/JFTUAVNSjkNsfs+0SA5GQeeDxwR/Oo3WaOLFpGJJnIXMjHYnXLHnOPYdSR0HIv0U76WFbW5T1OS4gtS9lai5myP3eQuR9SR9PbOcHGKsuoG3AHWn02T+H/eFIZg/2lrTzSxReG9myaSNZZ72NY3QLIY3G3c2GKxggqCvmHhtvOe2teK0s2kPgyJ7hWkAhj1WMhgNm0hio4bdJ1wQEGR82B1s0nlQySbHfYpbagyxx2A9agS83XTQtb3KYcoHaP5G+VWyCO3zEZOOVI9MgGDb6r4jk06OWbwvBb3bT+W0D6irKsfl53llQ/wAfyYx0+YkDOJhqeutqU0I8MqtmtykSXD30YLxEPul2AHABCYXOSHzwRg9FRQAm1f7o/Kjav90flS0UAJtX+6Pyo2r/AHR+VLRQAm1f7o/KquoPNBaXMtnai6uY4WeK33hPNcA4XceFycDJ6Zq3Tf8Alr/wGgDnbvVPEH2aSWw8MI7KqMsN1fxxO+S4ZRsDruAWMjLYO88grzTn1vxXHJAsfgtJVfy/MZdViAjyil+q87WLqPXaDxnjsKKAMOxvdYmvrWK60SC2ge2SWaX7XvMcpDbo1ATDbSFG4lc7sgcGoNK1XW7rxHdWV54aNppUQPl6ibxH81uMAR4DAEHr+B5zjXjv/MaILaXYV9+WaPbtCtjJBOeeo4yRzUt48iQS+Sjl9hKlQG5xxwSM0ATbV/uj8qNq/wB0flWfLdXIu49sE3kCQxuPKByDtCsDv4GSTnB4B4GM1o0AJtX+6Pyo2r/dH5UtFACbV/uj8qzNbub+zsHl0nSxqdyJMCDz1h47nc3HHpWpVa5txdW00Jkmi3hl3wuUZcgjII788e+DQBhf2rr6Lb+Z4YTfIse5Y75WCMUkZ1ztH3SqDPAJfjpy3'||
'S9V8SXNnZyX3hSKzuJbpY5ojqSSCGEgky7gvzEEAbB1z1q1bw2i3D6aNW1BriJUTDyncCRu4Yj5iQhJ5OMHpk5tR6PsnjkbUdScKuCjT/K/Tk4A54zxjv24oAyJNY8TPqc9vbeEYxaqP3d1c6nGiuQV6qiuwBy5BwT8oyBniQat4iMV+x8KIHhkjW3T+0I/9IUuQ7Zx8m1cNg9SSOMZOpcaQZlhX+0dRj8tUXKTAF9oYZbjkndyfZemKRdH2tCRqOpfuypIM+d+05w3Hfv69KAKOlanrs6QHUvDQs2ZmWVY76ObZ80YUjgZBDyMehHlYwSwqC51jxGln5tv4S8ybbKfIbUIlbK7dgzgj5stk5+Ur3yDUyeFyhONe14qUVCpugei7d2SuQTyTg9Tn0xtrbFY2RbifBUAEsCV5JJBIzk5x+AxigDAsNX1+fw3dX1x4W8jU0/1Gn/boyZhtU8yYAXksOf7ue+KW31bxAdzXPhQoojD4jv4nYt+6ygBwM/PLySB+6HPzjHTUUAYXhy/1i/ti+uaCukSeUG2C7S4+cs4K5UDoqo2e+/H8POnVl/uN9KrUAQ6lezWNv5sdnJcxqF3CPJfJZRwoBJwCSfoOuThNO1GS6m8qeynt32FssrFcq20/NgDk8r3I5IHFJqWkpqLQSPd3tuY0ZB9mmMe4MVJzjn+HH4nvghsWkGKWN11LUTsAUK0wYEB93ORzwAueuB1ySTHLLmvfQmzve5bvJbmFc21sJ/lPHmbTuyAOoxt5Yk5yMcBicU3T7x7t7sNbSwJDMYkaRSvmgKpLAEDjcWXPQ7cgkEUt9YpeD5pJon2NGHicqQGKk8dM/KOcZHOOpqpo+jDS9gXUNQuVVCgW5m3jqMHoORjA+p9qs15ly2tqQ32s3dtr9vYR6Pd3FtMY1+1xfcjLCQsXzwFURcnJO50GPmzW3WeNLUarJfLdXi+YBvgEv7osAAGxjIOABgHHtmntp6tfxXf2m7DR9IxM'||
'fLb5SMFeh65+oFBBdooooAKbJ/D/vCnVVF3by3ctrHKrXEGxpUHVN2dufc4PH09RQBapHdY0Z3YKijJYnAApa87v9SuvEvidbDT3IsYyVburKCN0hx7gbfy43GpclG1zOpUULLq9vU6WfxTp8DbE82bH8UaYX6cmsmT4k6LBqk1jdpdwNFK8TymMMgKkjPBLdvSugsNA0+0jCmBJnx8zyjdn8DwPwqtrHhHQ9WikW50+BJHJYzQoI5Nxz824dTznnIz1FdUXRvaSYsH7RXeK67W6Gtp99a6jaJc2M8c8DjKuhyPp7H2pVvLZpDGtxCZA20qHGQeOMevzD8x6145cw3/AMNPE8MkMzT6XddVP/LRAeVI/vrng+/uRXr9nFY3EaXtrDAy3AEwlWMAuCAQ3TPZfyHpSrUeS0ou6ex11aXJZxd0y2SFBJIAHJJqrYahbagszWkvmCKQxP8AKRhgASOR70y70+3udRsruWDfcWvmeVLvI8vcuDx0OR60yzM00jlp7tArDCyRKuRtQ9cc9wfct6DGF09v6/z/AKRkzQpv/LX/AIDTqb/y1/4DQIdVLV9UtdJtGuL2QIoHyqPvOfRR3NWp5UggkmmYLHGpdmPYAZJry62jufGviR3mLxWicnaM+WnZR23H/E44xWc58ui3ZzYiu6dowV5PY14fHM17qsVva2scUDkqDJl3Y87enTPHHP1qLV/FGs6XeSiWzUoJB5bzwELgxocKRjvvz1/Su30zTbPTIPJsYEiTuR1b6nqeverZAIIIyDWapT5nJy6Wt033/QqMKvsXCUvefW23kcx4f8Y2OqyLBMptLpjtVGOVc+gb19jjqMZrp64Pxt4ThFtJqOlxpEYl3TQqMKVHVlHYgdR3+vXU8A61JqumPDcsz3NqQrO3JdTnaT78EfhnvVxk0+WRlRrTjP2Nbfo+51FFFYo123u7K0utNubI290WWOS5kaIkgkHahGWxtY4yPu9ccjaztc7bdTaps'||
'f8AF/vGq8E08pUhbZo9xDlJi23jt8vJzj04P5waxcG10y4lV40IYANIWCglgOdvP5UhEwuLr7e8TWR+zZUJOsqnOVYklTggAgLxkkt0ABNQeHL+XU9EtLydUWWZdzBAQByRxnNTrFei/eQ3URtCQRCYPnX5SCN+712kccfMOcjbneB/+RT03/rmf/QjVJe62PoblFFFSIKKKKACiiigBH+430qtVl/uN9KrUAULrVNPtdSjsrguszqjFyn7tN7FUDP0BZgVA6k1TvfE2iWMrx3b3cZR2jYmymIUqeckJwO4J4YcgkVuXF5DaQF5i+FUEhI2c4PoFBJ6VVOvaYI76Q3aeXY/8fD4O1DzxnHJ46DJ6eooAxr/AMY+HbDXzotzcTDUQ+wxJayP/wAsxJnKqRgKwz6Z545rROs6Osk8cl0sbwRvLIsiFdqIFLPyPujeuT0GT6HFiLXtOlvorOKdnnkDFdsTleGKnLY2jDDHJ68da06AOYk8VaAlxp8JuZN1+/lwH7PIFZtzKBnbgEsjADr36c1sWNxYX/n/AGK4hn+zymCby2DeXIACUbHRgCODzzV+igCL7PH6UfZ4/SpaKAIvs8fpSGJUKlRzmpqbJ/D/ALwoAqa5I8Oi6hLExSRLeRlYdQQpwa5b4WWyLpt5dDPmSTCM+gCqCMf99H8hXYX1ut3ZXFs5KrNG0ZI6gEY/rXm/gDX7XS9cuPD19colzJIVWPOQsq4BUsOMt0HPVCOpGZ9nKc04q9jirNRrwlLbVfM7gRXUF7NCyXVzZzgkTfaFDRl2OVx8pCqMYIJbnHbJpz20uqawN8WtaebYkrMl0FilwWC5QMVIO7cARn5QHAG0N0VFUdpx3xatop/BF3JIuXt3jkjOejFwv8mNWPhfK83gbTDIzOyiRMsc8CRgB9AMD8Kt+M7FdX0WbTWmeHzsEsoB6HIzntkDpjp1pvhGGy0XSrbRE1G3uLq3JDKGVXy2ZMFMkg7Wz9OaqGKpT'||
'puhF3lF6/d9xu5L2PK97k+rWccuv6NePbxSNaicrIXYPHuQA7VB+bPQ5Bx2xT9JuDc3Vw3k6nBtYrsulwnH8S8ng5H5dBzT9Snkj1TT40ey2yCXMcjYnfC5Hk84PvntVKC1n061hnhh1m9uAi5imu0JJ2t9/L7epAO3vjAODUJyd+bbp6f8Pcw5FHVddf0/Q6Cm/wDLX/gNY2kW11C8MTvqqxrFuaW6mikLtu+62M4OBnK4GGPoMbP/AC1/4DTAxPHMjx+Fb9o2KsQq5BxwXUEfiCRWV8LokXRLmUKvmPcFS3cgKuB+p/Ot/wAT2LajoF7bR5MjJuQDqWUhgPxIArk/hfqUSx3OmyMqyM/nR5PL8AMPwwD+fpWMtKiucNT3cVFvqvxOn1OO7j1W1uYIr25hRJGeOG4RBuwAqlGwGzljksMED14r3tu090NONvrSQmEgXcV3tAG1QRuD7t3AGW+bJJGRuI6CitjuGQoyQRpJIZWVQrOwALnHJIHHPtXmvgsJp3ji6s03Mn723Vj1wrZyf++f1r0TU72LTtPnu5z+7iXcQOpPYficCuC+GtvNdaxe6lP8wClS7DlnYgkjt0Bz9RWNTWUUcOJ1rU4re/4Ho1YNvqEV/o9peXMC2rsztFHqiCKRHUPg7ecHCk5Bztya3qwF0qSWGyZGimWFJUYanb+bMwdhkb8jaMBh0OQR6YOjceZLr/X/AADt1v5f1/wTT0ppJbVZrg2j3LZV3tjlCFZsAE88c/jmodZljh0q5knijmjVgWSSRY1PzDqzEAfjV62QxW8UbBAVQKQgwvA7DsKVACGBAPzVQys8du2qK/kyfaVVf3oDBdvz4BPRurfLzgkHHQ1m+B8f8Ipp2R/yzPb3NbbMwkVRGxU9WBGBwf8AAfmPeuI+Gl8q20lgEJkb9+GzxgRxLj68itIq8WUleLO5+X0/Sj5fT9KjhmEyb4ijruK5DdwSCOnYgin5f+6v/fX/ANasyRfl9P0o+'||
'X0/Sky/91f++v8A61GX/ur/AN9f/WoAX5fT9KPl9P0pMv8A3V/76/8ArUZf+6v/AH1/9agAbGxselV6sHOxsgDjsar0ATqgJR8tkLjGTjnHb8P85p9Z01jDNqtpcNbv5kcTAXCOVxyuEbDAkHJOMEcHOOMy31gLuW3k+03cDQyrJ+5lKh8fwsOhU9xQBcorNsdFs7FLhbb7SBcD94WupXJ4xkFmJBxgZGDwPQVpUAFFFFABRRRQAU2T+H/eFOpkhGVHfIoAfXnnxO+H6+I1bUtK2RavGvKnhbgDoCezAcA/QHjBHodFaUqsqUuaG5lWowrR5JrQ8U0nx54q8OXEOneJrBHjT92JrwmFjghc+ZghwO5AYnrk1Y1j4ma5fpBb+GrC1a5mjYutuXu5YjgHpsUAjJ7MPyr2Oiuj6zSb5nTV/XT7jm+q1UuVVXb01+84/wCHema5a6OD4pk8y8EjMgaTzHC5/jbkE5yRgngj0xXW+VHuLeWm4ncTgdcYz9ccU+iuLlipSnGKXM7u3c7IR5IqN727lK7tPP1Cyn8q2cQ+Zl5EzIm5cfIccZ79OKltrOK2x5RmwAQA8zuOcdiT/dH059TmxRVN3Gla4U3/AJa/8Bp1MBBl4OeP60hj68+8X+Gri0vTq+iiQnf5kkaZLI2fvL6j1Hb6dPQaKmcFJWZjWoxrR5ZHn2m/ESGG1UazBJvXC+bCAdxJxkqcY7f/AFqnHxQ0CaZ7eyM9xdCITCMKF4I4ySeAcjsetdNqPh/StRk8y7sonkzkuuUY/Urgn8aqp4Q0JHV1sASpyN0jkfiCcGotUWlzBQxUVZST8/6Rw91dax40vRDBEEtojnYDhI89Cx7nH9cDrXpGiaZDpGmxWkGCF5d8YLt3Y/56YFWreCK2hWK3iSKJeiIoUDv0FSU4Q5dXqzShh/Ztzk7yfUKKKK0OkKbH/F/vGnEgAknAHemx/wAX+8aAB0DMjEsCh3DDEZ4I59Rz0Pse1cta+'||
'HrTS4mu7G41BJYwVC8DcchdpynQlF5xjHPTmuropptbDTaMhLIWtuYIdQuVDSEkZjBBdixOdnXkmmLcwRZifWLgSIzRhSELOUXcwX5MuQvJxnuOoNbVVHs2M0kiXdwhdi2AVIHyhcDIOBxnjuTnPSkIoSXaQWomutUlhHkeexcxhVHA5YpgDJHPenzSRiWW3m1a4iYFI8ny1yXyFAOzG4kHjOenqKvXVvNJbulvdPBKU2o4RWCns2COfpVIaO/9o/aXv7hkKrui2oA7jcN7YXrhlAxj7gznAwAR29yrafDdnUrsWzo0iybFIKAZDH93wCozz64qNNTtGRJP7akWB7dLpZG8tR5bnClsp8ucjGcZ5x901tQReTGEDMwHTd2HpSiKMAARoAAABjsOg/CgClplxHOt8sdzJcGGZonMmAVYKMrgAY9ffOehFTVMVRA5GAXOT7nH+A/SoaAIheRG/wDsC3lv9t8rz/s3mL5vl5279vXbnjPTNWds398f5/Cs7WLHQnVbvXLXTG2qq+deRxnAGcDc3pubH+8fWka90FTbwi806M+agiRJkQl9u9QADySnzY7qfSgCbTtSttTtftOm6haXdvv8vzbeZZE3dNuRkZ56VNPOLe0kup7mGK1jQyvM7hUVAMlixGAAOc1WistDkMbRW2msWkCIVjQ5kjwQB/tL5S8dR5Y/u8W302xkd2eztmZ0aJiYlJZGOWU8cgnkjvQARyNK8qRzxu0TbJArAlGwGweODhgcehHrUm2b++P8/hWS9h4a0/UEke00e2vvvqxjiSToTkHGeiN+Cn0qxoVzolxbvHoM+mywQOUZbJ0ZY3HUELwD7UAXts398f5/CjbN/fH+fwrPs9Z0JbAzWepaYLKPJ3xTx+WvzYPIOB8xx9TVhNY0ySF5U1GzaJIxKzidSqoSQGJzwMqwz6g+lAFjbN/fH+fwqvFYiK7nulz584UOzSE8LnaADwMZPT1pZ9X023x9o1CziyNw3'||
'zquR8vPJ/20/wC+l9RVqGWOeFJYXWSKRQyOhyrA8ggjqKAGbZv74/z+FG2b++P8/hUV5qdhZTJFe31rbyujyKksqozKoyzAE8gDknsKsQyxzRLJC6yRsMqyHII9jQAzbN/fH+fwo2zf3x/n8KmooAh2zf3x/n8KNs398f5/CpqKAIds398f5/CjbN/fH+fwqaigCErMRjePz/8ArVXsbEWNusFt8salj8zlySzFiSTknJJPNXqz7zW9KstQgsLzU7G3vp8eTby3CJJJk4G1ScnJBHFAFrbN/fH+fwo2zf3x/n8KrR61pcrRLHqVk7SqrxhZ1JdW3YI55B2Pg/7Lehq5BNFcQRz28iSwyKHSRGDKykZBBHUEd6AGbZv74/z+FG2b++P8/hU1FAEO2b++P8/hRtm/vj/P4VJI6RrukZVXIGWOBknAqoNX00yvENQszKj+WyecuVbcq7SM9dzKMerAdxQBPtm/vj/P4UbZv74/z+FQnVNPDxIb61DyhTGvnLl92MY55zkY+tW1YMoZSCpGQR0NAFLULH+0LSS1uiWgkGHVXKZHpkYOKsBJh0YD8f8A61TUUAQ7Zv74/wA/hRtm/vj/AD+FTUUAQ7Zv74/z+FG2b++P8/hU1FAEO2b++P8AP4UbZv74/wA/hU1FAEO2b++P8/hRtm/vj/P4VNRQBQuLETXVvczZaW33GP5yAMggnaOCcEjn1qWrL/cb6VWoAdctbCBEvGhCTfugspGHJH3cHrnHSsq9s/DLRrbXttoxjt18lYpkixEuwvsAPQbAWx/dGelaF9p9rqEcK3sKzJG29VZjtzgjkdDwTwc9aq3Xh/SbmdpprKEzNuzIGKsMoVOCORlSc/n15oAktYtF0O28q0j07TrcK8+yMJCoUbQz4GBgZXJ9x7Vfhnim3eTLHJtJU7GBwQSpH4EEfUGqsum2cjBmhUMAwDKxUjcckgjnOec9eT6mprW1htjIbeJULkliD1OSf5k/yoAig'||
's9N+3Xtxb29n9skZVupERfMZlUbQ5HJIUrjPYiqMXhTw5BJFNDoOkRyQOJY3WzjBjcdGBxwRgcj0qzfaJp2oNIby0SYuctuY88KP5Kv+SaF0TTVeVxYweZKUaVyMtKUGFLnq2Ae+aACw07SLOR4tPs7C3kDMzJBEiHcQCxIA6/MCf8AeHrVW40vw1OgtLix0eRIZEhELwxEI/l4VNpHB2NwOu0+hq1HomnRpKi2se2WTzZAWJ3PjG4574xz14HoKcdJsDgG3jwro6LuOEZVCqVHRcAAcYoAaNL0ea0ewFjp8lrEqwNbeShRAFG1CuMABduB6Yq/bwxW0EcNvGkUMahEjRQqqB0AA6Csy98P6XfBFubKN1jkWRV3EAMq7V4HYDjHTk+prRtYI7S1ht7dAkMKCNFyThQMAflQBTu4tIn1Bku0sJb4QEFZQjSCFmx0POwkY9CRUxurCxSztzPa26y4ito96oHwOFQd+OwpLnTrS5neS5hWV3j8pldiVK8/w9O55xnnFRXWkWFytos9tGVtSPIUMQFxjAAHXoOPYUATnUbIRzuby22W6GSZvNXEagsCzHPABRxk/wB0+houdRsrWQx3N5bQyBdxWSVVIGHbOCemI5D9Eb0NMl060lSdZY96ypsfdIx+UFiMHPGCxxjGOMdBhv8AZloJxLsYSeZ5ufOblueTzzwcY6YCjoowAWri5gtrZ7i4mjit41LvLIwVVUdyTwB71FHqVjKJjFeWziAFpSsqnywGZSW54GUcc91YdjSS2FtJafZ5olkgGTiRi2M5zgnkdSPYcdKY2m2Tw3MbQRslwrJNliS6sWJUnrjLNgdsnGKAG2et6VfRTSWWp2NxHCcSNFcI4Q/7RB4/GnHWNMEEs51GyEMMjRSSeeu1HUEspOcAgAkjsBVWz8P6RaIRa2NuhyD5gOXBHQ7/AL3A4HPA4qwNMshDPE0QeGZ2eWOSRnVixBbIJIxx06dfU0ASWOqaffySR2N9a'||
'XMkYy6wzK5UZI5APHII/A1FdRaSdVhmuo7A6mqeXE8ip5wRsttUnnB8tmwP7hPal0zS7HTWkOn28cG8AMsbEKcd9vTPqep71Zkt0km3uX3Yxt81gp4Yfdzg/ePbsPQYAMzUbLw7qsgbUrbSb2QRpKDcRxyEJ85Ruc8f6wg/72O9XLS/0zDW1nd2eLcrCYopF/dHJULgHjlWUD1UjtTvsFtsVQrAJGI0xKw2DBGV54OGPzDnpzwKRdPtREI/LDKrBvnkZjkMWHJOepNADrrU7C0iMl3fWsEYYqWllVQCASRknqArH/gJ9KhuNc0m2DG51SwhCtsJkuEXDbmXHJ67kcfVWHY0+LTLKG5e4it445nfzJHUkF2wRlvXhm6+tMn0qzmUeasjYIYMbh9ykEnIOcg84yO2B0AFAF2eWKFA08iRoWVAXYAFmIVRz3JIAHckVl23hjQ7Z75odIsVN9IJbkeSpEjAAAkEY7Zx0ySepJOpPEsyBZRlQysMMRyCCOnuBUnPoPzoAqyadZSQiGSztmiEJtwjRKVERABTGPunA46cCrEUaQxJFEixxooVUUYCgdAB2FO59B+dHPoPzoAKKKKACiiigAooooAKKKKACiiigBH+430qtVl/uN9KrUAQ6jplvqkMMd9AJo423qpkZQTjHIHB4J4ORVaTw7pz3U9z9jCTzgrI8c7oWBXaRwR2x+IB6gGr1/YW2pWRtr2ISwMBlSSP5UxdJslvzeiAfaTEYd+4n5C24jGccnnpQBFcaNZ3K4uLVZD5Tw7mlYsUYgsM9eSo/Kn6dpVpps93NY2kMMt3IZZ3VjmRiSck/Vj+dKNIsfs32eS2SaPa6HzyZWKv98FmySD3yeauqiqSVUAt1PrQBk6h4f0/UVuFvLQSLcP5kqid1DttVQxAI52ooz7e5p6aHYpIzrarvYxl2MzkvsBC7v72AT1zzz15qTVtGsNXgaHUYPOiYhihkYDI6Hgjn3+lMj0LT455Jo4XS'||
'SRo3crM4DFFKrkA4IAPTp36igCGHw5p0MDwx2mI3k81gbiQ5fbt3cnrjv7A9QKkfQrBmLGzjBMqT/LIwAdECKQB0wqgcelMg8M6Tb2n2aC08uESmYKsrjDldpYHOQcVdu9Ms7xLZbiBXW2cSRDJG1gMD69eh4oAp3Xh/T7qOWOa0BjlkSWRFndVdlVVUkAgHAReOnyitOFGhhSJF+VFCjdIWOB6k8k+5qlf6LY39nLa3MTNBL5e9PMYA7CCO/HQAkckVogYAAHA4oAzbzRrK8u5Lm6s4pZpIRbuzOeYwSQMdP4m568mor3w/p96unrc2aMLAhrbErr5RGMEYx6DrV7UbC11K1e3voEmhcYKt9CPw4J5FVX0OxeGKF438iGNY4o1kK+WFZWGCMNnKIckn7vucgD/AOyrbfcOYSZJ0WN3M7ltqszKAeq4LsRjGM8YwKa+jWklwk7wFpkm89WM78Phhnr/AHWK46bcDoABaayjMitl8BgxUuWVsYxwc4wQCMY5HucvNtEfM+QDzGDOQSCxGBz68KB7gYoAqz6XbXFmtrcW6zQqSVEkjMyk5Bwx5HDEcHgHHTilGmW4s5bVYAsEru7qsrDLOxdjnqMsSfxpbnTLe7ieG7UzwEAJG+MR/KVO0gbgSCec9zUt7ZR3ixrMX8tHWQopxuKkMuT14IB4I6c5HFAGXY+F9JsLVLe006KJEGEIkfenJb5X+8OSTwas2Oi2diJBa2+wSTNcOPPchpGYMzHJ65Ufr6nLv7E0/Kn7MNyIiI29soF6bTn5T0yRycDOcVOlhEpiBaRkiACI7lsEHO7J5Le5J/U5AINO0i106Z5bOAxM6LGR57lSFAUfKeM4AGcZqxLaiWbzXDlsBdoncLgBh90cfxHtzgf3RiOx0mzsJfMtImjbYIyPMYggKqjIJxkBFGevX1ObTwpIWLgtuUKQWOMc9ug69fp6CgCjJpFs6RKYnAii8mMrcyKUXaV+Ug5Bwx+Yc9OeB'||
'gh0m1hhSKO3ARHDqPOckMGL5z1+8xP41ZnsoZvLLiTdGrKrLKysAwweQc//AFwD1ApTZW+YysYTy9oXYxXaFzgDHbk8dD0oAqSaNZyQ3kT2qGO83+ePNYb9wIY+xIJGRTTolmY1RYXTazOGjuZEbczMxO4EHksx69zUtjo9jYteNbQbftkrTTq0jMru2cnBJAznoOKsy2kUssMjhi0LmRMSMMNgjOAeeCevrQAl1brdRLHcRI6K6SAFj95GDKenZlB/Cpsv/dX/AL6/+tTqKAG5f+6v/fX/ANagF88quP8Ae/8ArU6igAooooAKKKKACiiigAooooAKKKKAEf7jfSq1WX+430qtQAl9YWupWZt72ESxMMEEkH8xyKji0ewiu1uY7ZVmWH7OpBOBHu3bQucdfan6jptpqloIL6ESxcHGSpB9QRgioU0LTY7gzR2wWQwG2+V2AEec7QM4GO3p0HFAD9M0iy0y2W3s4mWFWLKryNJtJ64LE4HJ4HqfWm6VotjpU13LYxOkl3IZZmeV5C7ZJz8xOOWPApItE0+K2FvHARbhy4i8xtvOcrjONvP3fu9OOBVuK0ghu57mKMLPOFErD+PbnGffBxn6egoAqapoenapIJL62EsoUKr7mVlAOcAggjnB464Gegw9dJs0iEcaSRoHVwI5XQZVQoHykfKAB8vTvjNOvdLtb2QyTrLvKhd0czxnAOeqkY//AFelPawgaIx5mClw/wAkzryBjsRgcdOntQBTh8OaTBE8dvaCFXkMpMbshDEY4IOQMcYHHWpNR0PTNSNmb+ziuGtDmBpBuKcYPPcEdQeD3zT49Hso1mEcciedJ5rskzhi2AOoOQMADA4p9xplpci08+IyG1YNCzOxZTgjk5ycgkHOc980AVNT8O6bqUardQbivlbX3EsBG2RgnkZyQSOSCRmtSCGO3gjhgjSKGNQiIgAVVAwAAOgAqjdaNaXKEHzkciJTIkrByqNkDdnPOSCepBPNX'||
'40WKNI4xhFAUD0AoAr6np1pqdo9tfwLPA4wVb8fyPPWqX/CO6f5SQeW4tokVIoUcoIsOHLKVw24sqkkk8r2yc3dT0601O0e2v4VmgcYZCSP5d+etV20LTmtLe2+zbYbdQsSq7KVw6uDkHOdyKc9cj3NAEr6ZAbpZ1MiMH3uFbiQ4UAEHPTYh4xyvuQZmtIGWVWTKykM4JPzcAc/goGKQWVuJPMVCrE5JViMn5euDz9xf8k0y70+2u7S6trhXaG5UrKBKykgqFOCDkcAdMfqaAGTabFcJPFdPJPbSgKsD7QsQAwdpADc98k+2Kff2Ed75Imd/KjkWUxjGHZSGXPGeGCngjOOcjIqS5s4Lmza1nTdAy7CuSOPqOadPbQzoyTxrIjbcq/I4ORx064/IUAVE0XT0kR1t/mRURCXY7Qn3cZPHbPrgZzgU6HTLeEQIm/yIFUQwk5WMrn5gfvZ5xyTwPc5YNE075f9GU7VRBliflT7oPPI/n3qRtLs2SyTycJZyCSBVYqEYKVHAPIwx4PH5CgAsNLs7By1pD5bFVQ/Mx4VVUdT6Ko/CrDwRu7s4Lb1CEFjjAJPA6A89Rz09BVaw0ixsJPMtLdY5Ngj3ZJIUKq4yfZF+uBVt4UcuWXJZdp+nP8AiaAIprOCZAsiZADKPmIIDDBGeuPb2HoKbJp1m5Utbx/KgjXAxsUdl9OvamXGlWdxEI5YiyBgwG9hjp8oweFOMFfukZBBBNLPpllOyGW1iYooVDt5QDONv93qelAFNfDOkrNJItswaS4a7cedJtaVgysxXdjkMQRjB4/ujGnJbxSABlPDiQYJBDD0x+o7gkHqaiTT7VLd4EiCxO7SMoJ5ZmLkk+7Ek1BdaLY3d9DdzxO08OdhErqBnr8oOOe/HI4ORQBo0UUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAI/3G+lVqsv9xvpVagCLUbGy1K3jhvo/MRGDrhmUq2CMggg55NVJvD2jzXPnv'||
'bHzSrIcSuoKlSmCAcH5SQPQdMYql4gufEovYo/D0nh5LTy/3kl/JKZFk+bgImAR93+IHqPeqepXHjQRyDTLrwoz8BHuBMo+7HklVY9W83jPAKdeaAN4aLpG9Wazhcr5mN4LAbyu7g8fwKPYDAwOKs2NnZWHm/ZIliMrtJIRklmZixJJ92P51h6nceJhDG2mXXhxpfOcOlx5oAi8xihDKxy3l7QRjG4kg4AUuim8SGwthLf+HkvckTssUjRgbZMFRvB5PlcE8APycjBYLmvc2NpcSO7GdHf7xhnki3dBk7SMnAAz1pDYWpedjLdkzMrP/pUuAQMDaN2FHqFwD3zWRq114lFmyaRL4ea6G3bLdSShDwm7KLkjJ83HzHGE65OKEtx458iHyrjwgJvJxLuM+0S5flec7ceXwefvc9KLBc6ZNPskadk85Xnl86RhNJuLYUcHOQMIowOOOlD6fYuIN0ZLQyLKjb23F1XaGZs5Y44+bOe9Msp7tby4+3XenSWu0GEwgo4bfJkNliCAnlDI6kOcAEAXvtMH/PaL/vsUWC5QudKs5wNst1A+6NmkguJEZ9nADEH5sjg55I75AIvw+XDDHEjOVRQoLszsQPVjkk+55o+0wf8APeL/AL7FH2mD/ntF/wB9iiwXK19Y2N8ri6hVy67GYZVivOBkc8Ekj0PPWoZtH0ueK0jltwy2gHkfM2Y8MrAg5znKLz16+pzf+0wf89ov++xR9pg/57Rf99iiwXKslhYSRzIYVVZl2ybMrvGc4OOvJP5n1NFxYWFz532iFZfOG19+WyNpXHPQYLDA/vN/eObX2mD/AJ7Rf99ij7TB/wA9ov8AvsUWC5BeWtpe2T2dynmWzrsaMkgMuMYOKil03T5RdK8I23UYilUFgGXLHoOhy7HIwcnrwKufaYP+e0X/AH2KPtMH/PaL/vsUWC5j2vhrQ7V5Gt7JYxJs3qHfa20AAFc4I46Y5PJ55qzcaPpVxZG0ktIhblmfb'||
'GCnzMCpYFcEHDEZ96v/AGmD/ntF/wB9ij7TB/z2i/77FFguZuj6JpOjO76dapDI4wzks7EemWJOOOnSr8kNrLJ5kkcbSYxvK/NjDDr9Gb/vo+tP+0wf89ov++xR9pg/57Rf99iiwXKp0/TyiKbeMqihAMH7oBG33XDEY6cn1oTT9Ojuhcx2sKTg5DqmDn5vT/fb86tfaYP+e0X/AH2KPtMH/PaL/vsUWC5QbSNMbzd1uCJWLuNzYLHfk4z1PmOPocdAMLdaTpN3g3VjbSkNvBeIEg5JPPuS2fXJ9TV77TB/z2i/77FH2mD/AJ7Rf99iiwXFkMUihZArAENhhnkHIP4EA07zF9aZ9pg/57Rf99ij7TB/z2i/77FFguP8xfWjzF9aZ9pg/wCe0X/fYo+0wf8APaL/AL7FFguP8xfWjzF9aZ9pg/57Rf8AfYo+0wf89ov++xRYLj/MX1o8xfWmfaYP+e0X/fYo+0wf89ov++xRYLj/ADF9aPMX1pn2mD/ntF/32KPtMH/PaL/vsUWC4/zF9aPMX1pn2mD/AJ7Rf99ij7TB/wA9ov8AvsUWC4/zF9aPMX1pn2mD/ntF/wB9ij7TB/z2i/77FFguQ3Mk/nwC3EJgJbz2cncBtOAoAxnOMknoO+eFqQ3ELAhZoyTwAGFR0ANSJyCQOMnv71yknh/xc11dSJ4tjWF53eGL+y4yIoiJNqE78sQWTLcZEYGASSd6506xvpphdDzJGtzE8ZuXAEbFhu2A4UnLjeBnGRmoLGy0KMTSaetjGscDK5t59ojicAn7vCg7AQeO5HU5dxGbqmg+KbyKEWvihLCQOjytBp0bBgIwGVQ7NtUvluckZxk9a3NLs763sxHqF0Ly48yRvNEQi+UuSi7QT91Sq574zxnFSKtos8qmVHkQxb45Lpn2HomVJOCT09SAeSBTpVt5WAabBVycLduvzc8HB5+8ePp6DBcZL5L/AN39axdQ0fWrnXYbq212W001Igr2M'||
'dtE3mOGJLGRgSAQQMDHTIPNa2pyW8cate3KWoGSrm5MWOMZ7A9e+RVSPTNNfUp7iMK169sIZGF25byT078Z253DBJGc9aLgc5Z+GvGSW3lXnjQTP9nMfnRaVDG/m+ZuEnLMuNvybce+c10eg2Go2ej2tvq19/aV/GmJrvylh81vXYvC/QVXhtNBj8PG0hazGkspfIujtIDA7t+c8NjnPpV25tbB7No7rymgFuYWaW4YkxFTncx5ORkkk84znjNFwKmt6Xq16uNL1ZtNZYpFBFukoMhACMwb+FeSVGC2RyMc0NW0DxFPM76Z4ons0aRXCSWUEwVQeUHCnBHHJJHrW5qFpYXfkRX0Vs5U7oVZ8FTwuV7g/MBkf3sd6ryQaTdQrO8lvJFHbyxCX7WxAibAkJbP+yMt1HqKLgZI0PxUNREp8TQGzxDm3/s1M5Ux+ad+/wDjCvjj5fMP3sCszS/CnjeC/WTUvHrXdptw8Mej28TZ2EZVsnB3FW5B6Y711YtNKlW0hC2r/Z40aBfPyUQgqrL7HkA98ewxLFb2FkLOJPIi+yxCGENOcqmVXHPJGQo5zzjvRcA1KzvZ9MuoLK5FpeSQukNyYxJ5TlSFfYThsHBweuMVh3mieKZ9Ut7iHxLDbWkbKZLSPTUKyqJWYgszlgTGVTIPBUtjnaOrgjMEMcUaAIihVBck4AwOTyafl/7q/wDfX/1qLgcboWgeK7S8hk1bxUmowKpEkK6bHDvOcgghiRxkY57dMHME3hvxi1/pksfjJY7eBIhdwf2VERdOGzIQ27KBh8oAztxnJNdzl/7q/wDfX/1qiu1WS1mS5WPyGRhJucgbcc5OOOKLgR+S+4/L+tZWu6Zq95EBpOqnTZM8sbdJhjY4GAcYO5kbv9zGOSa1rHy/ssZszG9uw3IyyllwSTwfTngDgDAHFWMv/dX/AL6/+tRcDirnw94uk0eO2i8XJDfCZHa8XTIiWjESqybC20EyBnz2DbccZrU8P'||
'6Xrdl5v9s6wuphlATFosGw75CT8pOflaNcf9Myf4sDocv8A3V/76/8ArUZf+6v/AH1/9ai4FbyX/u/rXPeJNG8S30rHQ/EMOlRFAAraetwwb58tlnHXKcY42nru+XqQXxwq4/3v/rUuX/ur/wB9f/WouByNpoXiaPXre7ufEwn01BIJLEafGnmZaQofMzkbVaMcdfLJ43YF9NK1dfEP206xI2mGNlOnNbx7Q3GGWQYYYwcg5zntit/L/wB1f++v/rVTnjtpb6MSeULsLuVRMVcqD6DquSMjoeM9qLgP8l8/d/WjyX/u/rVXydPn0UWwFs+mSoIlCzfIVbAUKfxAGD6Y7VJdy2i4NxcxxeW2Dm7ZMEnODyPyPb2ouBz+laJ4stpZmv8AxLa3ys8PlodLEYRFGJBxJks/BB6Kf4SPlre061vIdPtYr6dbq7SJVmnVBGJXAAZwuTtycnGTjNOiFp/aZKSRveqjfIblmZUZgT8p6DIXt6Vfy/8AdX/vr/61FwK6xspywwKdUjlsfMAB7HNR00IKKKKACiiigAooooAKKKKAGT/6sf7y/wAxS0k/+rH+8v8AMUtJghy28MoieWKN3jJKMyglTnse3QUv2O189p/s0PnsuwyeWNxXjjPXHA/IUUUhiw2ltBNLNBbwxzShRI6IAzhRhckdcDp6U0WNoH3i1gD5DbvLGcgYB/KiigB13aW15GY7u3hnjIwVlQMPyNILO2ExlFvD5pXYX2DcV9M+ntRRQA0WFmLYW4tLcW46ReWNo5z0xjqAfrTms7VkCNbQlBGYQpQYCHqv09ulFFADpoIZ1ZZ4o5FIKkOoIIOMjntwPypjWVo0kcjW0BkjBCMYxlQc5APbOT+dFFADvstvvZ/Ii3NtydgydpLL+RJI9CTSm2gLITDETGdyEoPlOMZHpxxRRQBLRRRQAUjosiMkihkYYZWGQR6GiigBsMUcEaxQRpHGowqIAAPoBT6KKACiiigBFUKMKABnP'||
'FLRRQAVG9vDJKJJIY2kUYDsoJA64zRRQA2S1t5bf7PJBE9vgDymQFcDoMdOwqOXTbGUMJbO2cMQxDRKckDAPTt2oooAfHaW0VwZ47eFJyuwyKgDFfTPXHA4qeiigBkv3R9aiooqkIKKKKACiiigAooooAKKKKAGT/6sf7y/zFLRRSYI/9k=';

      INSERT INTO EMS_DASHBOARD (DASHBOARD_ID,NAME,TYPE,DESCRIPTION,CREATION_DATE,LAST_MODIFICATION_DATE,
                                 LAST_MODIFIED_BY,OWNER,IS_SYSTEM,APPLICATION_TYPE,ENABLE_TIME_RANGE,SCREEN_SHOT,
                                 DELETED,TENANT_ID,ENABLE_REFRESH,SHARE_PUBLIC,ENABLE_ENTITY_FILTER,ENABLE_DESCRIPTION) 
      VALUES(V_DASHBOARD_ID,V_NAME,V_TYPE,V_DESCRIPTION,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,
             V_OWNER,V_IS_SYSTEM,V_APPLICATION_TYPE,V_ENABLE_TIME_RANGE,V_SCREEN_SHOT,V_DELETED,V_TENANT_ID,
             V_ENABLE_REFRESH,V_SHARE_PUBLIC,V_ENABLE_ENTITY_FILTER,V_ENABLE_DESCRIPTION);

      V_TILE_ID                     := 121;
      V_TITLE                       := 'Completed Workflow Submissions';
      V_HEIGHT                      := 2;
      V_WIDTH                       := 12;
      V_IS_MAXIMIZED                := 0;
      V_POSITION                    := 0;
      V_WIDGET_UNIQUE_ID            := 5007;
      V_WIDGET_NAME                 := 'Completed Workflow Submissions';
      V_WIDGET_DESCRIPTION          := 'Orchestration';
      V_WIDGET_GROUP_NAME           := 'Orchestration';
      V_WIDGET_ICON                 := null;
      V_WIDGET_HISTOGRAM            := null;
      V_WIDGET_OWNER                := 'ORACLE';
      V_WIDGET_CREATION_TIME        := to_char(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS.ff3"Z"');
      V_WIDGET_SOURCE               := 1;
      V_WIDGET_KOC_NAME             := 'emcta-visualization';
      V_WIDGET_VIEWMODE             := '/widget/visualizationWidget/js/VisualizationWidget.js';
      V_WIDGET_TEMPLATE             := '/widget/visualizationWidget/visualizationWidget.html';
      V_PROVIDER_NAME               := 'TargetAnalytics';
      V_PROVIDER_VERSION            := '1.1';
      V_PROVIDER_ASSET_ROOT         := 'assetRoot';
      V_TILE_ROW                    := 4;
      V_TILE_COLUMN                 := 0;
      V_TILE_TYPE                   := 0;
      V_TILE_SUPPORT_TIMECONTROL    := 1;
      V_TILE_LINKED_DASHBOARD       := null;
      INSERT INTO EMS_DASHBOARD_TILE(TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,
                                     WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,
                                     WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,
                                     TYPE,WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD)
      VALUES(V_TILE_ID,V_DASHBOARD_ID,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_OWNER,V_TITLE,V_HEIGHT,V_WIDTH,V_IS_MAXIMIZED,V_POSITION,V_TENANT_ID,
             V_WIDGET_UNIQUE_ID,V_WIDGET_NAME,V_WIDGET_DESCRIPTION,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_HISTOGRAM,V_WIDGET_OWNER,V_WIDGET_CREATION_TIME,V_WIDGET_SOURCE,V_WIDGET_KOC_NAME,
             V_WIDGET_VIEWMODE,V_WIDGET_TEMPLATE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TILE_ROW,V_TILE_COLUMN,V_TILE_TYPE,V_TILE_SUPPORT_TIMECONTROL,V_TILE_LINKED_DASHBOARD);

      V_TILE_ID                     := 122;
      V_TITLE                       := 'Histogram of Submissions by Average Failed Steps';
      V_HEIGHT                      := 2;
      V_WIDTH                       := 3;
      V_IS_MAXIMIZED                := 0;
      V_POSITION                    := 0;
      V_WIDGET_UNIQUE_ID            := 5008;
      V_WIDGET_NAME                 := 'Histogram of Submissions by Average Failed Steps';
      V_WIDGET_DESCRIPTION          := 'Orchestration';
      V_WIDGET_GROUP_NAME           := 'Orchestration';
      V_WIDGET_ICON                 := null;
      V_WIDGET_HISTOGRAM            := null;
      V_WIDGET_OWNER                := 'ORACLE';
      V_WIDGET_CREATION_TIME        := to_char(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS.ff3"Z"');
      V_WIDGET_SOURCE               := 1;
      V_WIDGET_KOC_NAME             := 'emcta-visualization';
      V_WIDGET_VIEWMODE             := '/widget/visualizationWidget/js/VisualizationWidget.js';
      V_WIDGET_TEMPLATE             := '/widget/visualizationWidget/visualizationWidget.html';
      V_PROVIDER_NAME               := 'TargetAnalytics';
      V_PROVIDER_VERSION            := '1.1';
      V_PROVIDER_ASSET_ROOT         := 'assetRoot';
      V_TILE_ROW                    := 0;
      V_TILE_COLUMN                 := 9;
      V_TILE_TYPE                   := 0;
      V_TILE_SUPPORT_TIMECONTROL    := 1;
      V_TILE_LINKED_DASHBOARD       := null;
      INSERT INTO EMS_DASHBOARD_TILE(TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,
                                     WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,
                                     WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,
                                     TYPE,WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD)
      VALUES(V_TILE_ID,V_DASHBOARD_ID,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_OWNER,V_TITLE,V_HEIGHT,V_WIDTH,V_IS_MAXIMIZED,V_POSITION,V_TENANT_ID,
             V_WIDGET_UNIQUE_ID,V_WIDGET_NAME,V_WIDGET_DESCRIPTION,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_HISTOGRAM,V_WIDGET_OWNER,V_WIDGET_CREATION_TIME,V_WIDGET_SOURCE,V_WIDGET_KOC_NAME,
             V_WIDGET_VIEWMODE,V_WIDGET_TEMPLATE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TILE_ROW,V_TILE_COLUMN,V_TILE_TYPE,V_TILE_SUPPORT_TIMECONTROL,V_TILE_LINKED_DASHBOARD);

      V_TILE_ID                     := 123;
      V_TITLE                       := 'Scheduled Workflow Submissions';
      V_HEIGHT                      := 2;
      V_WIDTH                       := 12;
      V_IS_MAXIMIZED                := 0;
      V_POSITION                    := 0;
      V_WIDGET_UNIQUE_ID            := 5009;
      V_WIDGET_NAME                 := 'Scheduled Workflow Submissions';
      V_WIDGET_DESCRIPTION          := 'Orchestration';
      V_WIDGET_GROUP_NAME           := 'Orchestration';
      V_WIDGET_ICON                 := null;
      V_WIDGET_HISTOGRAM            := null;
      V_WIDGET_OWNER                := 'ORACLE';
      V_WIDGET_CREATION_TIME        := to_char(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS.ff3"Z"');
      V_WIDGET_SOURCE               := 1;
      V_WIDGET_KOC_NAME             := 'emcta-visualization';
      V_WIDGET_VIEWMODE             := '/widget/visualizationWidget/js/VisualizationWidget.js';
      V_WIDGET_TEMPLATE             := '/widget/visualizationWidget/visualizationWidget.html';
      V_PROVIDER_NAME               := 'TargetAnalytics';
      V_PROVIDER_VERSION            := '1.1';
      V_PROVIDER_ASSET_ROOT         := 'assetRoot';
      V_TILE_ROW                    := 6;
      V_TILE_COLUMN                 := 0;
      V_TILE_TYPE                   := 0;
      V_TILE_SUPPORT_TIMECONTROL    := 1;
      V_TILE_LINKED_DASHBOARD       := null;
      INSERT INTO EMS_DASHBOARD_TILE(TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,
                                     WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,
                                     WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,
                                     TYPE,WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD)
      VALUES(V_TILE_ID,V_DASHBOARD_ID,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_OWNER,V_TITLE,V_HEIGHT,V_WIDTH,V_IS_MAXIMIZED,V_POSITION,V_TENANT_ID,
             V_WIDGET_UNIQUE_ID,V_WIDGET_NAME,V_WIDGET_DESCRIPTION,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_HISTOGRAM,V_WIDGET_OWNER,V_WIDGET_CREATION_TIME,V_WIDGET_SOURCE,V_WIDGET_KOC_NAME,
             V_WIDGET_VIEWMODE,V_WIDGET_TEMPLATE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TILE_ROW,V_TILE_COLUMN,V_TILE_TYPE,V_TILE_SUPPORT_TIMECONTROL,V_TILE_LINKED_DASHBOARD);

      V_TILE_ID                     := 124;
      V_TITLE                       := 'Submissions by Type';
      V_HEIGHT                      := 2;
      V_WIDTH                       := 3;
      V_IS_MAXIMIZED                := 0;
      V_POSITION                    := 0;
      V_WIDGET_UNIQUE_ID            := 5010;
      V_WIDGET_NAME                 := 'Submissions by Type';
      V_WIDGET_DESCRIPTION          := 'Orchestration';
      V_WIDGET_GROUP_NAME           := 'Orchestration';
      V_WIDGET_ICON                 := null;
      V_WIDGET_HISTOGRAM            := null;
      V_WIDGET_OWNER                := 'ORACLE';
      V_WIDGET_CREATION_TIME        := to_char(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS.ff3"Z"');
      V_WIDGET_SOURCE               := 1;
      V_WIDGET_KOC_NAME             := 'emcta-visualization';
      V_WIDGET_VIEWMODE             := '/widget/visualizationWidget/js/VisualizationWidget.js';
      V_WIDGET_TEMPLATE             := '/widget/visualizationWidget/visualizationWidget.html';
      V_PROVIDER_NAME               := 'TargetAnalytics';
      V_PROVIDER_VERSION            := '1.1';
      V_PROVIDER_ASSET_ROOT         := 'assetRoot';
      V_TILE_ROW                    := 0;
      V_TILE_COLUMN                 := 6;
      V_TILE_TYPE                   := 0;
      V_TILE_SUPPORT_TIMECONTROL    := 1;
      V_TILE_LINKED_DASHBOARD       := null;
      INSERT INTO EMS_DASHBOARD_TILE(TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,
                                     WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,
                                     WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,
                                     TYPE,WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD)
      VALUES(V_TILE_ID,V_DASHBOARD_ID,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_OWNER,V_TITLE,V_HEIGHT,V_WIDTH,V_IS_MAXIMIZED,V_POSITION,V_TENANT_ID,
             V_WIDGET_UNIQUE_ID,V_WIDGET_NAME,V_WIDGET_DESCRIPTION,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_HISTOGRAM,V_WIDGET_OWNER,V_WIDGET_CREATION_TIME,V_WIDGET_SOURCE,V_WIDGET_KOC_NAME,
             V_WIDGET_VIEWMODE,V_WIDGET_TEMPLATE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TILE_ROW,V_TILE_COLUMN,V_TILE_TYPE,V_TILE_SUPPORT_TIMECONTROL,V_TILE_LINKED_DASHBOARD);

      V_TILE_ID                     := 125;
      V_TITLE                       := 'Submissions by User';
      V_HEIGHT                      := 2;
      V_WIDTH                       := 3;
      V_IS_MAXIMIZED                := 0;
      V_POSITION                    := 0;
      V_WIDGET_UNIQUE_ID            := 5011;
      V_WIDGET_NAME                 := 'Submissions by User';
      V_WIDGET_DESCRIPTION          := 'Orchestration';
      V_WIDGET_GROUP_NAME           := 'Orchestration';
      V_WIDGET_ICON                 := null;
      V_WIDGET_HISTOGRAM            := null;
      V_WIDGET_OWNER                := 'ORACLE';
      V_WIDGET_CREATION_TIME        := to_char(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS.ff3"Z"');
      V_WIDGET_SOURCE               := 1;
      V_WIDGET_KOC_NAME             := 'emcta-visualization';
      V_WIDGET_VIEWMODE             := '/widget/visualizationWidget/js/VisualizationWidget.js';
      V_WIDGET_TEMPLATE             := '/widget/visualizationWidget/visualizationWidget.html';
      V_PROVIDER_NAME               := 'TargetAnalytics';
      V_PROVIDER_VERSION            := '1.1';
      V_PROVIDER_ASSET_ROOT         := 'assetRoot';
      V_TILE_ROW                    := 0;
      V_TILE_COLUMN                 := 3;
      V_TILE_TYPE                   := 0;
      V_TILE_SUPPORT_TIMECONTROL    := 1;
      V_TILE_LINKED_DASHBOARD       := null;
      INSERT INTO EMS_DASHBOARD_TILE(TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,
                                     WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,
                                     WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,
                                     TYPE,WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD)
      VALUES(V_TILE_ID,V_DASHBOARD_ID,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_OWNER,V_TITLE,V_HEIGHT,V_WIDTH,V_IS_MAXIMIZED,V_POSITION,V_TENANT_ID,
             V_WIDGET_UNIQUE_ID,V_WIDGET_NAME,V_WIDGET_DESCRIPTION,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_HISTOGRAM,V_WIDGET_OWNER,V_WIDGET_CREATION_TIME,V_WIDGET_SOURCE,V_WIDGET_KOC_NAME,
             V_WIDGET_VIEWMODE,V_WIDGET_TEMPLATE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TILE_ROW,V_TILE_COLUMN,V_TILE_TYPE,V_TILE_SUPPORT_TIMECONTROL,V_TILE_LINKED_DASHBOARD);

      V_TILE_ID                     := 126;
      V_TITLE                       := 'Workflow Submission Alerts';
      V_HEIGHT                      := 1;
      V_WIDTH                       := 3;
      V_IS_MAXIMIZED                := 0;
      V_POSITION                    := 0;
      V_WIDGET_UNIQUE_ID            := 5012;
      V_WIDGET_NAME                 := 'Workflow Submission Alerts';
      V_WIDGET_DESCRIPTION          := 'Orchestration';
      V_WIDGET_GROUP_NAME           := 'Orchestration';
      V_WIDGET_ICON                 := null;
      V_WIDGET_HISTOGRAM            := null;
      V_WIDGET_OWNER                := 'ORACLE';
      V_WIDGET_CREATION_TIME        := to_char(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS.ff3"Z"');
      V_WIDGET_SOURCE               := 1;
      V_WIDGET_KOC_NAME             := 'emcta-visualization';
      V_WIDGET_VIEWMODE             := '/widget/visualizationWidget/js/VisualizationWidget.js';
      V_WIDGET_TEMPLATE             := '/widget/visualizationWidget/visualizationWidget.html';
      V_PROVIDER_NAME               := 'TargetAnalytics';
      V_PROVIDER_VERSION            := '1.1';
      V_PROVIDER_ASSET_ROOT         := 'assetRoot';
      V_TILE_ROW                    := 1;
      V_TILE_COLUMN                 := 0;
      V_TILE_TYPE                   := 0;
      V_TILE_SUPPORT_TIMECONTROL    := 1;
      V_TILE_LINKED_DASHBOARD       := null;
      INSERT INTO EMS_DASHBOARD_TILE(TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,
                                     WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,
                                     WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,
                                     TYPE,WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD)
      VALUES(V_TILE_ID,V_DASHBOARD_ID,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_OWNER,V_TITLE,V_HEIGHT,V_WIDTH,V_IS_MAXIMIZED,V_POSITION,V_TENANT_ID,
             V_WIDGET_UNIQUE_ID,V_WIDGET_NAME,V_WIDGET_DESCRIPTION,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_HISTOGRAM,V_WIDGET_OWNER,V_WIDGET_CREATION_TIME,V_WIDGET_SOURCE,V_WIDGET_KOC_NAME,
             V_WIDGET_VIEWMODE,V_WIDGET_TEMPLATE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TILE_ROW,V_TILE_COLUMN,V_TILE_TYPE,V_TILE_SUPPORT_TIMECONTROL,V_TILE_LINKED_DASHBOARD);

      V_PARAM_NAME                  := 'DF_HIDE_TITLE';
      V_PARAM_TYPE                  := 1;
      V_PARAM_VALUE_STR             := 'false';
      V_PARAM_VALUE_NUM             := null;
      V_PARAM_VALUE_TIMESTAMP       := null;
      Insert into EMS_DASHBOARD_TILE_PARAMS (TILE_ID,PARAM_NAME,TENANT_ID,IS_SYSTEM,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_NUM,PARAM_VALUE_TIMESTAMP) 
      values (V_TILE_ID,V_PARAM_NAME,V_TENANT_ID,CONST_IS_SYSTEM,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_NUM,V_PARAM_VALUE_TIMESTAMP);

      V_TILE_ID                     := 127;
      V_TITLE                       := 'Summary';
      V_HEIGHT                      := 1;
      V_WIDTH                       := 3;
      V_IS_MAXIMIZED                := 0;
      V_POSITION                    := 0;
      V_WIDGET_UNIQUE_ID            := 5005;
      V_WIDGET_NAME                 := 'Summary';
      V_WIDGET_DESCRIPTION          := 'Workflow Summary Status';
      V_WIDGET_GROUP_NAME           := 'Orchestration';
      V_WIDGET_ICON                 := null;
      V_WIDGET_HISTOGRAM            := null;
      V_WIDGET_OWNER                := 'ORACLE';
      V_WIDGET_CREATION_TIME        := to_char(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS.ff3"Z"');
      V_WIDGET_SOURCE               := 1;
      V_WIDGET_KOC_NAME             := 'Workflow Status Summary';
      V_WIDGET_VIEWMODE             := '/executionWidget/js/inProgressWidget.js';
      V_WIDGET_TEMPLATE             := '/executionWidget/html/inProgressWidget.html';
      V_PROVIDER_NAME               := 'CosUIService';
      V_PROVIDER_VERSION            := '1.0';
      V_PROVIDER_ASSET_ROOT         := 'assetRoot';
      V_TILE_ROW                    := 0;
      V_TILE_COLUMN                 := 0;
      V_TILE_TYPE                   := 0;
      V_TILE_SUPPORT_TIMECONTROL    := 1;
      V_TILE_LINKED_DASHBOARD       := null;
      INSERT INTO EMS_DASHBOARD_TILE(TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,
                                     WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,
                                     WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,
                                     TYPE,WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD)
      VALUES(V_TILE_ID,V_DASHBOARD_ID,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_OWNER,V_TITLE,V_HEIGHT,V_WIDTH,V_IS_MAXIMIZED,V_POSITION,V_TENANT_ID,
             V_WIDGET_UNIQUE_ID,V_WIDGET_NAME,V_WIDGET_DESCRIPTION,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_HISTOGRAM,V_WIDGET_OWNER,V_WIDGET_CREATION_TIME,V_WIDGET_SOURCE,V_WIDGET_KOC_NAME,
             V_WIDGET_VIEWMODE,V_WIDGET_TEMPLATE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TILE_ROW,V_TILE_COLUMN,V_TILE_TYPE,V_TILE_SUPPORT_TIMECONTROL,V_TILE_LINKED_DASHBOARD);

      V_PARAM_NAME                  := 'DF_HIDE_TITLE';
      V_PARAM_TYPE                  := 1;
      V_PARAM_VALUE_STR             := 'true';
      V_PARAM_VALUE_NUM             := null;
      V_PARAM_VALUE_TIMESTAMP       := null;
      Insert into EMS_DASHBOARD_TILE_PARAMS (TILE_ID,PARAM_NAME,TENANT_ID,IS_SYSTEM,PARAM_TYPE,PARAM_VALUE_STR,PARAM_VALUE_NUM,PARAM_VALUE_TIMESTAMP) 
      values (V_TILE_ID,V_PARAM_NAME,V_TENANT_ID,CONST_IS_SYSTEM,V_PARAM_TYPE,V_PARAM_VALUE_STR,V_PARAM_VALUE_NUM,V_PARAM_VALUE_TIMESTAMP);

      V_TILE_ID                     := 128;
      V_TITLE                       := 'Running Workflow Submission';
      V_HEIGHT                      := 2;
      V_WIDTH                       := 12;
      V_IS_MAXIMIZED                := 0;
      V_POSITION                    := 0;
      V_WIDGET_UNIQUE_ID            := 5006;
      V_WIDGET_NAME                 := 'Running Workflow Submission';
      V_WIDGET_DESCRIPTION          := 'Running Workflow Submission';
      V_WIDGET_GROUP_NAME           := 'Orchestration';
      V_WIDGET_ICON                 := null;
      V_WIDGET_HISTOGRAM            := null;
      V_WIDGET_OWNER                := 'ORACLE';
      V_WIDGET_CREATION_TIME        := to_char(SYS_EXTRACT_UTC(SYSTIMESTAMP),'YYYY-MM-DD"T"HH24:MI:SS.ff3"Z"');
      V_WIDGET_SOURCE               := 1;
      V_WIDGET_KOC_NAME             := 'Running Workflow Submission';
      V_WIDGET_VIEWMODE             := '/executionWidget/js/executionWidget.js';
      V_WIDGET_TEMPLATE             := '/executionWidget/html/executionWidget.html';
      V_PROVIDER_NAME               := 'CosUIService';
      V_PROVIDER_VERSION            := '1.0';
      V_PROVIDER_ASSET_ROOT         := 'assetRoot';
      V_TILE_ROW                    := 2;
      V_TILE_COLUMN                 := 0;
      V_TILE_TYPE                   := 0;
      V_TILE_SUPPORT_TIMECONTROL    := 1;
      V_TILE_LINKED_DASHBOARD       := null;
      INSERT INTO EMS_DASHBOARD_TILE(TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,
                                     WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,
                                     WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,
                                     TYPE,WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD)
      VALUES(V_TILE_ID,V_DASHBOARD_ID,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_OWNER,V_TITLE,V_HEIGHT,V_WIDTH,V_IS_MAXIMIZED,V_POSITION,V_TENANT_ID,
             V_WIDGET_UNIQUE_ID,V_WIDGET_NAME,V_WIDGET_DESCRIPTION,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_HISTOGRAM,V_WIDGET_OWNER,V_WIDGET_CREATION_TIME,V_WIDGET_SOURCE,V_WIDGET_KOC_NAME,
             V_WIDGET_VIEWMODE,V_WIDGET_TEMPLATE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TILE_ROW,V_TILE_COLUMN,V_TILE_TYPE,V_TILE_SUPPORT_TIMECONTROL,V_TILE_LINKED_DASHBOARD);
  DBMS_OUTPUT.PUT_LINE('Out of box dashboards:Orchestration Workflows have been created successfully for tenant: '||V_TENANT_ID);
ELSE
  DBMS_OUTPUT.PUT_LINE('Out of box dashboards:Orchestration Workflows have been created before, no need to create again for tenant: '||V_TENANT_ID);
END IF;
     IF (V_TID<>-1) THEN
        EXIT;
     END IF;
  END LOOP;
  CLOSE TENANT_CURSOR;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Failed to create out of box dashboards:Orchestration Workflows due to error '||SQLERRM);
    RAISE;
END;
/
