/**
 * Created by chehao on 2016/10/31.
 */

/**
 * this class is for test DashboardManager.listDashboards() method, you can executing these sql in sql-developer directly.
 * These sql were got from server log
 * env: den00ytq.us.oracle.com
 * branch:greenchannel_landing_oct28
 *
 */
public class DashboardManagerListDashboardTest {

    //no filter
    String sql1="select p.DASHBOARD_ID,p.DELETED,p.DESCRIPTION,p.SHOW_INHOME,p.ENABLE_TIME_RANGE,p.ENABLE_REFRESH,p.IS_SYSTEM,p.SHARE_PUBLIC,p.APPLICATION_TYPE,p.CREATION_DATE,p.LAST_MODIFICATION_DATE,p.NAME,p.OWNER,p.TENANT_ID,p.TYPE  from Ems_Dashboard p  left join Ems_Dashboard_User_Options le on (p.dashboard_Id =le.dashboard_Id and le.user_name = 'emcsadmin' and p.tenant_Id = le.tenant_Id) where 1=1  and p.show_inhome = 1  and p.deleted = 0 and p.tenant_Id = 1663659699 and ((p.type<>2 and (p.share_public = 1 or p.owner = 'emcsadmin' or p.application_type in (1,3,2,4,7,6)) and ((p.is_system=0 ) or (p.is_system=1 ))) OR (  p.type=2  and ( (p.is_system=0 ) or (p.is_system=1 )) and (p.share_public=1 or p.owner ='emcsadmin'  or p.application_type  IN (1,3,2,4,7,6)))) order by p.application_Type, p.type DESC, lower(p.name), p.name, CASE WHEN le.access_Date IS NULL THEN 0 ELSE 1 END DESC, le.access_Date DESC";

    //oracle,APM
    String sql2="select p.DASHBOARD_ID,p.DELETED,p.DESCRIPTION,p.SHOW_INHOME,p.ENABLE_TIME_RANGE,p.ENABLE_REFRESH,p.IS_SYSTEM,p.SHARE_PUBLIC,p.APPLICATION_TYPE,p.CREATION_DATE,p.LAST_MODIFICATION_DATE,p.NAME,p.OWNER,p.TENANT_ID,p.TYPE  from Ems_Dashboard p  left join Ems_Dashboard_User_Options le on (p.dashboard_Id =le.dashboard_Id and le.user_name = 'emcsadmin' and p.tenant_Id = le.tenant_Id) where 1=1  and p.show_inhome = 1  and p.deleted = 0 and p.tenant_Id = 1663659699 and ((p.type<>2 and (p.share_public = 1 or p.owner = 'emcsadmin' or p.application_type in (1,3,2,4,7,6)) and (  p.owner = 'Oracle' )  and ((p.is_system=0  and (p.dashboard_id in (select t.dashboard_Id from Ems_Dashboard_Tile t where t.WIDGET_GROUP_NAME in ('APMCS' ))) ) or (p.is_system=1  and ( p.application_type = 1 )))) OR (  p.type=2  and (  p.owner = 'Oracle' )  and ( (p.is_system=0  and p.DASHBOARD_ID in (SELECT p2.DASHBOARD_SET_ID FROM EMS_DASHBOARD_SET p2 WHERE p2.SUB_DASHBOARD_ID IN (SELECT t.dashboard_Id FROM Ems_Dashboard_Tile t WHERE t.WIDGET_GROUP_NAME IN ('APMCS')))) or (p.is_system=1  and ( p.application_type = 1 ))) and (p.share_public=1 or p.owner ='emcsadmin'  or p.application_type  IN (1,3,2,4,7,6)))) order by p.application_Type, p.type DESC, lower(p.name), p.name, CASE WHEN le.access_Date IS NULL THEN 0 ELSE 1 END DESC, le.access_Date DESC";

    //oracle,IT Analytics
    String sql3="select p.DASHBOARD_ID,p.DELETED,p.DESCRIPTION,p.SHOW_INHOME,p.ENABLE_TIME_RANGE,p.ENABLE_REFRESH,p.IS_SYSTEM,p.SHARE_PUBLIC,p.APPLICATION_TYPE,p.CREATION_DATE,p.LAST_MODIFICATION_DATE,p.NAME,p.OWNER,p.TENANT_ID,p.TYPE  from Ems_Dashboard p  left join Ems_Dashboard_User_Options le on (p.dashboard_Id =le.dashboard_Id and le.user_name = 'emcsadmin' and p.tenant_Id = le.tenant_Id) where 1=1  and p.show_inhome = 1  and p.deleted = 0 and p.tenant_Id = 1663659699 and ((p.type<>2 and (p.share_public = 1 or p.owner = 'emcsadmin' or p.application_type in (1,3,2,4,7,6)) and (  p.owner = 'Oracle' )  and ((p.is_system=0  and (p.dashboard_id in (select t.dashboard_Id from Ems_Dashboard_Tile t where t.WIDGET_GROUP_NAME in ('Data Explorer' ))) ) or (p.is_system=1  and ( p.application_type = 2 )))) OR (  p.type=2  and (  p.owner = 'Oracle' )  and ( (p.is_system=0  and p.DASHBOARD_ID in (SELECT p2.DASHBOARD_SET_ID FROM EMS_DASHBOARD_SET p2 WHERE p2.SUB_DASHBOARD_ID IN (SELECT t.dashboard_Id FROM Ems_Dashboard_Tile t WHERE t.WIDGET_GROUP_NAME IN ('Data Explorer')))) or (p.is_system=1  and ( p.application_type = 2 ))) and (p.share_public=1 or p.owner ='emcsadmin'  or p.application_type  IN (1,3,2,4,7,6)))) order by p.application_Type, p.type DESC, lower(p.name), p.name, CASE WHEN le.access_Date IS NULL THEN 0 ELSE 1 END DESC, le.access_Date DESC";

    //oracle, Log Analytics
    String sql4="select p.DASHBOARD_ID,p.DELETED,p.DESCRIPTION,p.SHOW_INHOME,p.ENABLE_TIME_RANGE,p.ENABLE_REFRESH,p.IS_SYSTEM,p.SHARE_PUBLIC,p.APPLICATION_TYPE,p.CREATION_DATE,p.LAST_MODIFICATION_DATE,p.NAME,p.OWNER,p.TENANT_ID,p.TYPE  from Ems_Dashboard p  left join Ems_Dashboard_User_Options le on (p.dashboard_Id =le.dashboard_Id and le.user_name = 'emcsadmin' and p.tenant_Id = le.tenant_Id) where 1=1  and p.show_inhome = 1  and p.deleted = 0 and p.tenant_Id = 1663659699 and ((p.type<>2 and (p.share_public = 1 or p.owner = 'emcsadmin' or p.application_type in (1,3,2,4,7,6)) and (  p.owner = 'Oracle' )  and ((p.is_system=0  and (p.dashboard_id in (select t.dashboard_Id from Ems_Dashboard_Tile t where t.WIDGET_GROUP_NAME in ('Log Analytics' ))) ) or (p.is_system=1  and ( p.application_type = 3 )))) OR (  p.type=2  and (  p.owner = 'Oracle' )  and ( (p.is_system=0  and p.DASHBOARD_ID in (SELECT p2.DASHBOARD_SET_ID FROM EMS_DASHBOARD_SET p2 WHERE p2.SUB_DASHBOARD_ID IN (SELECT t.dashboard_Id FROM Ems_Dashboard_Tile t WHERE t.WIDGET_GROUP_NAME IN ('Log Analytics')))) or (p.is_system=1  and ( p.application_type = 3 ))) and (p.share_public=1 or p.owner ='emcsadmin'  or p.application_type  IN (1,3,2,4,7,6)))) order by p.application_Type, p.type DESC, lower(p.name), p.name, CASE WHEN le.access_Date IS NULL THEN 0 ELSE 1 END DESC, le.access_Date DESC";

    //oracle,Orchestration
    String sql5="select p.DASHBOARD_ID,p.DELETED,p.DESCRIPTION,p.SHOW_INHOME,p.ENABLE_TIME_RANGE,p.ENABLE_REFRESH,p.IS_SYSTEM,p.SHARE_PUBLIC,p.APPLICATION_TYPE,p.CREATION_DATE,p.LAST_MODIFICATION_DATE,p.NAME,p.OWNER,p.TENANT_ID,p.TYPE  from Ems_Dashboard p  left join Ems_Dashboard_User_Options le on (p.dashboard_Id =le.dashboard_Id and le.user_name = 'emcsadmin' and p.tenant_Id = le.tenant_Id) where 1=1  and p.show_inhome = 1  and p.deleted = 0 and p.tenant_Id = 1663659699 and ((p.type<>2 and (p.share_public = 1 or p.owner = 'emcsadmin' or p.application_type in (1,3,2,4,7,6)) and (  p.owner = 'Oracle' )  and ((p.is_system=0  and (p.dashboard_id in (select t.dashboard_Id from Ems_Dashboard_Tile t where t.WIDGET_GROUP_NAME in ('Orchestration' ))) ) or (p.is_system=1  and ( p.application_type = 6 )))) OR (  p.type=2  and (  p.owner = 'Oracle' )  and ( (p.is_system=0  and p.DASHBOARD_ID in (SELECT p2.DASHBOARD_SET_ID FROM EMS_DASHBOARD_SET p2 WHERE p2.SUB_DASHBOARD_ID IN (SELECT t.dashboard_Id FROM Ems_Dashboard_Tile t WHERE t.WIDGET_GROUP_NAME IN ('Orchestration')))) or (p.is_system=1  and ( p.application_type = 6 ))) and (p.share_public=1 or p.owner ='emcsadmin'  or p.application_type  IN (1,3,2,4,7,6)))) order by p.application_Type, p.type DESC, lower(p.name), p.name, CASE WHEN le.access_Date IS NULL THEN 0 ELSE 1 END DESC, le.access_Date DESC";

    //oracle,IT Analytics,Log Analytics
    String sql6="select p.DASHBOARD_ID,p.DELETED,p.DESCRIPTION,p.SHOW_INHOME,p.ENABLE_TIME_RANGE,p.ENABLE_REFRESH,p.IS_SYSTEM,p.SHARE_PUBLIC,p.APPLICATION_TYPE,p.CREATION_DATE,p.LAST_MODIFICATION_DATE,p.NAME,p.OWNER,p.TENANT_ID,p.TYPE  from Ems_Dashboard p  left join Ems_Dashboard_User_Options le on (p.dashboard_Id =le.dashboard_Id and le.user_name = 'emcsadmin' and p.tenant_Id = le.tenant_Id) where 1=1  and p.show_inhome = 1  and p.deleted = 0 and p.tenant_Id = 1663659699 and ((p.type<>2 and (p.share_public = 1 or p.owner = 'emcsadmin' or p.application_type in (1,3,2,4,7,6)) and (  p.owner = 'Oracle' )  and ((p.is_system=0  and (p.dashboard_id in (select t.dashboard_Id from Ems_Dashboard_Tile t where t.WIDGET_GROUP_NAME in ('Data Explorer','Log Analytics' ))) ) or (p.is_system=1  and ( p.application_type = 2  or  p.application_type = 3 )))) OR (  p.type=2  and (  p.owner = 'Oracle' )  and ( (p.is_system=0  and p.DASHBOARD_ID in (SELECT p2.DASHBOARD_SET_ID FROM EMS_DASHBOARD_SET p2 WHERE p2.SUB_DASHBOARD_ID IN (SELECT t.dashboard_Id FROM Ems_Dashboard_Tile t WHERE t.WIDGET_GROUP_NAME IN ('Data Explorer','Log Analytics')))) or (p.is_system=1  and ( p.application_type = 2  or  p.application_type = 3 ))) and (p.share_public=1 or p.owner ='emcsadmin'  or p.application_type  IN (1,3,2,4,7,6)))) order by p.application_Type, p.type DESC, lower(p.name), p.name, CASE WHEN le.access_Date IS NULL THEN 0 ELSE 1 END DESC, le.access_Date DESC";

    //oracle,Log Analytics,Orchestration
    String sql7="select p.DASHBOARD_ID,p.DELETED,p.DESCRIPTION,p.SHOW_INHOME,p.ENABLE_TIME_RANGE,p.ENABLE_REFRESH,p.IS_SYSTEM,p.SHARE_PUBLIC,p.APPLICATION_TYPE,p.CREATION_DATE,p.LAST_MODIFICATION_DATE,p.NAME,p.OWNER,p.TENANT_ID,p.TYPE  from Ems_Dashboard p  left join Ems_Dashboard_User_Options le on (p.dashboard_Id =le.dashboard_Id and le.user_name = 'emcsadmin' and p.tenant_Id = le.tenant_Id) where 1=1  and p.show_inhome = 1  and p.deleted = 0 and p.tenant_Id = 1663659699 and ((p.type<>2 and (p.share_public = 1 or p.owner = 'emcsadmin' or p.application_type in (1,3,2,4,7,6)) and (  p.owner = 'Oracle' )  and ((p.is_system=0  and (p.dashboard_id in (select t.dashboard_Id from Ems_Dashboard_Tile t where t.WIDGET_GROUP_NAME in ('Log Analytics','Orchestration' ))) ) or (p.is_system=1  and ( p.application_type = 3  or  p.application_type = 6 )))) OR (  p.type=2  and (  p.owner = 'Oracle' )  and ( (p.is_system=0  and p.DASHBOARD_ID in (SELECT p2.DASHBOARD_SET_ID FROM EMS_DASHBOARD_SET p2 WHERE p2.SUB_DASHBOARD_ID IN (SELECT t.dashboard_Id FROM Ems_Dashboard_Tile t WHERE t.WIDGET_GROUP_NAME IN ('Log Analytics','Orchestration')))) or (p.is_system=1  and ( p.application_type = 3  or  p.application_type = 6 ))) and (p.share_public=1 or p.owner ='emcsadmin'  or p.application_type  IN (1,3,2,4,7,6)))) order by p.application_Type, p.type DESC, lower(p.name), p.name, CASE WHEN le.access_Date IS NULL THEN 0 ELSE 1 END DESC, le.access_Date DESC";

    //oracle,IT Analytics,Orchestration
    String sql8="select p.DASHBOARD_ID,p.DELETED,p.DESCRIPTION,p.SHOW_INHOME,p.ENABLE_TIME_RANGE,p.ENABLE_REFRESH,p.IS_SYSTEM,p.SHARE_PUBLIC,p.APPLICATION_TYPE,p.CREATION_DATE,p.LAST_MODIFICATION_DATE,p.NAME,p.OWNER,p.TENANT_ID,p.TYPE  from Ems_Dashboard p  left join Ems_Dashboard_User_Options le on (p.dashboard_Id =le.dashboard_Id and le.user_name = 'emcsadmin' and p.tenant_Id = le.tenant_Id) where 1=1  and p.show_inhome = 1  and p.deleted = 0 and p.tenant_Id = 1663659699 and ((p.type<>2 and (p.share_public = 1 or p.owner = 'emcsadmin' or p.application_type in (1,3,2,4,7,6)) and (  p.owner = 'Oracle' )  and ((p.is_system=0  and (p.dashboard_id in (select t.dashboard_Id from Ems_Dashboard_Tile t where t.WIDGET_GROUP_NAME in ('Data Explorer','Orchestration' ))) ) or (p.is_system=1  and ( p.application_type = 2  or  p.application_type = 6 )))) OR (  p.type=2  and (  p.owner = 'Oracle' )  and ( (p.is_system=0  and p.DASHBOARD_ID in (SELECT p2.DASHBOARD_SET_ID FROM EMS_DASHBOARD_SET p2 WHERE p2.SUB_DASHBOARD_ID IN (SELECT t.dashboard_Id FROM Ems_Dashboard_Tile t WHERE t.WIDGET_GROUP_NAME IN ('Data Explorer','Orchestration')))) or (p.is_system=1  and ( p.application_type = 2  or  p.application_type = 6 ))) and (p.share_public=1 or p.owner ='emcsadmin'  or p.application_type  IN (1,3,2,4,7,6)))) order by p.application_Type, p.type DESC, lower(p.name), p.name, CASE WHEN le.access_Date IS NULL THEN 0 ELSE 1 END DESC, le.access_Date DESC";

    //oracle
    String sql9="select p.DASHBOARD_ID,p.DELETED,p.DESCRIPTION,p.SHOW_INHOME,p.ENABLE_TIME_RANGE,p.ENABLE_REFRESH,p.IS_SYSTEM,p.SHARE_PUBLIC,p.APPLICATION_TYPE,p.CREATION_DATE,p.LAST_MODIFICATION_DATE,p.NAME,p.OWNER,p.TENANT_ID,p.TYPE  from Ems_Dashboard p  left join Ems_Dashboard_User_Options le on (p.dashboard_Id =le.dashboard_Id and le.user_name = 'emcsadmin' and p.tenant_Id = le.tenant_Id) where 1=1  and p.show_inhome = 1  and p.deleted = 0 and p.tenant_Id = 1663659699 and ((p.type<>2 and (p.share_public = 1 or p.owner = 'emcsadmin' or p.application_type in (1,3,2,4,7,6)) and (  p.owner = 'Oracle' )  and ((p.is_system=0 ) or (p.is_system=1 ))) OR (  p.type=2  and (  p.owner = ''Oracle'' )  and ( (p.is_system=0 ) or (p.is_system=1 )) and (p.share_public=1 or p.owner ='emcsadmin'  or p.application_type  IN (1,3,2,4,7,6)))) order by p.application_Type, p.type DESC, lower(p.name), p.name, CASE WHEN le.access_Date IS NULL THEN 0 ELSE 1 END DESC, le.access_Date DESC";

    //others(shared)
    String sql10="select p.DASHBOARD_ID,p.DELETED,p.DESCRIPTION,p.SHOW_INHOME,p.ENABLE_TIME_RANGE,p.ENABLE_REFRESH,p.IS_SYSTEM,p.SHARE_PUBLIC,p.APPLICATION_TYPE,p.CREATION_DATE,p.LAST_MODIFICATION_DATE,p.NAME,p.OWNER,p.TENANT_ID,p.TYPE  from Ems_Dashboard p  left join Ems_Dashboard_User_Options le on (p.dashboard_Id =le.dashboard_Id and le.user_name = 'emcsadmin' and p.tenant_Id = le.tenant_Id) where 1=1  and p.show_inhome = 1  and p.deleted = 0 and p.tenant_Id = 1663659699 and ((p.type<>2 and (p.share_public = 1 or p.owner = 'emcsadmin' or p.application_type in (1,3,2,4,7,6)) and (  p.owner != 'emcsadmin' and p.share_public > 0 )  and ((p.is_system=0 ) or (p.is_system=1 ))) OR (  p.type=2  and (  p.owner != 'emcsadmin' and p.share_public > 0 )  and ( (p.is_system=0 ) or (p.is_system=1 )) and (p.share_public=1 or p.owner ='emcsadmin'  or p.application_type  IN (1,3,2,4,7,6)))) order by p.application_Type, p.type DESC, lower(p.name), p.name, CASE WHEN le.access_Date IS NULL THEN 0 ELSE 1 END DESC, le.access_Date DESC";

    //me
    String sql11="select p.DASHBOARD_ID,p.DELETED,p.DESCRIPTION,p.SHOW_INHOME,p.ENABLE_TIME_RANGE,p.ENABLE_REFRESH,p.IS_SYSTEM,p.SHARE_PUBLIC,p.APPLICATION_TYPE,p.CREATION_DATE,p.LAST_MODIFICATION_DATE,p.NAME,p.OWNER,p.TENANT_ID,p.TYPE  from Ems_Dashboard p  left join Ems_Dashboard_User_Options le on (p.dashboard_Id =le.dashboard_Id and le.user_name = 'emcsadmin' and p.tenant_Id = le.tenant_Id) where 1=1  and p.show_inhome = 1  and p.deleted = 0 and p.tenant_Id = 1663659699 and ((p.type<>2 and (p.share_public = 1 or p.owner = 'emcsadmin' or p.application_type in (1,3,2,4,7,6)) and (  p.owner = 'emcsadmin' )  and ((p.is_system=0 ) or (p.is_system=1 ))) OR (  p.type=2  and (  p.owner = 'emcsadmin' )  and ( (p.is_system=0 ) or (p.is_system=1 )) and (p.share_public=1 or p.owner ='emcsadmin'  or p.application_type  IN (1,3,2,4,7,6)))) order by p.application_Type, p.type DESC, lower(p.name), p.name, CASE WHEN le.access_Date IS NULL THEN 0 ELSE 1 END DESC, le.access_Date DESC";

    //favorite
    String sql12="select p.DASHBOARD_ID,p.DELETED,p.DESCRIPTION,p.SHOW_INHOME,p.ENABLE_TIME_RANGE,p.ENABLE_REFRESH,p.IS_SYSTEM,p.SHARE_PUBLIC,p.APPLICATION_TYPE,p.CREATION_DATE,p.LAST_MODIFICATION_DATE,p.NAME,p.OWNER,p.TENANT_ID,p.TYPE  from Ems_Dashboard p  left join Ems_Dashboard_User_Options le on (p.dashboard_Id =le.dashboard_Id and le.user_name = 'emcsadmin' and p.tenant_Id = le.tenant_Id) where 1=1  and p.show_inhome = 1  and p.deleted = 0 and p.tenant_Id = 1663659699 and ((p.type<>2 and (p.share_public = 1 or p.owner = 'emcsadmin' or p.application_type in (1,3,2,4,7,6)) and le.is_favorite > 0  and ((p.is_system=0 ) or (p.is_system=1 ))) OR (  p.type=2  and le.is_favorite > 0  and ( (p.is_system=0 ) or (p.is_system=1 )) and (p.share_public=1 or p.owner ='emcsadmin'  or p.application_type  IN (1,3,2,4,7,6)))) order by p.application_Type, p.type DESC, lower(p.name), p.name, CASE WHEN le.access_Date IS NULL THEN 0 ELSE 1 END DESC, le.access_Date DESC";

    //me,APM
    String sql13="select p.DASHBOARD_ID,p.DELETED,p.DESCRIPTION,p.SHOW_INHOME,p.ENABLE_TIME_RANGE,p.ENABLE_REFRESH,p.IS_SYSTEM,p.SHARE_PUBLIC,p.APPLICATION_TYPE,p.CREATION_DATE,p.LAST_MODIFICATION_DATE,p.NAME,p.OWNER,p.TENANT_ID,p.TYPE  from Ems_Dashboard p  left join Ems_Dashboard_User_Options le on (p.dashboard_Id =le.dashboard_Id and le.user_name = 'emcsadmin' and p.tenant_Id = le.tenant_Id) where 1=1  and p.show_inhome = 1  and p.deleted = 0 and p.tenant_Id = 1663659699 and ((p.type<>2 and (p.share_public = 1 or p.owner = 'emcsadmin' or p.application_type in (1,3,2,4,7,6)) and (  p.owner = 'emcsadmin' )  and ((p.is_system=0  and (p.dashboard_id in (select t.dashboard_Id from Ems_Dashboard_Tile t where t.WIDGET_GROUP_NAME in ('APMCS' ))) ) or (p.is_system=1  and ( p.application_type = 1 )))) OR (  p.type=2  and (  p.owner = 'emcsadmin' )  and ( (p.is_system=0  and p.DASHBOARD_ID in (SELECT p2.DASHBOARD_SET_ID FROM EMS_DASHBOARD_SET p2 WHERE p2.SUB_DASHBOARD_ID IN (SELECT t.dashboard_Id FROM Ems_Dashboard_Tile t WHERE t.WIDGET_GROUP_NAME IN ('APMCS')))) or (p.is_system=1  and ( p.application_type = 1 ))) and (p.share_public=1 or p.owner ='emcsadmin'  or p.application_type  IN (1,3,2,4,7,6)))) order by p.application_Type, p.type DESC, lower(p.name), p.name, CASE WHEN le.access_Date IS NULL THEN 0 ELSE 1 END DESC, le.access_Date DESC";

    //me,IT Analytics
    String sql14="select p.DASHBOARD_ID,p.DELETED,p.DESCRIPTION,p.SHOW_INHOME,p.ENABLE_TIME_RANGE,p.ENABLE_REFRESH,p.IS_SYSTEM,p.SHARE_PUBLIC,p.APPLICATION_TYPE,p.CREATION_DATE,p.LAST_MODIFICATION_DATE,p.NAME,p.OWNER,p.TENANT_ID,p.TYPE  from Ems_Dashboard p  left join Ems_Dashboard_User_Options le on (p.dashboard_Id =le.dashboard_Id and le.user_name = 'emcsadmin' and p.tenant_Id = le.tenant_Id) where 1=1  and p.show_inhome = 1  and p.deleted = 0 and p.tenant_Id = 1663659699 and ((p.type<>2 and (p.share_public = 1 or p.owner = 'emcsadmin' or p.application_type in (1,3,2,4,7,6)) and (  p.owner = 'emcsadmin' )  and ((p.is_system=0  and (p.dashboard_id in (select t.dashboard_Id from Ems_Dashboard_Tile t where t.WIDGET_GROUP_NAME in ('Data Explorer' ))) ) or (p.is_system=1  and ( p.application_type = 2 )))) OR (  p.type=2  and (  p.owner = 'emcsadmin' )  and ( (p.is_system=0  and p.DASHBOARD_ID in (SELECT p2.DASHBOARD_SET_ID FROM EMS_DASHBOARD_SET p2 WHERE p2.SUB_DASHBOARD_ID IN (SELECT t.dashboard_Id FROM Ems_Dashboard_Tile t WHERE t.WIDGET_GROUP_NAME IN ('Data Explorer')))) or (p.is_system=1  and ( p.application_type = 2 ))) and (p.share_public=1 or p.owner ='emcsadmin'  or p.application_type  IN (1,3,2,4,7,6)))) order by p.application_Type, p.type DESC, lower(p.name), p.name, CASE WHEN le.access_Date IS NULL THEN 0 ELSE 1 END DESC, le.access_Date DESC";

    //me, Log Analytics
    String sql15="select p.DASHBOARD_ID,p.DELETED,p.DESCRIPTION,p.SHOW_INHOME,p.ENABLE_TIME_RANGE,p.ENABLE_REFRESH,p.IS_SYSTEM,p.SHARE_PUBLIC,p.APPLICATION_TYPE,p.CREATION_DATE,p.LAST_MODIFICATION_DATE,p.NAME,p.OWNER,p.TENANT_ID,p.TYPE  from Ems_Dashboard p  left join Ems_Dashboard_User_Options le on (p.dashboard_Id =le.dashboard_Id and le.user_name = 'emcsadmin' and p.tenant_Id = le.tenant_Id) where 1=1  and p.show_inhome = 1  and p.deleted = 0 and p.tenant_Id = 1663659699 and ((p.type<>2 and (p.share_public = 1 or p.owner = 'emcsadmin' or p.application_type in (1,3,2,4,7,6)) and (  p.owner = 'emcsadmin' )  and ((p.is_system=0  and (p.dashboard_id in (select t.dashboard_Id from Ems_Dashboard_Tile t where t.WIDGET_GROUP_NAME in ('Log Analytics' ))) ) or (p.is_system=1  and ( p.application_type = 3 )))) OR (  p.type=2  and (  p.owner = 'emcsadmin' )  and ( (p.is_system=0  and p.DASHBOARD_ID in (SELECT p2.DASHBOARD_SET_ID FROM EMS_DASHBOARD_SET p2 WHERE p2.SUB_DASHBOARD_ID IN (SELECT t.dashboard_Id FROM Ems_Dashboard_Tile t WHERE t.WIDGET_GROUP_NAME IN ('Log Analytics')))) or (p.is_system=1  and ( p.application_type = 3 ))) and (p.share_public=1 or p.owner ='emcsadmin'  or p.application_type  IN (1,3,2,4,7,6)))) order by p.application_Type, p.type DESC, lower(p.name), p.name, CASE WHEN le.access_Date IS NULL THEN 0 ELSE 1 END DESC, le.access_Date DESC";

    //me, Orchestration
    String sql16="select p.DASHBOARD_ID,p.DELETED,p.DESCRIPTION,p.SHOW_INHOME,p.ENABLE_TIME_RANGE,p.ENABLE_REFRESH,p.IS_SYSTEM,p.SHARE_PUBLIC,p.APPLICATION_TYPE,p.CREATION_DATE,p.LAST_MODIFICATION_DATE,p.NAME,p.OWNER,p.TENANT_ID,p.TYPE  from Ems_Dashboard p  left join Ems_Dashboard_User_Options le on (p.dashboard_Id =le.dashboard_Id and le.user_name = 'emcsadmin' and p.tenant_Id = le.tenant_Id) where 1=1  and p.show_inhome = 1  and p.deleted = 0 and p.tenant_Id = 1663659699 and ((p.type<>2 and (p.share_public = 1 or p.owner = 'emcsadmin' or p.application_type in (1,3,2,4,7,6)) and (  p.owner = 'emcsadmin' )  and ((p.is_system=0  and (p.dashboard_id in (select t.dashboard_Id from Ems_Dashboard_Tile t where t.WIDGET_GROUP_NAME in ('Orchestration' ))) ) or (p.is_system=1  and ( p.application_type = 6 )))) OR (  p.type=2  and (  p.owner = 'emcsadmin' )  and ( (p.is_system=0  and p.DASHBOARD_ID in (SELECT p2.DASHBOARD_SET_ID FROM EMS_DASHBOARD_SET p2 WHERE p2.SUB_DASHBOARD_ID IN (SELECT t.dashboard_Id FROM Ems_Dashboard_Tile t WHERE t.WIDGET_GROUP_NAME IN ('Orchestration')))) or (p.is_system=1  and ( p.application_type = 6 ))) and (p.share_public=1 or p.owner ='emcsadmin'  or p.application_type  IN (1,3,2,4,7,6)))) order by p.application_Type, p.type DESC, lower(p.name), p.name, CASE WHEN le.access_Date IS NULL THEN 0 ELSE 1 END DESC, le.access_Date DESC";


}

