  SET FEEDBACK ON
  SET SERVEROUTPUT ON
  DEFINE TENANT_ID ='&1'
DECLARE
v_count     INTEGER;
V_TENANT_ID NUMBER(38,0);
V_TID NUMBER(38,0) := '&TENANT_ID';
V_PARAM_NAME EMS_DASHBOARD_TILE_PARAMS.PARAM_NAME%TYPE;
V_PARAM_STR EMS_DASHBOARD_TILE_PARAMS.PARAM_VALUE_STR%TYPE;
V_DASHBOARD_ID NUMBER(38,0);

CURSOR TENANT_CURSOR IS
    SELECT DISTINCT TENANT_ID FROM EMS_DASHBOARD ORDER BY TENANT_ID;

BEGIN
  V_PARAM_NAME:='DF_HIDE_TITLE';
  V_PARAM_STR:='TRUE';
  OPEN TENANT_CURSOR;
  LOOP
     IF (V_TID<>-1) THEN
        V_TENANT_ID:=V_TID;
     ELSE
       FETCH TENANT_CURSOR INTO V_TENANT_ID;
       EXIT WHEN TENANT_CURSOR%NOTFOUND;     
     END IF;  
     
    SELECT COUNT(*) INTO v_count FROM EMS_DASHBOARD_TILE_PARAMS 
    WHERE TILE_ID = 127 AND PARAM_NAME = V_PARAM_NAME AND UPPER(PARAM_VALUE_STR) = V_PARAM_STR AND TENANT_ID = V_TENANT_ID;
    IF v_count > 0 THEN
       V_PARAM_STR:='false';
       UPDATE EMS_DASHBOARD_TILE_PARAMS SET PARAM_VALUE_STR = V_PARAM_STR 
       WHERE TILE_ID = 127 AND PARAM_NAME =V_PARAM_NAME  AND TENANT_ID = V_TENANT_ID;

       DBMS_OUTPUT.PUT_LINE('OOB WIDGET WITH TITLE SUMMARY HAS BEEN UPDATED SUCCESSFULLY! for tenant:'||V_TENANT_ID);
    ELSE
       DBMS_OUTPUT.PUT_LINE('OOB WIDGET WITH TITLE SUMMARY NEED NOT TO BE UPDATED for tenant:'||V_TENANT_ID);
    END IF;
     IF (V_TID<>-1) THEN
        EXIT;
     END IF;
  END LOOP;
  CLOSE TENANT_CURSOR;
  commit;
  DBMS_OUTPUT.PUT_LINE('Upgrade is done');    
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      DBMS_OUTPUT.PUT_LINE('Failed to update the sql due to '||SQLERRM);
      RAISE;
  END;
  /
