  SET FEEDBACK ON
  SET SERVEROUTPUT ON
  DEFINE TENANT_ID ='&1'
  DECLARE
    v_count     INTEGER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM EMS_DASHBOARD_TILE_PARAMS WHERE TILE_ID = 127 AND PARAM_NAME = 'DF_HIDE_TITLE' AND UPPER(PARAM_VALUE_STR) = 'TRUE' AND TENANT_ID = '&TENANT_ID';
    IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'UPDATE EMS_DASHBOARD_TILE_PARAMS SET PARAM_VALUE_STR = ''false'' WHERE TILE_ID = 127 AND PARAM_NAME = ''DF_HIDE_TITLE'' AND TENANT_ID = ''&TENANT_ID''';
    DBMS_OUTPUT.PUT_LINE('OOB WIDGET WITH TITLE SUMMARY HAS BEEN UPDATED');
    ELSE
    DBMS_OUTPUT.PUT_LINE('OOB WIDGET WITH TITLE SUMMARY NEEDN''T TO BE UPDATED');
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      DBMS_OUTPUT.PUT_LINE('Failed to update the sql due to '||SQLERRM);
      RAISE;
  END;
  /