Rem --DDL change during upgrade
Rem
Rem upgrade_impl_ddl.sql
Rem
Rem Copyright (c) 2013, 2014, 2015, 2016 Oracle and/or its affiliates.
Rem All rights reserved.
Rem
Rem    NAME
Rem      upgrade_impl_ddl.sql
Rem
Rem    DESCRIPTION
Rem      DDL change during upgrade
Rem
Rem    NOTES
Rem      None
Rem

SET FEEDBACK ON
SET SERVEROUTPUT ON


DECLARE
  v_count     INTEGER;
BEGIN

  --add new column 'EMS_DASHBOARD_TILE.WIDGET_DELETED'
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name='EMS_DASHBOARD_TILE' AND column_name='WIDGET_DELETED';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_TILE ADD "WIDGET_DELETED" NUMBER(1,0) DEFAULT(0) NOT NULL';
  ELSE
    DBMS_OUTPUT.PUT_LINE('Schema object: EMS_DASHBOARD_TILE.WIDGET_DELETED exists already, no change is needed');
  END IF;
  
    --add new column 'EMS_DASHBOARD_TILE.WIDGET_DELETION_DATE'
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name='EMS_DASHBOARD_TILE' AND column_name='WIDGET_DELETION_DATE';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_TILE ADD "WIDGET_DELETION_DATE" TIMESTAMP';
  ELSE
    DBMS_OUTPUT.PUT_LINE('Schema object: EMS_DASHBOARD_TILE.WIDGET_DELETION_DATE exists already, no change is needed');
  END IF;

  ---update coluum show_inhome value
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name='EMS_DASHBOARD' AND column_name='SHOW_INHOME';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD ADD "SHOW_INHOME" NUMBER(1,0) DEFAULT(1) NOT NULL';
  ELSE
    DBMS_OUTPUT.PUT_LINE('Schema object: EMS_DASHBOARD.SHOW_INHOME exists already, no change is needed');
  END IF;

  --alter column EMS_DASHBOARD_TILE.TILE_ID
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name='EMS_DASHBOARD_TILE' AND column_name='TILE_ID';
  IF v_count>0 THEN
    EXECUTE IMMEDIATE 'alter table EMS_DASHBOARD_TILE drop constraint EMS_DASHBOARD_TILE_PK cascade drop index';
    EXECUTE IMMEDIATE 'alter table EMS_DASHBOARD_TILE rename column TILE_ID to TEMP_ID';
    EXECUTE IMMEDIATE 'alter table EMS_DASHBOARD_TILE add TILE_ID varchar2(63)';
    EXECUTE IMMEDIATE 'update EMS_DASHBOARD_TILE set TILE_ID = to_char(TEMP_ID)';
    EXECUTE IMMEDIATE 'alter table EMS_DASHBOARD_TILE drop column TEMP_ID';
    EXECUTE IMMEDIATE 'alter table EMS_DASHBOARD_TILE add constraint EMS_DASHBOARD_TILE_PK primary key(TILE_ID, TENANT_ID) USING INDEX';
  ELSE
    DBMS_OUTPUT.PUT_LINE('Schema object: EMS_DASHBOARD_TILE.TILE_ID does not exist, no change is needed');
  END IF;
  
  --alter column EMS_DASHBOARD_TILE_PARAMS.TILE_ID
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name='EMS_DASHBOARD_TILE_PARAMS' AND column_name='TILE_ID';
  IF v_count>0 THEN
    EXECUTE IMMEDIATE 'alter table EMS_DASHBOARD_TILE_PARAMS drop constraint EMS_DASHBOARD_TILE_PARAMS_PK cascade drop index';
    EXECUTE IMMEDIATE 'alter table EMS_DASHBOARD_TILE_PARAMS rename column TILE_ID to TEMP_ID';
    EXECUTE IMMEDIATE 'alter table EMS_DASHBOARD_TILE_PARAMS add TILE_ID varchar2(63)';
    EXECUTE IMMEDIATE 'update EMS_DASHBOARD_TILE_PARAMS set TILE_ID = to_char(TEMP_ID)';
    EXECUTE IMMEDIATE 'alter table EMS_DASHBOARD_TILE_PARAMS drop column TEMP_ID';
    EXECUTE IMMEDIATE 'alter table EMS_DASHBOARD_TILE_PARAMS add constraint EMS_DASHBOARD_TILE_PARAMS_PK primary key(TILE_ID, TENANT_ID, PARAM_NAME) USING INDEX';
    EXECUTE IMMEDIATE 'alter table EMS_DASHBOARD_TILE_PARAMS add constraint EMS_DASHBOARD_TILE_PARAMS_FK1 FOREIGN KEY (TILE_ID, TENANT_ID) REFERENCES EMS_DASHBOARD_TILE (TILE_ID, TENANT_ID)';
  ELSE
    DBMS_OUTPUT.PUT_LINE('Schema object: EMS_DASHBOARD_TILE_PARAMS.TILE_ID does not exist, no change is needed');
  END IF;
  
  --add new column 'EMS_DASHBOARD_SET.CREATION_DATE'
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name='EMS_DASHBOARD_SET' AND column_name='CREATION_DATE';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_SET ADD CREATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP';
  ELSE
    DBMS_OUTPUT.PUT_LINE('Schema object: EMS_DASHBOARD_SET.CREATION_DATE exists already, no change is needed');
  END IF;
  
  --add new column 'EMS_DASHBOARD_SET.LAST_MODIFICATION_DATE'
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name='EMS_DASHBOARD_SET' AND column_name='LAST_MODIFICATION_DATE';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_SET ADD LAST_MODIFICATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP';
  ELSE
    DBMS_OUTPUT.PUT_LINE('Schema object: EMS_DASHBOARD_SET.LAST_MODIFICATION_DATE exists already, no change is needed');
  END IF;
  
  --add new column 'EMS_DASHBOARD_TILE_PARAMS.CREATION_DATE'
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name='EMS_DASHBOARD_TILE_PARAMS' AND column_name='CREATION_DATE';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_TILE_PARAMS ADD CREATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP';
  ELSE
    DBMS_OUTPUT.PUT_LINE('Schema object: EMS_DASHBOARD_TILE_PARAMS.CREATION_DATE exists already, no change is needed');
  END IF;
  
  --add new column 'EMS_DASHBOARD_TILE_PARAMS.LAST_MODIFICATION_DATE'
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name='EMS_DASHBOARD_TILE_PARAMS' AND column_name='LAST_MODIFICATION_DATE';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_TILE_PARAMS ADD LAST_MODIFICATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP';
  ELSE
    DBMS_OUTPUT.PUT_LINE('Schema object: EMS_DASHBOARD_TILE_PARAMS.LAST_MODIFICATION_DATE exists already, no change is needed');
  END IF;
  
  --add new column 'EMS_DASHBOARD_USER_OPTIONS.CREATION_DATE'
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name='EMS_DASHBOARD_USER_OPTIONS' AND column_name='CREATION_DATE';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_USER_OPTIONS ADD CREATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP';
  ELSE
    DBMS_OUTPUT.PUT_LINE('Schema object: EMS_DASHBOARD_USER_OPTIONS.CREATION_DATE exists already, no change is needed');
  END IF;
  
  --add new column 'EMS_DASHBOARD_USER_OPTIONS.LAST_MODIFICATION_DATE'
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name='EMS_DASHBOARD_USER_OPTIONS' AND column_name='LAST_MODIFICATION_DATE';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_DASHBOARD_USER_OPTIONS ADD LAST_MODIFICATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP';
  ELSE
    DBMS_OUTPUT.PUT_LINE('Schema object: EMS_DASHBOARD_USER_OPTIONS.LAST_MODIFICATION_DATE exists already, no change is needed');
  END IF;
  
  --add new column 'EMS_PREFERENCE.CREATION_DATE'
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name='EMS_PREFERENCE' AND column_name='CREATION_DATE';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_PREFERENCE ADD CREATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP';
  ELSE
    DBMS_OUTPUT.PUT_LINE('Schema object: EMS_PREFERENCE.CREATION_DATE exists already, no change is needed');
  END IF;
  
  --add new column 'EMS_PREFERENCE.LAST_MODIFICATION_DATE'
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name='EMS_PREFERENCE' AND column_name='LAST_MODIFICATION_DATE';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EMS_PREFERENCE ADD LAST_MODIFICATION_DATE TIMESTAMP(6) DEFAULT LOCALTIMESTAMP';
  ELSE
    DBMS_OUTPUT.PUT_LINE('Schema object: EMS_PREFERENCE.LAST_MODIFICATION_DATE exists already, no change is needed');
  END IF;
  
  EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Failed to update the sql due to '||SQLERRM);
    RAISE;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TRIGGER EMS_DASHBOARD_TR DISABLE';
  EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN
         RAISE;
      END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TRIGGER EMS_DASHBOARD_TILE_TR DISABLE';
  EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN
         RAISE;
      END IF;
END;
/

