Rem
Rem emaas_dashboards_seed_data_sec.sql
Rem
Rem Copyright (c) 2013, 2014, 2015, 2016, 2017 Oracle and/or its affiliates.
Rem All rights reserved.
Rem
Rem    NAME
Rem      emaas_dashboards_seed_data_sec.sql
Rem
Rem    DESCRIPTION
Rem      Seed data for Security Analytics
Rem
Rem    NOTES
Rem      None
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    XIADAI       02/03/17 - Add OOB dashborads for Security Analytics
Rem

DEFINE TENANT_ID ='&1'
SET FEEDBACK ON
SET SERVEROUTPUT ON

DECLARE
  V_COUNT                                NUMBER;
  V_DASHBOARD_ID                         NUMBER(38,0);
  V_NAME                                 VARCHAR2(320 BYTE);
  V_TYPE                                 NUMBER(38,0);
  V_DESCRIPTION                          VARCHAR2(1280 BYTE);
  V_CREATION_DATE                        TIMESTAMP(6);
  V_LAST_MODIFICATION_DATE               TIMESTAMP(6);
  V_LAST_MODIFIED_BY                     VARCHAR2(128 BYTE);
  V_OWNER                                VARCHAR2(128 BYTE);
  V_IS_SYSTEM                            NUMBER(1,0);
  V_APPLICATION_TYPE                     NUMBER(4,0);
  V_ENABLE_TIME_RANGE                    NUMBER(2,0);
  V_ENABLE_REFRESH                       NUMBER(1,0);
  V_ENABLE_ENTITY_FILTER                 NUMBER(1,0);
  V_ENABLE_DESCRIPTION                   NUMBER(1,0);
  V_SHARE_PUBLIC                         NUMBER(1,0);
  V_DELETED                              NUMBER(38,0);
  V_TENANT_ID                            NUMBER(38,0);
  V_SCREEN_SHOT                          CLOB;
  V_CLOB                                 CLOB;
  V_DASHBOARD_SET_ID                     NUMBER(38,0);
  V_SUB_DASHBOARD_ID                     NUMBER(38,0);
  V_SUB_DSB_POSITION                     NUMBER(38,0);
  V_EXTENDED_OPTIONS	                 VARCHAR2(4000 BYTE);

  V_TILE_ID                     NUMBER(38,0);
  V_TITLE                       VARCHAR2(64 BYTE);
  V_HEIGHT                      NUMBER(38,0);
  V_WIDTH                       NUMBER(38,0);
  V_IS_MAXIMIZED                NUMBER(1,0);
  V_POSITION                    NUMBER(38,0);
  V_WIDGET_UNIQUE_ID            VARCHAR2(64 BYTE);
  V_WIDGET_NAME                 VARCHAR2(64 BYTE);
  V_WIDGET_DESCRIPTION          VARCHAR2(256 BYTE);
  V_WIDGET_GROUP_NAME           VARCHAR2(64 BYTE);
  V_WIDGET_ICON                 VARCHAR2(1024 BYTE);
  V_WIDGET_HISTOGRAM            VARCHAR2(1024 BYTE);
  V_WIDGET_OWNER                VARCHAR2(128 BYTE);
  V_WIDGET_CREATION_TIME        VARCHAR2(32 BYTE);
  V_WIDGET_SOURCE               NUMBER(38,0);
  V_WIDGET_KOC_NAME             VARCHAR2(256 BYTE);
  V_WIDGET_VIEWMODE             VARCHAR2(1024 BYTE);
  V_WIDGET_TEMPLATE             VARCHAR2(1024 BYTE);
  V_PROVIDER_NAME               VARCHAR2(64 BYTE);
  V_PROVIDER_VERSION            VARCHAR2(64 BYTE);
  V_PROVIDER_ASSET_ROOT         VARCHAR2(64 BYTE);
  V_TILE_ROW                    NUMBER(38,0);
  V_TILE_COLUMN                 NUMBER(38,0);
  V_TILE_TYPE                   NUMBER(38,0);
  V_TILE_SUPPORT_TIMECONTROL    NUMBER(1,0);
  V_TILE_LINKED_DASHBOARD       NUMBER(38,0);

  CONST_NULL                       CONSTANT    CLOB:=null;
  CONST_ORACLE                     CONSTANT    VARCHAR2(128 BYTE):='Oracle';
  CONST_IS_SYSTEM                  CONSTANT    NUMBER:=1;
  CONST_OOB_DSB_ACCESS_DATE        CONSTANT    EMS_DASHBOARD_USER_OPTIONS.ACCESS_DATE%TYPE:=SYS_EXTRACT_UTC(SYSTIMESTAMP);
  CONST_OOB_DSB_IS_FAVORITE        CONSTANT    EMS_DASHBOARD_USER_OPTIONS.IS_FAVORITE%TYPE:=0;

  CONST_DASHBOARD_ID_SEC_ANA   CONSTANT    EMS_DASHBOARD.DASHBOARD_ID%type:=40;
  V_TID                   NUMBER(38,0) := '&TENANT_ID';
  CURSOR TENANT_CURSOR IS
    SELECT DISTINCT TENANT_ID FROM EMS_DASHBOARD ORDER BY TENANT_ID;
BEGIN
  OPEN TENANT_CURSOR;
  LOOP
     IF (V_TID<>-1) THEN
        V_TENANT_ID:=V_TID;
     ELSE
       FETCH TENANT_CURSOR INTO V_TENANT_ID;
       EXIT WHEN TENANT_CURSOR%NOTFOUND;
     END IF;
  SELECT COUNT(DASHBOARD_ID) INTO V_COUNT FROM EMS_DASHBOARD WHERE DASHBOARD_ID=CONST_DASHBOARD_ID_SEC_ANA AND TENANT_ID=V_TENANT_ID;
  IF (V_COUNT<1) THEN
      V_DASHBOARD_ID              := CONST_DASHBOARD_ID_SEC_ANA;
      V_NAME                      := 'DNS';
      V_TYPE                      := 0;
      V_DESCRIPTION               := 'DNS Security Dashboard';
      V_CREATION_DATE             := SYS_EXTRACT_UTC(SYSTIMESTAMP);
      V_LAST_MODIFICATION_DATE    := SYS_EXTRACT_UTC(SYSTIMESTAMP);
      V_LAST_MODIFIED_BY          := CONST_ORACLE;
      V_OWNER                     := CONST_ORACLE;
      V_IS_SYSTEM                 := CONST_IS_SYSTEM;
      V_APPLICATION_TYPE          := 5;
      V_ENABLE_TIME_RANGE         := 1;
      V_ENABLE_REFRESH            := 1;
      V_ENABLE_ENTITY_FILTER      := 0;
      V_ENABLE_DESCRIPTION        := 0;
      V_SHARE_PUBLIC              := 0;
      V_DELETED                   := 0;
      V_EXTENDED_OPTIONS          := '{"timeSel":{"defaultValue":"last1day"}}';

  V_SCREEN_SHOT      :=  'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAClAToDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD6O16/'||
  '1SxWH+yNCOql43LEXMcIRxt2Bt3ZstyM429Dmq02q68NINzB4X33olC/ZHvolJTZkvvGRndlQO/BJAzjo0+4v0paAOfm1PWkvLeFPDZkhk2GSdbyILEC7K+QfmJChWGBg7iMgjmlqPiHW9Oa0E/hO4uBPIkRNlcLMI2ZUJzkKQoYyLuOB8qkkBjt62igClpk1xcQM19Y/Y5Q2AnmLICMA5BH1IPupxkYJubV/uj8qWigBNq/3R+VG1f7o/KsrxXr9l4X8P3ms6oZBaWqhmEa7mYkhVUD1JIHOBzyQK5jw58Sba/uNStde0jUdAvLGzbUnivIyd1qP+WgwM5HdcZByBkg4AO82r/dH5UbV/uj8q4Hwh8TLbxBrVpp9zo2qaUdRia40yW7jAW7jUZJGOjYyccjaAc/MAei8Y+J7LwppKX1/FdXHmzpbQ29qgeWaRzwqKSMngnGe1AG5tX+6Pyo2r/dH5VwcnxNsrfRrnUL/wAP+JbDy54raG2u7Hy5ruSQnCwqW+YjaSeR+PSpvDXxEstTtdZGsWVzouo6NEZ7+zufmZI9pbehHLrgdQO49QSAdttX+6Pyo2r/AHR+VcF4M+Jdr4j1mHTbjSdQ0ma8ga709rsKBdwDGGHOQxG47RkbVzk131ACbV/uj8qNq/3R+VLRQAm1f7o/Kjav90flS0UAJtX+6PyqrfPLDbXMlpbC5uEiZooN4TzHA4XceBk8ZPTNW6YP9cfpQBg6xqusWU8CWfh1r9ZpygaO6RQiBQdz5HBJ3ADkfKMsCwWnNqesC705V8NyG1nLC5kN3EHtRkhSVzh+ME7W4B43EYO/RQBga7qWsWTwrpXhxtS3Bi7fa44QmMY+91zk/lTtPv8AWZ9Slhu9AS'||
  '1s1lCpcG8Ry8ZVju2AcMGCDbn+InJ2/Nu0UAJtX+6Pyo2r/dH5UtFACbV/uj8qNq/3R+VZninXrLwz4fvdY1RnW0tU3P5a7mYkgKoHqSQBnA55IHNcz4R+Iaa34hOiajomo6LqMkDXdsl2FxNBkBT1yHPJK4ONp54oA7nav90flRtX+6PyrlvHPjGPwudPtYNOu9U1fUmdLOytl5kKAFizdFUAjJ565xgEjIX4p6UfCDa01hqa3K339l/2Z5Gbg3mP9SB698+2MbvloA9A2r/dH5UbV/uj8q4fR/iJDf6Jq1zJoWspqukyRxXukwwCW4VnIwUAI3ryTnjhScYxmbwj8QbXxLr1zpEWh6/p93bwieX+0LVYQikgKD8xIJzwMcgH0oA7Lav90flRtX+6PypaKAE2r/dH5UbV/uj8qWigBNq/3R+VG1f7o/KlooAZKoCHAFQVYl/1ZqvQBZT7i/SlpE+4v0paACiiigAooooAw/G/iW18I+GL3Wb5S8duo2xKcGRycKo+pI57DJ7V434X1Ow8ZaT4u1FtVbVPG+oaHcRrY20Eqx2dvt4gj3KAx3suTk5J4zyzfQFRXFxFbI73EixRIjSPI7BVRV6kk9BQB4T4J16w8TeKfhbaaJJJczaDpk41H92yiAm2SPqwGfnGMjI5FdB8Tdf8M+JvBWlap9s1dtGg1eItqGmo0bWrruXzG3LuCjdwVX720DkjPp/9qWQube3NwgnnOI4zkMThjjHY4R+D/cb0NYHhjWdHtkvLCJzbyQ3T+Y09xC7zyuzu0hEbsVztkbDBcBT8oCnAB4xBNY3/AIQ8XOdV8San4V0u8s59I1T79xaz7CHkG8oWVWZQV7BsgAndVfRtLv8AxVe+P9Y0'||
  '3VLrXo20U2f9oizMH2yf924jjiAGMJGEI5OSD/EK+j5tSs4HVJ7iONmYIu87ckkKOvqzKoPQkgdSBUE+t2cGqQWEjOJpopJVO3gBCmQe+cSA4xwAScCgDxjwLrVp4p8V/DS30PzLj/hHNJk/tKXyyixM9usQTLY3EMO2RzkE4OPeaKKACiiigAooooAKYP8AXH6U+mD/AFx+lAD6KKKACiiigAooooAyfFevWfhjw9e6zqZcWtqm5gi7mYkhVUD1LEDnjnkgc15b8OPGHh3XfE1z4h1bV4pfEk1kyx2cNvMI9PtUy7RhigDv1LN65C8dfZ3YIjMeijNVJ9QtEmNq93HFcNHv27huUENg4P8AuORnrsbrtOADzf4hfFrTtL8LaZeeHbqGabWGdLW5njkEcKK2x5nTbvIU9Bt55IBxg8hfS+H7TwF4d1XQtTutWsbDxXb32s6k8EgZpcZklZSMgfMgAAPUDJOSfWZNa0bwpounw2yE6eGeEP50aCPYxEjO0rqSQ27djLE5ODzW/FqVnLM8UVxHJIjbWVDkg5K847blZc9MqR1BFAHmvwz1iz1bxf8AEPxTZyM2gztaLHdOhQN5MBEnB54yDyOhFanwSjku/CUniK+BOq69cy3tyx5wA5SONSefLVVG0EnG4128Wo2szyLFMHeMgOqgkqTjAI7ZBBHqDkcU3S9SttUtUuLOQOjKDjuM9j2yCCDjuCOoNAFyiiigAooooAKKKKAGy/6s1XqxL/qzVegCdS20YXt60u5/7n61h+J9Bm1y2jFrrWp6VMkUiK1nIFViwXBcYycFRjBU8nnmtOwsVs4EiSe5l2hQXnmaRmwqrkk9yFBOMZJJ6k0AWdz/ANz9aNz/ANz9a5mx8H'||
  'iznkkXxB4ilD7fkmvy6jDo/GRkZKEH/Zdh0wBVl8CySSSP/wAJd4rVpPvbb1AOg6DZhemflx/SgDsNz/3P1o3P/c/Wq9hZJZLIEmuZQ7Bj58zSYwoXA3E4GFH1OSeSSbVADdz/ANz9ap6hYQajH5d5AZYijRtGZCEdW4ZWUHDA46HNXqKAMH/hG7UarZX4kvjLaNvjSS7eRc7ZlJO4knid+/GFAwBg2b7RLG9kWSe1ImUBVmimaKRQA4GHUhhgSSAHPG9vU1q0UAZMmh2csiNNDPLslMyrJdSMobcrj5S2MBkUqMYXHAGTUWpeHNO1KS6e+tppjdQtBKpupApjYIGUKGwoPlpnAGce5zt0UAM3P/c/Wl3P/c/WnUUAN3P/AHP1o3P/AHP1p1FADdz/ANz9aNz/ANz9adRQBFKJHidV3RswIDqRlfcZBGfqKq6Xaf2fbJbI8s2wEl5nDOxJJJJ7nJq/TB/rj9KAF3P/AHP1o3P/AHP1rntO8MzWerz3cmvaxdW8kSIlrNPlY2EhctkAE54X6ZByCAt3WNETVLYQvqGp22JFkD2l00TcYG3I6qQDkH+8TwcEAGpuf+5+tG5/7n61ymo+C2vlkUeKPE9t5kaRsbe9VT8qhdw+Q7WO3JIxkk+prRtfDi25gK6trLtEI+ZLsvvK7MlgeDuCAEdOWIAZixANrc/9z9aNz/3P1p1FAEbbmUqyZBGDzWVP4fspXaQpdJOYzF5yXkocLtdRzu7eY+M9CcjBrZooAybbRLO3sHsxA8kDidWEspcsJnLyAknJyT1PPvQuiWi3HnrHciTzPNyLyUAHcXIA3YCljkr0bAyDtGNaigDIh0KyhtZoIoZ084o0sq3comkK4ALS7t5OABkn'||
  'JAweOKk03R7PTbqa4s7ZkmmijhdjKz5SPdsX5icAb26etadFADdz/wBz9aNz/wBz9adRQA3c/wDc/Wjc/wDc/WnUUAN3P/c/Wjc/9z9adRQBSntne9S5aacLGhQQhh5eSfvEYyT268c+pp9WJf8AVmq9AFlPuL9KWkT7i/SloAKKK5rx+4TR4Sby5tP36/PbzeWx+VuM+nt7UXS1lt5K/wCCGozm+WCu+x0rHCk+gorxszrj/kP6x/4HH/Cl89f+g/rH/gef8KXtaPeX/gEv8i/qeO/58/8AkyPY6K8b89f+g/rH/gef8KXz1/6D+sf+B5/wo9rR7y/8Al/kH1PHf8+f/JkexMcD8cUteNmdf+g/rH/gcf8ACr+l6fe6r5v9n6vrU3lY341DGM5x1HsaTrUF1l/4BL/IUsLjYq8qVl/iR6qOlFZvhy1nstHt4LqSeSZd25p5PMc5YkZbvxWlVXT1W33fgRr13KF3qtvAk/kh7yaBlWWC1xJImemVzx+NM/tX90X+wX+OgHk8k4YkYz6rjPQkjBIINZ8ulo0+r7Ybi3a7ePfNZTlZXxnnO75ce2OtKjR2zR23max50gMi723thURSec8AFSR3Ynqxo5oy1jf5/wBfd5BaUdJWv5fh+G/mWLnXTBcvD/ZWqylTjdHb5VhnGQc475+lLLrvl3TwjS9VcIsjGVbf5DszwOcknHGBzmqmmJbNDvtptZuCrFz5kzncwcAjJO0HMfKZGPmGBuIM2n6XFKkh+1azmM+Uvn3EiEAMrDHTcOB8xySCQSRkUATza0YkZjpmpsQoYKkGSwyOnPXnoeeDSx6yXuJ4v7M1JfKcoHaEbXwpbKnPTjGTjkgUxNCCiXOp6qzyD7xuT8p3A5'||
  'A6DoB0xjIxycv/ALET/SR9u1LZcffX7U3B9UP3k+ikD2oAs6bfG+j3/ZLq2XarD7QgQnOeMZyCMc5x1qyP9cfpUVjbfZITH5882WLbpn3MMnOM+npUo/1x+lAD6KKKACiiuW+Ivnf2JB5F/LYN9oXMkblSRtb5cgj6/hQ5RjrN2Xo3+C1DlnLSmrvov+HOporxL/T/APoabz/wIb/4qj/T/wDoabz/AMCG/wDiqn6zgv8An7/5JP8A+RH9WzD/AKB3/wCBR/zPbQetBOCPc14l/p//AENN5/4EN/8AFVoHQ/EnH/E11r/yJ/jS+tYL/n7/AOST/wDkSZUMdH4qFv8At6P+Z67QpyoPqK8j/sPxL/0Fdb/8if40g0PxJjjVdax/20/xo+t4H/n7/wCST/8AkSfZ43/nz/5ND/M9dorzfS/COuXlu0k/iXVbZg20I+/JGBzy49f0q5/wg+r/APQ36l/4/wD/AByuuEKFSKlGro/J/wCRzyq4iD5XRf8A4FH/ADO8oHSuD/4QfV/+hv1L/wAf/wDjlIPA+r4/5G/Uv/H/AP45Vexo/wDPxfcyfrFf/ny/vX+Z3mfmI9ADVCHVYZtRvrILJFJaGIPJKAEfeMgKc8+n1qv4Z0u40i0kt7vUZtQkL7xLNnIB428k8cfrToLpG1bU4kuz5kTQBklU7I9w4C89W/njrXPO0ZWiuZd9ref6fM7KcZ1I8z0tq1v5W/Hf5ELXuoefDELjSFkLurxGZi2AgKhTgc87jxwCPqbWpT3fkj+z57BZMtuNwSVGMjsfXg/jWdIYzd2SI2gOizSDY2A6cKTs65bJyeB1H1NvWGuTbg2v9lTuDINt0Si4wwxkbsY4zx2PTPEjNaX/AFZqvViX'||
  '/Vmq9AE+WEOUALbeATgE/WqUt9cJp6Tx2YmmIUmBJ0yPXDHCnH1q+vKD6VB9htMAfZYMB/M/1Y+9knd9cknPqTQBWl1C4RiF02d1+YhhLEBgZx1bvjj6jOOcYHxGu44dBhe5ijC/alUCRlwfkY5FdI2l2DxSxtY2rRysXkUwqQ7EgkkY5JIB+oFYfjKz0mHRo0vNN863a4VvLt4x9/YQGIBHYY/KmqsaL9pNNpdFv+hM6TrL2adr9Ty/+1bD/nnZ/wDfaf4Uf2tYf887P/vtP8K2jbeFsf8AIAvf+/R/+Lpfs3hb/oAXv/fo/wDxda/27g/+fE/w/wDkjm/sSt/z/l96/wAzE/taw/552f8A32n+FH9rWH/POz/77T/CtxLTww7BU8PXzMegERJP/j9dbYeBvDktpFLLpKgyKH2uXVlyAcEZ6itqGbYStLlVKS9bf/JEVMnq01d15feebf2tYf8APOz/AO+0/wAK9d8H2kNvoVrJHBHFJOgdyqBS2SSMnvgHiqT+A/DIHGkxdR/G/r9a6WCJIII4Yl2xxqEVfQAYAp4qvSqRSpRt/XqXh8LKhJt1JSv3HjoKKB0FFcR1mDPbfZZ9QuIop7Np5It1xApnaYDI+4AduM9ce54FSSIYwsv27VizoIvlhzyjHLldmATzngAjGB0qOBTbalqs01m2nJJLEEuxMJPtR5AGznZyQPfNNttXh8x/P1iIrFKEf/R/L+YfKVye2SvPr354uas/6/4Ik5te+7v7/Tt0/pl6BGKF/tmoMu/f88QB2seFxsBwOn971JqeGMzIki3N0AMAh0ClipwSQVzzjtxjketZAuHVbZ11u4cXGYo2NqpR2YFlZSFHbGDkqQD3+YSRahFI4SDWhM'||
  'cwh8Qh8bumCowpbI65wOwzmoGb1FR26SRxbZZTK+SdxUDgkkDA9BgfhUlABTB/rj9KfTB/rj9KAI7mcwKXYRiIDLO8gUDnvmoYbyd0DNa4Hmsnyyq3yh9obr0I+bHUdOtW5ESRGSRVdGGCrDII96pro+mKwZdOswwQxgiBchSMFenTAAx6UARNqjLdxReQjRurAyC4T/WA48sAnJPyyE+mw9ecYfj2SObw/A17EYh9oX5C2SDsY87e/JrpJNMsJDmSxtXPz8tEp+/9/t/Fk59e9YfjfTLW40hI/tv9lq1yJWliYRl22EYJ4zxj/vkelVGrTov2lV2ityZQqVFy0pOMns1ujzbbpvp/6FW7ovhVNYszc2nkiMMU+d3ByMe3vXWeDPDr6Il2Z726vDMVAFyc7Nuen13fpXTgADgAfSuqeLpTV6K07/8AAaTOWnRxkJfvMTNr1kv/AG5nJaV4I0yO2K6japLPuPzJLIBj8xXWN1X6/wBKB1P1obqv1/pXLKTk7s7nOcoqM5OVu7b/ADFpE+4v0paRPuL9KkkWiiigAoHQUUDoKAGj/Wt9B/WqNvciTU7+BLsO8JjzC0eBFkZ698/pV4f61voP61Tto7ldSvnlvfOt38vyrbygvkYHzfN1bJ556U1KK0k99v69LkuLbTXT+v6uYks+6x065M/ht4o0eUzMf3cSgKd0RycgdzxxjpW+217xYpXtnyjMIivz/eHI56cgHjrj6VzV3b3VzpcQHh+1nkiSVRHdTJ8p2AKEwzABj8vUYHp0rd1AXEey4sbJJrry3UFyAR8pYKWzwCwUHGefzCKNCX/Vmq9WJf8AVmq9AFlPuL9KWkT7i/SloAK5vx5oVz4g0iG0s2gWRJxKTMzA'||
  'YCsOwPPIrpKr3EM8l3bSRXTRQxlvNhCA+bkYGSeRg88daabi7oPdfxRUl2aun6pnk5+GWrgE+dpvH/TST/4ml/4Vlq//AD203/v5J/8AE163PG7xMsUnluQcEjI6dxUFnb3MGnrFPd/aboKQZ3jChjzglVIGBxwPStPb1f5397K5cN/0DU//AAXH/I4rwX4Fn0fV/tmpfZJfLU+SYZHJV/XBAHTNegVniRtPjLX920y4ABEJzkZ5O3PUYHTr06gVTN6F1N7j+03e0G6I2iWxbDqcH5gN2cg8dxkgYGREpym7ydyOWnFv2cIxT6RSS+5G2/3R9R/OlrJnuBqKyQabey29xsba5tyyjkfONwAPtg4OT1xxckguDYrFHdFbkKoM5QHJGMkr055/OpGWh0FFQ20csasJ5hKxOQQu3AwOOp75P4+2aghtrtL3zHvjJb4b9yYgDksSPm9AMD8OtAGZqGoSwm/Mm/TI4pYgl0YzN5+T90Jj8OM9aoR6sbidYbfxA4lkkby1fTW5xIU2nIHAIwTwcc5wQas6fayJrPiB7G3uYLi4eINcXH+rPysN0Y2/Ntz0J545FaaW2pxLKv21bjftRWdFjaIYwW4Uhm6HBAH0FTGCguWL/TfX+u43zfbjyvte/o/mtbdL2MW11qK5R0g12Z5JGeFP+JewKOqNkY29ckHnrtwByabHqTRTyGfxG8nkszyQjT8MF+UYIxu4LKfx/Ld+x6jujH9qkRoMk+Qm9zuz8x6bccEBQe4IphsNTNrHF/bLiQY3zC3Tc3XOB90ZyOx6VQijpwv76P8A0bxAZGtS9vcE2KrvlwSDg9MbkPHBx71q2tteJdSSXF+ZYmbKxCFVCjHTPJPPOc1HdWWoSLILfV'||
  'XhLKQCYEbY27II9scEHOQByDklkdlqht4PM1UC4VFWQrbrsc5BJwecnBHBA56UAatMH+uP0p9MH+uP0oAfRRRQAVT1XTLPVbdYNQh82JXDhdxXnBGeCPU1cqOVJGkiZJdiKSXXbneMHjPbnB/ClKKkrSV0VGTg+aLsySimyKWRgrFWI4brimW0ciQKs8olkHBcLtz6cZ64/wAjpTJJB1P1obqv1/pUFvDMksjzXHmBidqBNqoMnGOpzjAJJ5IyAOlJfERQmZ52hhhBkkIXJwOT68YBB4zzxigCzSJ9xfpVN7yGWK7WGWRXhDBmWNiUPPQY5PGcDPUdiM0l1mysLeGPULyQylfvtbuhbjcOMccfqCOoIoA2qKzrBLiS7muvt3nWMqjy4DDsaIg8/NnPrkEZyO3OZ7yC5leJrW78hVzvUxhw/THfjp+RPsQAWqB0FNkVijBG2uQcE5IB+maSKMopDSM/JILcEAnOOPTp+HOTzQAo/wBa30H9ay7O6abW9VtxeLP5Hk/6N5ZXyNy5+9j5s9e+OnFXYoJlvJZXuWaJvuRbAAowO/UnIJ/4ERzxiVIIY5pJUijWWXG9woDPjgZPfFFk9/69RNyXw2t19PLs72+V0YjQ3G+xCaXOI490e77cVZFG0qWAb5ssOhJ469Sta1zLcRRkwWvnNtYhRIF5A4BJ9ent+tWaKBjZf9War1Yl/wBWar0AWU+4v0pajWRQoHPSl81fegB9FM81fejzV96AH0UzzV96PNX3oAWRElQpIquh6qwyDTqZ5q+9Hmr70APopnmr70eavvQA+imeavvR5q+9AD6KZ5q+9Hmr70APopnmr70eavvQA+imeavvR5q+9AD6YP8AXH6U2SXEbGMBnwdo'||
  'Y4BPbJwcflVXTTcpbJ/aLxPc4O8xAhepIAzzgDA5oAv0VzsugxyeKhrJu5QRGU2KCG5XaU3g/wCr6Nsxw43AjJB07q3854nS6uIWR937tuGGHGCDkfx5+qrngYq5KKtZ3Ii5O91Yv0Vmw286XMkr6hPIjIFELIoRCFAJGAG5PPLHr9KmMbbj/pU2MHjA65Bz09semDUFlyis6C3ljmLyajcyoYwgjZUChhj5wQucn3JHtT2ikM3mC8mVdm0xhVK545GRnt6nrQBeoqlbRNFAkc13PcMoIaSTCs/PGdoAH4AU6RDLZyW8k8g3x7PMj+RxkYLA9j3GOlAFvAznHPrRWe8Erbf9OnGFIICrhjhhnpnuDwf4R05zB9in+1Cc6pdHG793tUJgkHGAO2MAnJwTzk5oA16KyJtOeX7QTql+ryFSjKwHlbSx4AGDndg5BzgZ6VNHbyIrhtQun3DgkJlT6j5fx5yOOABkEA0aKyJrCWQykatfpvk8wY2fJ0wq/L93gdcn1OCQZ7KCW3YGa/uLoc581EGeF/ugdNpP/Aj7YANCimeavvR5q+9AD6KZ5q+9Hmr70ALL/qzVemTPcNdoE8oWgQlySd5bPAAxgDGffp0xy+gDI8VyeJ4rWGTwnDpU7rG5ljvmcMxG3YE24HPzA7iByORzWvYC+FrD/aDWzXOxfNMCsqbto3bcknG7djPbH1qyn3F+lLQBzOnHxms9yNSHh6SHCmB7czI2dw3BlIP8JbBB6qDj5sKumDxizP8A2ofD8Sghl+zCZyRuGVO7bj5dw3c8kHbxg9LRQBz9z/wlUdu8dsdDuJyH2zyCWFUPlrszEN5YGTfn5xhduMnNTQ/8JEum2HnjSZNQMy/bChkSJYt/Pl'||
  '5ySwXgZwCeeBxWyrBxlTkZI/I4paAOYuT4z+zwC2Xw955x5zSGbaP3SZ2gDJ/eeaeSPlCDgkkQ6O/jn+34o9aj8Pf2QfMZ5LPzTKAOEX5iACcg5wRhW6cZ62igAooHNGecd6ACig0UAFFFFABRRRQBn23nlnackDAAXjGe5GOxz39Ks27TvJK0qiOPO1EOC3BOWJBxg8YHoOeTgSvKkeN7qoJAyTjkkAD8SR+dR213b3QJtp4pgOpjcMO/p9D+VNu4krECNqH9rurpCNO8v5WH39/Hv/vZGOy8nJAtD/XH6U23uIbhd1vLHKuAcowPB6U4f64/SkM5vSJPGB1u5j1eHRF0tYg0M1sZDI7mT7pBPGIxz7lcE8gaGtrr7WZ/sOTS0uhIuBeJIyFMDdypBBzuI65wBxnI16KAOQ1VvHxnf+yovCywlVK/aZLgsG2LuU7VGQGD4PGQRwCDnY1VNfaX/iUzaXFGRj/SYZHI+/z8rLnrGccdGGeQRr0UAYkS+JDejzZdHW0yCQsUjPjzCSPvAf6vAz/eBOCDtE6LrbR3avJpsbl5RbOEdwq5Hll1yMnG7cAR2wRWpQTgZNABRRRnrQAUUUUAFFFHegAopssiQxtJK6pGoyzMcAD1Jqv/AGjZb2T7Zb7125XzFyNxAXv3JAH1oAtUVVi1GymAMV5bOCSo2yqckAkjr2AP5UQ6jYzyJHBeW0kj52qkqktjrgA84oAtUUUUANl/1ZqvViX/AFZqvQBZT7i/Slpu4LFuOcBcnAyfyqudQtRbwTmX91PjyztPzZXcABjOSB0/DrQBaoqlb6pZ3EEcsUpMci71JRl+X5eSCOPvKeexzSW2q2VyYhBNvMo3IAjcjOD24wcZ9Mj1oA46'||
  '+17X7e/u4bWTRxAk8gQSpKWxuPXHGah/4STxL/z10L/viaue12GzOuaiZJpA5uZcgdvnPtVHyLD/AJ7y/wCfwroWExrV042/wP8A+SOV43KE7Tqzv1Ov/wCEk8S/89dC/wC+JqP+Ek8S/wDPXQv++Jq5S3s7S4njhhmlaSRgijpkk4A6V6V4H0KTRYLszrIsszKMM6sMKDgjH+8azq0sXSXvSj/4B/8AbGtKrl1dP2E6jf3L77GAPEfiUf8ALXQ/++JqT/hI/Eu4HzdD6f3Jq9FXp+JpD/rF+h/pXPz4n+aP/gH/ANsaexof3v8AwL/gHnh8SeJSP9bof/fE1H/CSeJf+euhf98TV6K33T9KKOfE/wA0f/AP/tg9jQ/vf+Bf8A46yuPGV5bJPC/h8xvnGRMOhx/Sp9vjb+/4e/8AI1dVRXVGu0lzRV/QweGV9JS+85q0Xxf9qi+2NoX2bePN8rzd+3PO3PGcVo+KEL6FcqLm5tc7f31scSL8w6cj6dehNah6Gs/xBkaRcbbxrI/L+/VNxT5h29+n41E5ym/csn006+nU0p04QVqkny9bvp11I1WN7e1Mj2szRmNRJcAF1JC8dfvNx3HUde8OhYEQdv7JQyEANZciUAH+WPfgH8LPnGOOzU3Vt823DzDDP90YAz1OevYkcGqfhlibaQB9G3kqxOncqwKjDEds4468Dr6Rr1NNOmxN4ekV4MM2ltOEXP2A5XZuYL74yHx2yG9DWoP9cfpVLSUsNnm2QsWlaNEkktVUBgu4AcZ+UHfgZOOfero/1x+lAD6KY8qI4Vjhj049wP6iqlzq1jbGcXFykZhx5mc/LkE/yBNAF6uC1HX/ABDDqF1FbyaMIUlZUEiS7toJAzjjOP'||
  'Suui1iwlfbHcqSXEYO0gFicAA4wcnp64Poa8o16GyOuaiXmkDG5kyB2O4+1aU6Vao7UbX84836oyq1sJSV8XKUV05Tof8AhJPEuf8AW6H/AN8TUh8R+JSCPN0P/viasHSdA/tbzf7P82bysb/nVcZzjrj0NXz4IvwMmCX/AL+pRKliYu0pwT/wf/bDhVy2ouaEqrXkn/kaH/CSeJf+euhf98TUg8R+Jef3uh8/7E1Uf+EHv/8AnhL/AN/U/wAa2dN8AWclojX0t5HcZO5UkTA54/hPbFRJYiP24f8AgH/2xvShl9V2Uqi9br9Cr/wkniX/AJ66F/3xNWvA/jSeCOWN/D2x1DDIm6Go/wDhXmlf8/N//wB/E/8Aia620gW1tYbeMsUiRUUt1IAxzTp1KkX77jL/ALdt+rFiMLh0l7Gcvmyrog1QWjf22bM3O87fsm7ZtwMZ3c5zn9KvfxD6UtJ/EPpSk+Z3M4x5VYxL3MeuXMwvXj26e37qc/6MvzZ8xuevr7d6zYIpbq1kuYB4YnuWRWkdELIx8wEsWBzj5XwP7y5z1A2Zg7a3Iq3mc2hxaOhKZ3f6wn9MVnwWOpQpJDFZeH7ezaNiYUViGk2t14A2kkZ4zjI75pe99p3/AMirQ+x8/UgaVbRfLtJvDMQt5cyg/IIm8s7+AeGJVzz/AAg5zg1YVp0u7JIX0BJF+XYM78/8tdnp0bjnpz0q/BBcRyORaaYm6X5tjEEr2Y/L94env1FFtDdJc+ZJa6ahkcrK0bHe64OGzt68/dPTJ+Y0AVEv9Ra4aE3uibwj/KHYsHCg4Iz0G4MT1wQMc5pzaldS3qxWWoaLJ5kZaGMuS8hy3TDdAAeQDkqenbUS2sZEiZIbZkUZjIRS'||
  'ACO34H8jTobW0hZTDBBGyghSiAEAnkD8qAJpf9War1Yl/wBWar0AWU+4v0qjNpu+6mnS9vYmkUDasuUUjuqkEA8c9vbNXk+4v0paAKK6ewj2NfXjnduLFwCeoxwBgYOOMdARzzTLfShBjbe3p/e+c26XO47mYg8cDLdBjoPx0aKAPKNT8L2V9rt47eIZIZprqT9ysq/KS5+UDNek/wBj6Z/0DrP/AL8L/hUcGlaeztO1haGfzXfzDCpbO485xnNaVKFXEu6qzuumyt9yQ6tOhK3LH1vYpJpWnRurx2ForqQVZYVBB9RxV2iiqcnLdkRhGPwqwi9PxNIf9Yv0P9KVen4mkP8ArF+h/pSKHN90/Sihvun6UUAFFFFAAehrM8S3iWGiXNzLffYETbm58rzdmWA+73znH41pnoaq6peQ2FjLc3M3kRJjdJtLYyQOg+tDmqfvvZa9P10+/QOT2nud9NP+BqUJZ/3+lzLNZOJIsCSZQsj7mi+5kjAPcYPOz0pnhtLiP7Tug0mKFgjJ9g/jcrklj7jZgenc8VauZGZ7Se3tpboOm3ekgRVVimSQWHOBkcE8Y4zzHoS3MfmpcWLWygIys10ZyxwRjJORgAe3J69aL31C1tC5plt9lsYYzFbxS7AZBbx7EL45IHYZ9zU4/wBcfpVbTJ7ueHdfWi2r/wBwSh+57j6D86sj/XH6UAMng80qfNlTa24bGx2x+I9qqw6X5X/L9fOdzHLy5+Ug/L0xgZ4PXgc1oUUAUorBkmMrX15ISVJDMu3gdMAY5xk1yOjeHbFvGGoXT6gL1meV3tJCrqhLemeME46V3dcj4LsrmLXPEdzdwNH5l0ywM8OwlNzHIbHIOR+QpqVSOtOfL3Xf8P8AIf'||
  'KpJ3hdd9NPv1fbS/3HTWtnbWhb7LbQwbvveWgXOOmcVO/3G+lL3FI/3G+lDbbuyUlFWQtIvVvr/SlpF6t9f6Uhi0UUUAFJ/EPpS0n8Q+lAGPc3EM+vTabLcpPvsi76c8GVZC20uXIwQfu7ajeznNvbiXR9KmkiMUnL7VV1UgsvyHG3ovse1Xbq6ie7msEcSXRtzKLc5TK5xneBxzx696yzp0ttv8jSNyHO4Rag4ZuGUHBwCcdye45yODnU9umnT9P11Dk5PnqTQabFCYUTRtKRkBWJFCr5UbBTIB8v94noADxnBrTWyt5raNbqyts7FUx7QyrjnaOOQD04rntPivLeeKYeGnieNJpA39oK+HY8qMnkNgEk4APOM109rJJLArzwtBIc5jZg2OfUce/+FAFY6PphEwOnWZEyeXIDAvzrgLtbjkYVRg9lA7VLc6fZXSyrc2lvMso2yCSJWDjjg5HPQflVmigBsv8AqzVerEv+rNV6ALKfcX6UtFFABTJn8uF3xnapbHriiigCGwZpLSOTgeYPMxjpu5x+tYUfidn8Q2+l/ZQPOuLiDzd/TykRs4x334xnjHeiigDa1O7axsZrjaH8tc7emeR3o0+8a80m2vdoTzoFm2dcZUHGfxoooAo6HrLaneX9v5Ii+yuV3bt27Esqe2P9Xn8fbmbVNRaxlg/dh/MmSHrjG50XP4b8/hRRQAeItTbSNMluvKE2xJG25252RO/Xnrsx+NWtPuWu7RJ9oTcWG3r0JH9KKKAKWlau1/fz23kiPyreGfduznzC/GPbZ175o1jV2067sYPJEn2qZYt27G3JAz79aKKALepXbWcKvtD7iwx06Izf+y/rWBqetXF34Fm1O022s7EBcgSbcShT'||
  '1GDkA9u9FFaUknUin3Rz4xuOHqNOzs/yL0d0ktjHJcQ+Y8UtvGSG2hmfyvnIHHBcED/Z7VX8NXFmLO0ks7H7Ot02NpmZ9mFkPGf9w9MfeP4lFRLc2h8KH+Cns5tOM9jZfZAwClfNMnALY5P1P51vj/XH6UUUih9FFFABVDQ79tU0q2vdgi85c7M7sckdePSiigCnfa01r4l07SvID/a1Y+buxswrN07/AHPXvWhqVw1paNLgP8yJjp95gv8AWiigCaB2lgjk4G9Q2MdMioRct/aP2baOYzLu/EDGPxoooAqapqzWOraXZeUH+3NIu/djZtXd075/CtRyyoxyOBnpRRQBnaDqbatYi58sRfMy7c7ujFevHpVXX9ebSNT0i1NuJvt83k7t+3y+VGcYOevtRRQBQ8QajJa6tqYmAnsIdHkuGtsBS7BufnA3DI4rlrPUdEu9GtHOgbYovMSOP7bIdohWWVecc8of++u+MUUVpUSVrdjmw0m+e7+0zbhu9Mj1Kewj0kKpuImZhcN8zyo+Wx7AEY9+2K3PCfiL/hILCC5+y/Z/NR22+ZvxtkKdcD0zRRWZ0m9RRRQA2X/Vmq9FFAH/2Q==';



  INSERT INTO EMS_DASHBOARD (DASHBOARD_ID,NAME,TYPE,DESCRIPTION,CREATION_DATE,LAST_MODIFICATION_DATE,
                             LAST_MODIFIED_BY,OWNER,IS_SYSTEM,APPLICATION_TYPE,ENABLE_TIME_RANGE,SCREEN_SHOT,
                             DELETED,TENANT_ID,ENABLE_REFRESH,SHARE_PUBLIC,ENABLE_ENTITY_FILTER,ENABLE_DESCRIPTION,EXTENDED_OPTIONS)
  VALUES(V_DASHBOARD_ID,V_NAME,V_TYPE,V_DESCRIPTION,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,
         V_OWNER,V_IS_SYSTEM,V_APPLICATION_TYPE,V_ENABLE_TIME_RANGE,V_SCREEN_SHOT,V_DELETED,V_TENANT_ID,
         V_ENABLE_REFRESH,V_SHARE_PUBLIC,V_ENABLE_ENTITY_FILTER,V_ENABLE_DESCRIPTION,V_EXTENDED_OPTIONS) RETURNING SCREEN_SHOT INTO V_CLOB;

  V_TILE_ID                     := 150;
  V_TITLE                       := 'Total DNS Messages';
  V_HEIGHT                      := 1;
  V_WIDTH                       := 6;
  V_IS_MAXIMIZED                := 0;
  V_POSITION                    := 0;
  V_WIDGET_UNIQUE_ID            := 3300;
  V_WIDGET_NAME                 := 'Total DNS Messages';
  V_WIDGET_DESCRIPTION          := 'The Total number of DNS Messages';
  V_WIDGET_GROUP_NAME           := 'Log Analytics';
  V_WIDGET_ICON                 := null;
  V_WIDGET_HISTOGRAM            := null;
  V_WIDGET_OWNER                := CONST_ORACLE;
  V_WIDGET_CREATION_TIME        := SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_WIDGET_SOURCE               := 1;
  V_WIDGET_KOC_NAME             := 'emcla-visualizationemcla-visualization';
  V_WIDGET_VIEWMODE             := '/js/viewmodel/search/widget/VisualizationWidget.js';
  V_WIDGET_TEMPLATE             := '/html/search/widgets/visualizationWidget.html';
  V_PROVIDER_NAME               := 'LogAnalyticsUI';
  V_PROVIDER_VERSION            := '1.0';
  V_PROVIDER_ASSET_ROOT         := 'assetRoot';
  V_TILE_ROW                    := 0;
  V_TILE_COLUMN                 := 0;
  V_TILE_TYPE                   := 0;
  V_TILE_SUPPORT_TIMECONTROL    := 1;
  V_TILE_LINKED_DASHBOARD       := null;
  INSERT INTO EMS_DASHBOARD_TILE(TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,
                                 WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,
                                 WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,
                                 TYPE,WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD)
  VALUES(V_TILE_ID,V_DASHBOARD_ID,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_OWNER,V_TITLE,V_HEIGHT,V_WIDTH,V_IS_MAXIMIZED,V_POSITION,V_TENANT_ID,
         V_WIDGET_UNIQUE_ID,V_WIDGET_NAME,V_WIDGET_DESCRIPTION,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_HISTOGRAM,V_WIDGET_OWNER,V_WIDGET_CREATION_TIME,V_WIDGET_SOURCE,V_WIDGET_KOC_NAME,
         V_WIDGET_VIEWMODE,V_WIDGET_TEMPLATE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TILE_ROW,V_TILE_COLUMN,V_TILE_TYPE,V_TILE_SUPPORT_TIMECONTROL,V_TILE_LINKED_DASHBOARD);


  V_TILE_ID                     := 151;
  V_TITLE                       := 'Unique DNS Queries';
  V_HEIGHT                      := 1;
  V_WIDTH                       := 6;
  V_IS_MAXIMIZED                := 0;
  V_POSITION                    := 0;
  V_WIDGET_UNIQUE_ID            := 3301;
  V_WIDGET_NAME                 := 'Unique DNS Queries';
  V_WIDGET_DESCRIPTION          := 'Number of Unique DNS Queries for all DNS Message';
  V_WIDGET_GROUP_NAME           := 'Log Analytics';
  V_WIDGET_ICON                 := null;
  V_WIDGET_HISTOGRAM            := null;
  V_WIDGET_OWNER                := CONST_ORACLE;
  V_WIDGET_CREATION_TIME        := SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_WIDGET_SOURCE               := 1;
  V_WIDGET_KOC_NAME             := 'emcla-visualization';
  V_WIDGET_VIEWMODE             := '/js/viewmodel/search/widget/VisualizationWidget.js';
  V_WIDGET_TEMPLATE             := '/html/search/widgets/visualizationWidget.html';
  V_PROVIDER_NAME               := 'LogAnalyticsUI';
  V_PROVIDER_VERSION            := '1.0';
  V_PROVIDER_ASSET_ROOT         := 'assetRoot';
  V_TILE_ROW                    := 0;
  V_TILE_COLUMN                 := 6;
  V_TILE_TYPE                   := 0;
  V_TILE_SUPPORT_TIMECONTROL    := 1;
  V_TILE_LINKED_DASHBOARD       := null;
  INSERT INTO EMS_DASHBOARD_TILE(TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,
                                 WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,
                                 WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,
                                 TYPE,WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD)
  VALUES(V_TILE_ID,V_DASHBOARD_ID,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_OWNER,V_TITLE,V_HEIGHT,V_WIDTH,V_IS_MAXIMIZED,V_POSITION,V_TENANT_ID,
             V_WIDGET_UNIQUE_ID,V_WIDGET_NAME,V_WIDGET_DESCRIPTION,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_HISTOGRAM,V_WIDGET_OWNER,V_WIDGET_CREATION_TIME,V_WIDGET_SOURCE,V_WIDGET_KOC_NAME,
             V_WIDGET_VIEWMODE,V_WIDGET_TEMPLATE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TILE_ROW,V_TILE_COLUMN,V_TILE_TYPE,V_TILE_SUPPORT_TIMECONTROL,V_TILE_LINKED_DASHBOARD);

  V_TILE_ID                     := 152;
  V_TITLE                       := 'Top 10 DNS Domains';
  V_HEIGHT                      := 2;
  V_WIDTH                       := 6;
  V_IS_MAXIMIZED                := 0;
  V_POSITION                    := 0;
  V_WIDGET_UNIQUE_ID            := 3302;
  V_WIDGET_NAME                 := 'Top 10 DNS Domains';
  V_WIDGET_DESCRIPTION          := 'Top 10 DNS Domains with the largest number of DNS queries';
  V_WIDGET_GROUP_NAME           := 'Log Analytics';
  V_WIDGET_ICON                 := null;
  V_WIDGET_HISTOGRAM            := null;
  V_WIDGET_OWNER                := CONST_ORACLE;
  V_WIDGET_CREATION_TIME        := SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_WIDGET_SOURCE               := 1;
  V_WIDGET_KOC_NAME             := 'emcla-visualization';
  V_WIDGET_VIEWMODE             := '/js/viewmodel/search/widget/VisualizationWidget.js';
  V_WIDGET_TEMPLATE             := '/html/search/widgets/visualizationWidget.html';
  V_PROVIDER_NAME               := 'LogAnalyticsUI';
  V_PROVIDER_VERSION            := '1.0';
  V_PROVIDER_ASSET_ROOT         := 'assetRoot';
  V_TILE_ROW                    := 1;
  V_TILE_COLUMN                 := 0;
  V_TILE_TYPE                   := 0;
  V_TILE_SUPPORT_TIMECONTROL    := 1;
  V_TILE_LINKED_DASHBOARD       := null;
  INSERT INTO EMS_DASHBOARD_TILE(TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,
                                 WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,
                                 WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,
                                 TYPE,WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD)
  VALUES(V_TILE_ID,V_DASHBOARD_ID,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_OWNER,V_TITLE,V_HEIGHT,V_WIDTH,V_IS_MAXIMIZED,V_POSITION,V_TENANT_ID,
             V_WIDGET_UNIQUE_ID,V_WIDGET_NAME,V_WIDGET_DESCRIPTION,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_HISTOGRAM,V_WIDGET_OWNER,V_WIDGET_CREATION_TIME,V_WIDGET_SOURCE,V_WIDGET_KOC_NAME,
             V_WIDGET_VIEWMODE,V_WIDGET_TEMPLATE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TILE_ROW,V_TILE_COLUMN,V_TILE_TYPE,V_TILE_SUPPORT_TIMECONTROL,V_TILE_LINKED_DASHBOARD);

  V_TILE_ID                     := 153;
  V_TITLE                       := 'Top 10 DNS Sources';
  V_HEIGHT                      := 2;
  V_WIDTH                       := 6;
  V_IS_MAXIMIZED                := 0;
  V_POSITION                    := 0;
  V_WIDGET_UNIQUE_ID            := 3303;
  V_WIDGET_NAME                 := 'Top 10 DNS Sources';
  V_WIDGET_DESCRIPTION          := 'Top 10 DNS Sources with the largest number of DNS queries';
  V_WIDGET_GROUP_NAME           := 'Log Analytics';
  V_WIDGET_ICON                 := null;
  V_WIDGET_HISTOGRAM            := null;
  V_WIDGET_OWNER                := CONST_ORACLE;
  V_WIDGET_CREATION_TIME        := SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_WIDGET_SOURCE               := 1;
  V_WIDGET_KOC_NAME             := 'emcla-visualization';
  V_WIDGET_VIEWMODE             := '/js/viewmodel/search/widget/VisualizationWidget.js';
  V_WIDGET_TEMPLATE             := '/html/search/widgets/visualizationWidget.html';
  V_PROVIDER_NAME               := 'LogAnalyticsUI';
  V_PROVIDER_VERSION            := '1.0';
  V_PROVIDER_ASSET_ROOT         := 'assetRoot';
  V_TILE_ROW                    := 1;
  V_TILE_COLUMN                 := 6;
  V_TILE_TYPE                   := 0;
  V_TILE_SUPPORT_TIMECONTROL    := 1;
  V_TILE_LINKED_DASHBOARD       := null;
  INSERT INTO EMS_DASHBOARD_TILE(TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,
                                 WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,
                                 WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,
                                 TYPE,WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD)
  VALUES(V_TILE_ID,V_DASHBOARD_ID,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_OWNER,V_TITLE,V_HEIGHT,V_WIDTH,V_IS_MAXIMIZED,V_POSITION,V_TENANT_ID,
             V_WIDGET_UNIQUE_ID,V_WIDGET_NAME,V_WIDGET_DESCRIPTION,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_HISTOGRAM,V_WIDGET_OWNER,V_WIDGET_CREATION_TIME,V_WIDGET_SOURCE,V_WIDGET_KOC_NAME,
             V_WIDGET_VIEWMODE,V_WIDGET_TEMPLATE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TILE_ROW,V_TILE_COLUMN,V_TILE_TYPE,V_TILE_SUPPORT_TIMECONTROL,V_TILE_LINKED_DASHBOARD);

  V_TILE_ID                     := 154;
  V_TITLE                       := 'Top 10 DNS Sources with TXT Lookup';
  V_HEIGHT                      := 2;
  V_WIDTH                       := 6;
  V_IS_MAXIMIZED                := 0;
  V_POSITION                    := 0;
  V_WIDGET_UNIQUE_ID            := 3304;
  V_WIDGET_NAME                 := 'Top 10 DNS Sources with TXT Lookup';
  V_WIDGET_DESCRIPTION          := 'Top 10 DNS Sources with the largest number of TXT Lookup queries';
  V_WIDGET_GROUP_NAME           := 'Log Analytics';
  V_WIDGET_ICON                 := null;
  V_WIDGET_HISTOGRAM            := null;
  V_WIDGET_OWNER                := CONST_ORACLE;
  V_WIDGET_CREATION_TIME        := SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_WIDGET_SOURCE               := 1;
  V_WIDGET_KOC_NAME             := 'emcla-visualization';
  V_WIDGET_VIEWMODE             := '/js/viewmodel/search/widget/VisualizationWidget.js';
  V_WIDGET_TEMPLATE             := '/html/search/widgets/visualizationWidget.html';
  V_PROVIDER_NAME               := 'LogAnalyticsUI';
  V_PROVIDER_VERSION            := '1.0';
  V_PROVIDER_ASSET_ROOT         := 'assetRoot';
  V_TILE_ROW                    := 3;
  V_TILE_COLUMN                 := 6;
  V_TILE_TYPE                   := 0;
  V_TILE_SUPPORT_TIMECONTROL    := 1;
  V_TILE_LINKED_DASHBOARD       := null;
  INSERT INTO EMS_DASHBOARD_TILE(TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,
                                 WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,
                                 WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,
                                 TYPE,WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD)
  VALUES(V_TILE_ID,V_DASHBOARD_ID,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_OWNER,V_TITLE,V_HEIGHT,V_WIDTH,V_IS_MAXIMIZED,V_POSITION,V_TENANT_ID,
             V_WIDGET_UNIQUE_ID,V_WIDGET_NAME,V_WIDGET_DESCRIPTION,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_HISTOGRAM,V_WIDGET_OWNER,V_WIDGET_CREATION_TIME,V_WIDGET_SOURCE,V_WIDGET_KOC_NAME,
             V_WIDGET_VIEWMODE,V_WIDGET_TEMPLATE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TILE_ROW,V_TILE_COLUMN,V_TILE_TYPE,V_TILE_SUPPORT_TIMECONTROL,V_TILE_LINKED_DASHBOARD);

  V_TILE_ID                     := 155;
  V_TITLE                       := 'Top 10 DNS Non-Standard TLDs';
  V_HEIGHT                      := 2;
  V_WIDTH                       := 6;
  V_IS_MAXIMIZED                := 0;
  V_POSITION                    := 0;
  V_WIDGET_UNIQUE_ID            := 3305;
  V_WIDGET_NAME                 := 'Top 10 DNS Non-Standard TLDs';
  V_WIDGET_DESCRIPTION          := 'Top 10 Non-Standard TLDs with the largest number of queries';
  V_WIDGET_GROUP_NAME           := 'Log Analytics';
  V_WIDGET_ICON                 := null;
  V_WIDGET_HISTOGRAM            := null;
  V_WIDGET_OWNER                := CONST_ORACLE;
  V_WIDGET_CREATION_TIME        := SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_WIDGET_SOURCE               := 1;
  V_WIDGET_KOC_NAME             := 'emcla-visualization';
  V_WIDGET_VIEWMODE             := '/js/viewmodel/search/widget/VisualizationWidget.js';
  V_WIDGET_TEMPLATE             := '/html/search/widgets/visualizationWidget.html';
  V_PROVIDER_NAME               := 'LogAnalyticsUI';
  V_PROVIDER_VERSION            := '1.0';
  V_PROVIDER_ASSET_ROOT         := 'assetRoot';
  V_TILE_ROW                    := 3;
  V_TILE_COLUMN                 := 0;
  V_TILE_TYPE                   := 0;
  V_TILE_SUPPORT_TIMECONTROL    := 1;
  V_TILE_LINKED_DASHBOARD       := null;
  INSERT INTO EMS_DASHBOARD_TILE(TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,
                                 WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,
                                 WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,
                                 TYPE,WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD)
  VALUES(V_TILE_ID,V_DASHBOARD_ID,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_OWNER,V_TITLE,V_HEIGHT,V_WIDTH,V_IS_MAXIMIZED,V_POSITION,V_TENANT_ID,
             V_WIDGET_UNIQUE_ID,V_WIDGET_NAME,V_WIDGET_DESCRIPTION,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_HISTOGRAM,V_WIDGET_OWNER,V_WIDGET_CREATION_TIME,V_WIDGET_SOURCE,V_WIDGET_KOC_NAME,
             V_WIDGET_VIEWMODE,V_WIDGET_TEMPLATE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TILE_ROW,V_TILE_COLUMN,V_TILE_TYPE,V_TILE_SUPPORT_TIMECONTROL,V_TILE_LINKED_DASHBOARD);

  V_TILE_ID                     := 156;
  V_TITLE                       := 'DNS Queries Per Domain';
  V_HEIGHT                      := 2;
  V_WIDTH                       := 6;
  V_IS_MAXIMIZED                := 0;
  V_POSITION                    := 0;
  V_WIDGET_UNIQUE_ID            := 3306;
  V_WIDGET_NAME                 := 'DNS Queries Per Domain';
  V_WIDGET_DESCRIPTION          := 'The total number of DNS Queries for each Domain';
  V_WIDGET_GROUP_NAME           := 'Log Analytics';
  V_WIDGET_ICON                 := null;
  V_WIDGET_HISTOGRAM            := null;
  V_WIDGET_OWNER                := CONST_ORACLE;
  V_WIDGET_CREATION_TIME        := SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_WIDGET_SOURCE               := 1;
  V_WIDGET_KOC_NAME             := 'emcla-visualization';
  V_WIDGET_VIEWMODE             := '/js/viewmodel/search/widget/VisualizationWidget.js';
  V_WIDGET_TEMPLATE             := '/html/search/widgets/visualizationWidget.html';
  V_PROVIDER_NAME               := 'LogAnalyticsUI';
  V_PROVIDER_VERSION            := '1.0';
  V_PROVIDER_ASSET_ROOT         := 'assetRoot';
  V_TILE_ROW                    := 5;
  V_TILE_COLUMN                 := 0;
  V_TILE_TYPE                   := 0;
  V_TILE_SUPPORT_TIMECONTROL    := 1;
  V_TILE_LINKED_DASHBOARD       := null;
  INSERT INTO EMS_DASHBOARD_TILE(TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,
                                 WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,
                                 WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,
                                 TYPE,WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD)
  VALUES(V_TILE_ID,V_DASHBOARD_ID,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_OWNER,V_TITLE,V_HEIGHT,V_WIDTH,V_IS_MAXIMIZED,V_POSITION,V_TENANT_ID,
             V_WIDGET_UNIQUE_ID,V_WIDGET_NAME,V_WIDGET_DESCRIPTION,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_HISTOGRAM,V_WIDGET_OWNER,V_WIDGET_CREATION_TIME,V_WIDGET_SOURCE,V_WIDGET_KOC_NAME,
             V_WIDGET_VIEWMODE,V_WIDGET_TEMPLATE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TILE_ROW,V_TILE_COLUMN,V_TILE_TYPE,V_TILE_SUPPORT_TIMECONTROL,V_TILE_LINKED_DASHBOARD);

  V_TILE_ID                     := 157;
  V_TITLE                       := 'DNS Responses by Type';
  V_HEIGHT                      := 2;
  V_WIDTH                       := 6;
  V_IS_MAXIMIZED                := 0;
  V_POSITION                    := 0;
  V_WIDGET_UNIQUE_ID            := 3307;
  V_WIDGET_NAME                 := 'DNS Responses by Type';
  V_WIDGET_DESCRIPTION          := 'The total number of DNS queries based on response type';
  V_WIDGET_GROUP_NAME           := 'Log Analytics';
  V_WIDGET_ICON                 := null;
  V_WIDGET_HISTOGRAM            := null;
  V_WIDGET_OWNER                := CONST_ORACLE;
  V_WIDGET_CREATION_TIME        := SYS_EXTRACT_UTC(SYSTIMESTAMP);
  V_WIDGET_SOURCE               := 1;
  V_WIDGET_KOC_NAME             := 'emcla-visualization';
  V_WIDGET_VIEWMODE             := '/js/viewmodel/search/widget/VisualizationWidget.js';
  V_WIDGET_TEMPLATE             := '/html/search/widgets/visualizationWidget.html';
  V_PROVIDER_NAME               := 'LogAnalyticsUI';
  V_PROVIDER_VERSION            := '1.0';
  V_PROVIDER_ASSET_ROOT         := 'assetRoot';
  V_TILE_ROW                    := 5;
  V_TILE_COLUMN                 := 6;
  V_TILE_TYPE                   := 0;
  V_TILE_SUPPORT_TIMECONTROL    := 1;
  V_TILE_LINKED_DASHBOARD       := null;
  INSERT INTO EMS_DASHBOARD_TILE(TILE_ID,DASHBOARD_ID,CREATION_DATE,LAST_MODIFICATION_DATE,LAST_MODIFIED_BY,OWNER,TITLE,HEIGHT,WIDTH,IS_MAXIMIZED,POSITION,TENANT_ID,
                                 WIDGET_UNIQUE_ID,WIDGET_NAME,WIDGET_DESCRIPTION,WIDGET_GROUP_NAME,WIDGET_ICON,WIDGET_HISTOGRAM,WIDGET_OWNER,WIDGET_CREATION_TIME,
                                 WIDGET_SOURCE,WIDGET_KOC_NAME,WIDGET_VIEWMODE,WIDGET_TEMPLATE,PROVIDER_NAME,PROVIDER_VERSION,PROVIDER_ASSET_ROOT,TILE_ROW,TILE_COLUMN,
                                 TYPE,WIDGET_SUPPORT_TIME_CONTROL,WIDGET_LINKED_DASHBOARD)
  VALUES(V_TILE_ID,V_DASHBOARD_ID,V_CREATION_DATE,V_LAST_MODIFICATION_DATE,V_LAST_MODIFIED_BY,V_OWNER,V_TITLE,V_HEIGHT,V_WIDTH,V_IS_MAXIMIZED,V_POSITION,V_TENANT_ID,
             V_WIDGET_UNIQUE_ID,V_WIDGET_NAME,V_WIDGET_DESCRIPTION,V_WIDGET_GROUP_NAME,V_WIDGET_ICON,V_WIDGET_HISTOGRAM,V_WIDGET_OWNER,V_WIDGET_CREATION_TIME,V_WIDGET_SOURCE,V_WIDGET_KOC_NAME,
             V_WIDGET_VIEWMODE,V_WIDGET_TEMPLATE,V_PROVIDER_NAME,V_PROVIDER_VERSION,V_PROVIDER_ASSET_ROOT,V_TILE_ROW,V_TILE_COLUMN,V_TILE_TYPE,V_TILE_SUPPORT_TIMECONTROL,V_TILE_LINKED_DASHBOARD);

  DBMS_OUTPUT.PUT_LINE('Out of box dashboards for Security Analytics have been created successfully! For '||V_TENANT_ID);
ELSE
  DBMS_OUTPUT.PUT_LINE('Out of box dashboards for Security Analytics had been created before, no need to create again.For '||V_TENANT_ID);
END IF;
     IF (V_TID<>-1) THEN
        EXIT;
     END IF;
  END LOOP;
  CLOSE TENANT_CURSOR;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Failed to create out of box dashboards for Security Analytics due to error '||SQLERRM);
    RAISE;
END;
/