/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

define({
      "BRANDING_BAR_COMMA": ",",
      "BRANDING_BAR_TEXT_ORACLE": "Oracle",
      "BRANDING_BAR_TEXT_APP_NAVIGATOR": "Application navigator",
      "BRANDING_BAR_TEXT_NOTIFICATIONS": "Notifications",
      "BRANDING_BAR_MANAGEMENT_CLOUD": "Management Cloud",
      "BRANDING_BAR_MENU_PREFERENCES": "Preferences",
      "BRANDING_BAR_MENU_HELP": "Help",
      "BRANDING_BAR_MENU_ABOUT": "About",
      "BRANDING_BAR_MENU_SIGN_OUT": "Sign Out",
      "BRANDING_BAR_LINKS_BTN_LABEL": "Links",
      "BRANDING_BAR_NAV_DASHBOARDS_LABEL": "Dashboards",
      "BRANDING_BAR_NAV_CLOUD_SERVICES_LABEL": "Cloud Services",
      "BRANDING_BAR_NAV_HOME_LABEL": "Home",
      "BRANDING_BAR_NAV_FAVORITES_LABEL": "My Favorites",
      "BRANDING_BAR_NAV_WELCOME_LABEL": "Welcome",
      "BRANDING_BAR_NAV_VISUAL_ANALYZER_LABEL": "Visual Analyzers",
      "BRANDING_BAR_NAV_ADMIN_LABEL": "Administration",
      "BRANDING_BAR_ABOUT_DIALOG_TITLE": "About Cloud Service",
      "BRANDING_BAR_ABOUT_DIALOG_SUB_TITLE": "Oracle Management Cloud",
      "BRANDING_BAR_ABOUT_DIALOG_COPY_RIGHT": "Copyright \u00a9 {0}, Oracle and/or its affiliates. All rights reserved. Oracle is a registered trademark of Oracle Corporation and/or its affiliates.",
      "BRANDING_BAR_ABOUT_DIALOG_COPY_RIGHT_WARNING": "Warning: Unauthorized access is strictly prohibited.",
      "BRANDING_BAR_ABOUT_DIALOG_CLOSE_BTN_LABEL": "Close",
      "BRANDING_BAR_ABOUT_DIALOG_ICON_ALT_TEXT": "About Cloud Service icon",
      "BRANDING_BAR_TOOLBAR_LABEL": "Toolbar",
      "BRANDING_BAR_APP_NAME_APM": "Application Performance Monitoring",
      "BRANDING_BAR_APP_NAME_IT_ANALYTICS": "IT Analytics",
      "BRANDING_BAR_APP_NAME_LOG_ANALYTICS": "Log Analytics",
      "BRANDING_BAR_APP_NAME_DASHBOARD": "Dashboards",
      "BRANDING_BAR_APP_NAME_TENANT_MANAGEMENT_UI":"Set up Oracle Management Cloud",
      "BRANDING_BAR_APP_NAME_MONITORING": "Infrastructure Monitoring",
      "BRANDING_BAR_APP_NAME_SECURITY_ANALYTICS": "Security Monitoring and Analytics",
      "BRANDING_BAR_APP_NAME_COMPLIANCE": "Compliance",
      "BRANDING_BAR_APP_NAME_ORCHESTRATION": "Orchestration",
      "BRANDING_BAR_MESSAGE_BOX_ICON_ALT_TEXT_ERROR":"Error",
      "BRANDING_BAR_MESSAGE_BOX_ICON_ALT_TEXT_WARN":"Warning",
      "BRANDING_BAR_MESSAGE_BOX_ICON_ALT_TEXT_CONFIRM":"Confirmation",
      "BRANDING_BAR_MESSAGE_BOX_ICON_ALT_TEXT_INFO":"Information",
      "BRANDING_BAR_MESSAGE_BOX_ICON_ALT_TEXT_CLEAR":"Clear",
      "BRANDING_BAR_MESSAGE_BOX_TEXT_SHOW_MORE":"More...",
      "BRANDING_BAR_MESSAGE_BOX_TEXT_SHOW_FIRST":"Show first {0} only",
      "BRANDING_BAR_MESSAGE_BOX_TITLE_SHOW_MORE":"Click to show all messages",
      "BRANDING_BAR_MESSAGE_BOX_TITLE_SHOW_FIRST":"Click to show first {0} messages only",
      "BRANDING_BAR_CLOUD_SERVICE_NAME_APM": "APM",
      "BRANDING_BAR_CLOUD_SERVICE_NAME_SA": "Security",
      "BRANDING_BAR_SESSION_TIMEOUT_DIALOG_TILE": "Session Expired",
      "BRANDING_BAR_SESSION_TIMEOUT_MSG": "Your current session has expired. Click \'OK\' and sign in again.",
      "BRANDING_BAR_SESSION_TIMEOUT_DIALOG_BTN_OK": "OK",
      "WIDGET_SELECTOR_DEFAULT_DIALOG_TITLE": "Open",
      "WIDGET_SELECTOR_WIDGET_GROUP_LABEL": "Widget Group",
      "WIDGET_SELECTOR_SEARCH_BOX_PLACEHOLDER": " Search widgets.",
      "WIDGET_SELECTOR_SEARCH_BTN_LABEL": "Search",
      "WIDGET_SELECTOR_CLEAR_BTN_LABEL": "Clear",
      "WIDGET_SELECTOR_DEFAULT_AFFIRMATIVE_BTN_LABEL": "Open",
      "WIDGET_SELECTOR_TIME_YEARS": "year",
      "WIDGET_SELECTOR_TIME_YEAR": "years",
      "WIDGET_SELECTOR_TIME_MONTHS": "months",
      "WIDGET_SELECTOR_TIME_MONTH": "month",
      "WIDGET_SELECTOR_TIME_DAYS": "days",
      "WIDGET_SELECTOR_TIME_DAY": "day",
      "WIDGET_SELECTOR_TIME_HOURS": "hours",
      "WIDGET_SELECTOR_TIME_HOUR": "hour",
      "WIDGET_SELECTOR_TIME_MINS": "minutes",
      "WIDGET_SELECTOR_TIME_MIN": "minute",
      "WIDGET_SELECTOR_TIME_DIFF_A_MOMENT": "a moment",
      "WIDGET_SELECTOR_TIME_DIFF_AGO": "ago",
      "WIDGET_SELECTOR_WIDGET_GROUP_ALL": "All",
      "WIDGET_SELECTOR_WIDGET_NAVI_SCREENSHOT_TITLE": "Screen Shot",
      "WIDGET_SELECTOR_WIDGET_NAVI_DESC_TITLE": "Description",
      "WIDGET_SELECTOR_WIDGETS_LOADING_HINT": "Loading...",
      "BRANDING_BAR_MESSAGE_AJAX_RETRYING_SUMMARY":"Not connected.",
      "BRANDING_BAR_MESSAGE_AJAX_RETRYING_DETAIL":"Retrying to connect to your cloud service now...",
      "BRANDING_BAR_MESSAGE_AJAX_RETRY_FAIL_SUMMARY":"Oracle Management Cloud is unreachable.",
      "BRANDING_BAR_MESSAGE_AJAX_RETRY_FAIL_DETAIL":"Try again later.",
       //datetime picker
      "DATETIME_PICKER_DROP_DOWN": "Drop Down",
      "DATATIME_PICKER_TF_INDICATOR_LABEL": "Time filter indicator",
      "DATETIME_PICKER_TIME_FILTER": "Time Filter",
      "DATETIME_FILTER_TIME_FILTER_ICON_TITLE": "Click to show time filter settings",
      "DATETIME_PICKER_START_DATE_LABEL": "Start Date",
      "DATETIME_PICKER_START_TIME_LABEL": "Start Time",
      "DATETIME_PICKER_END_DATE_LABEL": "End Date",
      "DATETIME_PICKER_END_TIME_LABEL": "End Time",
      "DATETIME_PICKER_TIME_PERIOD_OPTION_LAST_15_MINS": "Last 15 mins",
      "DATETIME_PICKER_TIME_PERIOD_OPTION_LAST_30_MINS": "Last 30 mins",
      "DATETIME_PICKER_TIME_PERIOD_OPTION_LAST_60_MINS": "Last hour",
      "DATETIME_PICKER_TIME_PERIOD_OPTION_LAST_4_HOURS": "Last 4 hours",
      "DATETIME_PICKER_TIME_PERIOD_OPTION_LAST_6_HOURS": "Last 6 hours",
      "DATETIME_PICKER_TIME_PERIOD_OPTION_LAST_1_DAY": "Last day",
      "DATETIME_PICKER_TIME_PERIOD_OPTION_LAST_7_DAYS": "Last week",
      "DATETIME_PICKER_TIME_PERIOD_OPTION_LAST_14_DAYS": "Last 14 days",
      "DATETIME_PICKER_TIME_PERIOD_OPTION_LAST_30_DAYS": "Last 30 days",
      "DATETIME_PICKER_TIME_PERIOD_OPTION_LAST_90_DAYS": "Last 90 days",
      "DATETIME_PICKER_TIME_PERIOD_OPTION_LAST_1_YEAR": "Last year",
      "DATETIME_PICKER_TIME_PERIOD_OPTION_CUSTOM": "Custom",
      "DATETIME_PICKER_TIME_PERIOD_OPTION_LATEST": "Latest",
      "DATETIME_PICKER_TIME_PERIOD_OPTION_RECENT": "Recent",
      "DATETIME_PICKER_BUTTONS_APPLY_BUTTON": "Apply",
      "DATETIME_PICKER_BUTTONS_CANCEL_BUTTON": "Cancel",
      "DATETIME_PICKER_TIME_RANGE": "Time Range",
      "DATETIME_PICKER_ERROR": "Error!",
      "DATETIME_PICKER_FORMAT_ERROR_MSG": "Please enter valid \"mm/dd/yyyy\" for date or \"hh:mm AM/PM\" for time.",
      "DATETIME_PICKER_TIME_VALIDATE_ERROR_MSG": "The start date/time is after the end date/time.",
      "DATETIME_PICKER_BEYOND_WINDOW_LIMIT_ERROR_MSG": "The selected time range exceeds the maximum time range of ",
      "DATETIME_PICKER_WINDOW_SIZE_WITH_DAYS": "{0} day(s) {1} hour(s) {2} minute(s).",
      "DATETIME_PICKER_WINDOW_SIZE_WITH_HOURS": "{0} hour(s) {1} minute(s).",
      "DATETIME_PICKER_WINDOW_SIZE_WITH_MINUTES": "{0} minute(s).",
      "DATETIME_PICKER_SHOW_TODAY": "Today",
      "DATETIME_PICKER_SHOW_YESTERDAY": "Yesterday",
      "DATETIME_PICKER_TIME_FILTER_INFO_HOURS_EXCLUDED": "Hours excluded: ",
      "DATETIME_PICKER_TIME_FILTER_INFO_DAYS_EXCLUDED": "Days excluded: ",
      "DATETIME_PICKER_TIME_FILTER_INFO_MONTHS_EXCLUDED": "Months excluded: ",


      //time filter
      "TIME_FILTER_TITLE": "Filters",
      "TIME_FILTER_TIME_LABEL": "Time",
      "TIME_FILTER_TIME_HINT": "Hint : Enter time ranges you want to include in 24 hr format. For multiple time ranges separate them with ',' Ex: 1-7,13-17",
      "TIME_FILTER_DAYS_LABEL": "Days",
      "TIME_FILTER_MONTHS_LABEL": "Months",
      "TIME_FILTER_OPTION_ALL": "All",
      "TIME_FILTER_HOURS_FILTER_ERRMSG": "Time range format invalid. Re-enter time range(s).",
      "TIME_FILTER_DAYS_FILTER_ERRMSG": "Select at least one day.",
      "TIME_FILTER_MONTHS_FILTER_ERRMSG": "Select at least one month."
});

