Rem --DDL change during upgrade

Rem --upgrade increaseby
SET FEEDBACK ON
SET SERVEROUTPUT ON
DECLARE
  v_max_tileId INTEGER;
BEGIN
  SELECT MAX(tile_Id) INTO v_max_tileId FROM EMS_DASHBOARD_TILE;
  EXECUTE IMMEDIATE 'DROP SEQUENCE EMS_DASHBOARD_TILE_SEQ';
  EXECUTE IMMEDIATE 'CREATE SEQUENCE EMS_DASHBOARD_TILE_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH '||(v_max_tileId+20)||' CACHE 20 ORDER  NOCYCLE';
  DBMS_OUTPUT.PUT_LINE('Schema object: EMS_DASHBOARD_TILE_SEQ upgraded');
END;
/

