DEFINE TENANT_ID = '&1'
SET FEEDBACK ON
SET SERVEROUTPUT ON

DECLARE
OOB_DB_CONF_STOR CONSTANT EMS_DASHBOARD.NAME%TYPE:='Database Configuration and Storage By Version';
OOB_ENT_OV CONSTANT EMS_DASHBOARD.NAME%TYPE:='Enterprise Overview';
OOB_HOST_INV CONSTANT EMS_DASHBOARD.NAME%TYPE:='Host Inventory By Platform';
OOB_TOP25_WLS_HEAP CONSTANT EMS_DASHBOARD.NAME%TYPE:='Top 25 WebLogic Servers by Heap Usage';
OOB_TOP25_WLS_LOAD CONSTANT EMS_DASHBOARD.NAME%TYPE:='Top 25 WebLogic Servers by Load';
OOB_TOP25_DB CONSTANT EMS_DASHBOARD.NAME%TYPE:='Top 25 Databases by Resource Consumption';
OOB_WLS_SDK CONSTANT EMS_DASHBOARD.NAME%TYPE:='WebLogic Servers by JDK Version';
BEGIN
DELETE FROM EMS_DASHBOARD_TILE WHERE TENANT_ID = '&TENANT_ID'
  AND DASHBOARD_ID IN
  (SELECT DASHBOARD_ID FROM EMS_DASHBOARD WHERE TENANT_ID = '&TENANT_ID' AND DASHBOARD_ID<=1000 and NAME IN 
(OOB_DB_CONF_STOR
,OOB_ENT_OV
,OOB_HOST_INV
,OOB_TOP25_DB
,OOB_TOP25_WLS_HEAP
,OOB_TOP25_WLS_LOAD
,OOB_WLS_SDK
)
  );

DELETE FROM EMS_DASHBOARD_LAST_ACCESS WHERE TENANT_ID = '&TENANT_ID'
  AND DASHBOARD_ID IN
  (SELECT DASHBOARD_ID FROM EMS_DASHBOARD WHERE TENANT_ID = '&TENANT_ID' AND DASHBOARD_ID<=1000 and NAME IN 
(OOB_DB_CONF_STOR
,OOB_ENT_OV
,OOB_HOST_INV
,OOB_TOP25_DB
,OOB_TOP25_WLS_HEAP
,OOB_TOP25_WLS_LOAD
,OOB_WLS_SDK
)
  );

DELETE FROM EMS_DASHBOARD_USER_OPTIONS WHERE TENANT_ID = '&TENANT_ID' 
  AND DASHBOARD_ID IN
  (SELECT DASHBOARD_ID FROM EMS_DASHBOARD WHERE TENANT_ID = '&TENANT_ID' AND DASHBOARD_ID<=1000 and NAME IN 
(OOB_DB_CONF_STOR
,OOB_ENT_OV
,OOB_HOST_INV
,OOB_TOP25_DB
,OOB_TOP25_WLS_HEAP
,OOB_TOP25_WLS_LOAD
,OOB_WLS_SDK
)
  );

DELETE FROM EMS_DASHBOARD_SET WHERE TENANT_ID = '&TENANT_ID'
    AND SUB_DASHBOARD_ID IN
  (SELECT DASHBOARD_ID FROM EMS_DASHBOARD WHERE TENANT_ID = '&TENANT_ID' AND DASHBOARD_ID<=1000 and NAME IN
(OOB_DB_CONF_STOR
,OOB_ENT_OV
,OOB_HOST_INV
,OOB_TOP25_DB
,OOB_TOP25_WLS_HEAP
,OOB_TOP25_WLS_LOAD
,OOB_WLS_SDK
)
  );
  
DELETE FROM EMS_DASHBOARD WHERE TENANT_ID = '&TENANT_ID' and DASHBOARD_ID<=1000  and NAME IN 
(OOB_DB_CONF_STOR
,OOB_ENT_OV
,OOB_HOST_INV
,OOB_TOP25_DB
,OOB_TOP25_WLS_HEAP
,OOB_TOP25_WLS_LOAD
,OOB_WLS_SDK
);
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Remove out of box dashboards for BF successfully');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Failed to remove out of box dashboards for BF due to error '||SQLERRM);
    RAISE;
END;
/