Rem
Rem cleanup_oob.sql
Rem
Rem Copyright (c) 2013, 2014, 2015, 2016, 2017 Oracle and/or its affiliates.
Rem All rights reserved.
Rem
Rem    NAME
Rem      cleanup_oob.sql
Rem
Rem    DESCRIPTION
Rem      cleanup oob dashboards by application
Rem
Rem    NOTES
Rem      None
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    REX      05/05/17 - 
Rem

SET FEEDBACK ON
SET SERVEROUTPUT ON
DECLARE
    CONST_IS_SYSTEM             CONSTANT    NUMBER:=1;
    CONST_ORACLE                CONSTANT    VARCHAR2(128 BYTE):='Oracle';

BEGIN
DELETE FROM EMS_DASHBOARD_TILE_PARAMS WHERE TILE_ID IN
(
SELECT TILE_ID FROM EMS_DASHBOARD_TILE WHERE DASHBOARD_ID IN 
(SELECT EMS_DASHBOARD.DASHBOARD_ID FROM EMS_DASHBOARD WHERE IS_SYSTEM = CONST_IS_SYSTEM)
);

DELETE FROM EMS_DASHBOARD_TILE WHERE DASHBOARD_ID IN 
(
SELECT EMS_DASHBOARD.DASHBOARD_ID FROM EMS_DASHBOARD WHERE IS_SYSTEM = CONST_IS_SYSTEM
);

DELETE FROM EMS_DASHBOARD_USER_OPTIONS WHERE USER_NAME = CONST_ORACLE AND DASHBOARD_ID IN 
(
SELECT EMS_DASHBOARD.DASHBOARD_ID FROM EMS_DASHBOARD WHERE IS_SYSTEM = CONST_IS_SYSTEM
);

DELETE FROM EMS_DASHBOARD_SET WHERE DASHBOARD_SET_ID IN 
(
SELECT EMS_DASHBOARD.DASHBOARD_ID FROM EMS_DASHBOARD WHERE IS_SYSTEM = CONST_IS_SYSTEM
);

DELETE FROM EMS_DASHBOARD WHERE IS_SYSTEM = CONST_IS_SYSTEM;

DBMS_OUTPUT.PUT_LINE('OOB dashboards have been cleaned up succesfully!');

EXCEPTION
WHEN OTHERS THEN
  ROLLBACK;
  DBMS_OUTPUT.PUT_LINE('Failed to clean OOB dashboards due to ' || SQLERRM);
  RAISE;
END;
/