Rem ----------------------------------------------------------------
Rem 08/29/2017	REX	Created file
Rem
Rem ----------------------------------------------------------------

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EMS_DASHBOARD_RESOURCE_BUNDLE';
  DBMS_OUTPUT.PUT_LINE('EMS_DASHBOARD_RESOURCE_BUNDLE HAS BEEN DROPPED');
  EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -00942 THEN
         DBMS_OUTPUT.PUT_LINE('>>>DF DDL ERROR<<<');
         RAISE;
      END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE EMS_DASHBOARD_RESOURCE_BUNDLE
  (
    LANGUAGE_CODE                VARCHAR(2) NOT NULL,
    COUNTRY_CODE                 VARCHAR(4) NOT NULL,
    SERVICE_NAME                 VARCHAR(255) NOT NULL,
    SERVICE_VERSION              VARCHAR(255),
    PROPERTIES_FILE              NCLOB,
    LAST_MODIFICATION_DATE       TIMESTAMP NOT NULL,
    CONSTRAINT EMS_DASHBOARD_RESOURCE_B_PK PRIMARY KEY (LANGUAGE_CODE, COUNTRY_CODE, SERVICE_NAME) USING INDEX COMPRESS
  )';
  DBMS_OUTPUT.PUT_LINE('EMS_DASHBOARD_RESOURCE_BUNDLE HAS BEEN CREATED');
  EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -00955 THEN
         DBMS_OUTPUT.PUT_LINE('>>>DF DDL ERROR<<<');
         RAISE;
      END IF;
END;
/

