  SET FEEDBACK ON
  SET SERVEROUTPUT ON
  DEFINE TENANT_ID ='&1'
DECLARE
v_count     INTEGER;
V_TENANT_ID NUMBER(38,0);
V_TID NUMBER(38,0) := '&TENANT_ID';

CURSOR TENANT_CURSOR IS
    SELECT DISTINCT TENANT_ID FROM EMS_DASHBOARD ORDER BY TENANT_ID;

BEGIN

  LOOP
     IF (V_TID<>-1) THEN
        V_TENANT_ID:=V_TID;
     ELSE
       IF NOT TENANT_CURSOR%ISOPEN THEN
        OPEN TENANT_CURSOR;
       END IF;
       FETCH TENANT_CURSOR INTO V_TENANT_ID;
       EXIT WHEN TENANT_CURSOR%NOTFOUND;     
     END IF;  
     
    SELECT COUNT(*) INTO v_count FROM EMS_DASHBOARD
    WHERE DASHBOARD_ID = 23  OR DASHBOARD_ID = 22 AND TENANT_ID = V_TENANT_ID;
    IF v_count > 0 THEN
       DELETE FROM EMS_DASHBOARD_USER_OPTIONS WHERE DASHBOARD_ID = 23 AND TENANT_ID = V_TENANT_ID;
       DELETE FROM EMS_DASHBOARD_TILE WHERE DASHBOARD_ID = 23 AND TENANT_ID = V_TENANT_ID;
       DELETE FROM EMS_DASHBOARD_SET WHERE DASHBOARD_SET_ID = 23 AND TENANT_ID = V_TENANT_ID;
       DELETE FROM EMS_DASHBOARD WHERE DASHBOARD_ID = 23 AND TENANT_ID = V_TENANT_ID;

       DELETE FROM EMS_DASHBOARD_USER_OPTIONS WHERE DASHBOARD_ID = 22 AND TENANT_ID = V_TENANT_ID;
       DELETE FROM EMS_DASHBOARD_TILE WHERE DASHBOARD_ID = 22 AND TENANT_ID = V_TENANT_ID;
       DELETE FROM EMS_DASHBOARD WHERE DASHBOARD_ID = 22 AND TENANT_ID = V_TENANT_ID;
       DBMS_OUTPUT.PUT_LINE('COS DASHBOARD WITH ID 22 and 23 HAS BEEN DELETED SUCCESSFULLY! for tenant:'||V_TENANT_ID);
    ELSE
       DBMS_OUTPUT.PUT_LINE('COS DASHBOARD WITH ID 22 and 23 DONNOT EXIST NO NEED NOT TO BE DELETED for tenant:'||V_TENANT_ID);
    END IF;
     IF (V_TID<>-1) THEN
        EXIT;
     END IF;
  END LOOP;
  IF TENANT_CURSOR%ISOPEN THEN
    CLOSE TENANT_CURSOR;
  END IF;

  commit;
  DBMS_OUTPUT.PUT_LINE('Upgrade is done');    
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      DBMS_OUTPUT.PUT_LINE('Failed to update the sql due to '||SQLERRM);
      RAISE;
  END;
  /
