Rem
Rem Copyright (c) 2014, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    DESCRIPTION
REM         Drop all tables for EMaaS Dashboard
REM


prompt Drop EMS_DASHBOARD Triggers 


BEGIN
   EXECUTE IMMEDIATE 'DROP TRIGGER EMS_DASHBOARD_TR';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TRIGGER EMS_DASHBOARD_TILE_TR';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -4080 THEN
         RAISE;
      END IF;
END;
/

prompt Drop EMS_DASHBOARD Sequences 


BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE EMS_DASHBOARD_SEQ';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE EMS_DASHBOARD_TILE_SEQ';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/

prompt Drop EMS_DASHBOARD Tables 

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE EMS_DASHBOARD_LAST_ACCESS PURGE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE EMS_DASHBOARD_TILE_PARAMS PURGE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE EMS_DASHBOARD_TILE PURGE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE EMS_DASHBOARD_FAVORITE PURGE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE EMS_DASHBOARD PURGE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE EMS_PREFERENCE PURGE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


